DROP TABLE CCRS_PM_DEPB;/*SkipError*/

CREATE TABLE CCRS_PM_DEPB(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE VARCHAR2(10),
    JRJGBM CHAR(14),
    KHLX CHAR(2),
    CKZHDM VARCHAR2(60),
    CKXYDM VARCHAR2(60),
    CPLB VARCHAR2(6),
    CKXYQSR VARCHAR2(10),
    CKXYDQR VARCHAR2(10),
    CKBZ CHAR(3),
    CKYE NUMBER(17,2),
    LLSFGD CHAR(4),
    LLSP NUMBER(13,5),
    CKRDM VARCHAR2(38),
    CKRMC VARCHAR2(120),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_DEPB IS '存款余额报文';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_DEPB.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_DEPB.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_DEPB.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_DEPB.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_DEPB.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_DEPB.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_DEPB.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_DEPB.KHLX IS '客户类型';
COMMENT ON COLUMN CCRS_PM_DEPB.CKZHDM IS '存款账户代码';
COMMENT ON COLUMN CCRS_PM_DEPB.CKXYDM IS '存款协议代码';
COMMENT ON COLUMN CCRS_PM_DEPB.CPLB IS '产品类别';
COMMENT ON COLUMN CCRS_PM_DEPB.CKXYQSR IS '存款协议起始日';
COMMENT ON COLUMN CCRS_PM_DEPB.CKXYDQR IS '存款协议到期日';
COMMENT ON COLUMN CCRS_PM_DEPB.CKBZ IS '存款币种';
COMMENT ON COLUMN CCRS_PM_DEPB.CKYE IS '存款余额';
COMMENT ON COLUMN CCRS_PM_DEPB.LLSFGD IS '利率是否固定';
COMMENT ON COLUMN CCRS_PM_DEPB.LLSP IS '利率水平';
COMMENT ON COLUMN CCRS_PM_DEPB.CKRDM IS '存款人代码';
COMMENT ON COLUMN CCRS_PM_DEPB.CKRMC IS '存款人名称';
COMMENT ON COLUMN CCRS_PM_DEPB.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_DEPB.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_DEPB.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_DEPB.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_DEPB.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_DEPB.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_DEPB.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_DEPB.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_DEPB.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_DEPB.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_DEPB.RSV5 IS '备用5';


DROP TABLE CCRS_PM_ETLB;/*SkipError*/

CREATE TABLE CCRS_PM_ETLB(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE VARCHAR2(10),
    JRJGBM CHAR(14),
    KHLX CHAR(1),
    JKRDM VARCHAR2(38),
    JKRHY CHAR(1),
    JKRDQDM CHAR(12),
    JKRJJCF CHAR(5),
    JKRGM CHAR(4),
    WTDKJJBM CHAR(35),
    WTDKSJTX CHAR(4),
    WTDKFFRQ VARCHAR2(10),
    WTDKDQRQ VARCHAR2(10),
    WTDKZQDQRQ VARCHAR2(10),
    WTDKBZ CHAR(3),
    WTDKYE NUMBER(17,2),
    LLSFGD CHAR(4),
    LLSP NUMBER(13,5),
    SXFJE_CNY NUMBER(17,2),
    DKDBFS VARCHAR2(3),
    DKZL CHAR(4),
    DKZT CHAR(4),
    WTRLX CHAR(1),
    WTRZJDM VARCHAR2(38),
    WTRHY CHAR(1),
    WTRDQDM CHAR(12),
    WTRJJCF CHAR(12),
    QYWTRQYGM CHAR(4),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_ETLB IS '委托贷款余额报文';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_ETLB.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_ETLB.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_ETLB.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_ETLB.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_ETLB.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_ETLB.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_ETLB.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_ETLB.KHLX IS '客户类型';
COMMENT ON COLUMN CCRS_PM_ETLB.JKRDM IS '借款人代码';
COMMENT ON COLUMN CCRS_PM_ETLB.JKRHY IS '借款人行业';
COMMENT ON COLUMN CCRS_PM_ETLB.JKRDQDM IS '借款人地区代码';
COMMENT ON COLUMN CCRS_PM_ETLB.JKRJJCF IS '借款人经济成分';
COMMENT ON COLUMN CCRS_PM_ETLB.JKRGM IS '借款人规模';
COMMENT ON COLUMN CCRS_PM_ETLB.WTDKJJBM IS '委托贷款借据编码';
COMMENT ON COLUMN CCRS_PM_ETLB.WTDKSJTX IS '委托贷款实际投向';
COMMENT ON COLUMN CCRS_PM_ETLB.WTDKFFRQ IS '委托贷款发放日期';
COMMENT ON COLUMN CCRS_PM_ETLB.WTDKDQRQ IS '委托贷款到期日期';
COMMENT ON COLUMN CCRS_PM_ETLB.WTDKZQDQRQ IS '委托贷款展期到期日期';
COMMENT ON COLUMN CCRS_PM_ETLB.WTDKBZ IS '委托贷款币种';
COMMENT ON COLUMN CCRS_PM_ETLB.WTDKYE IS '委托贷款余额';
COMMENT ON COLUMN CCRS_PM_ETLB.LLSFGD IS '利率是否固定';
COMMENT ON COLUMN CCRS_PM_ETLB.LLSP IS '利率水平';
COMMENT ON COLUMN CCRS_PM_ETLB.SXFJE_CNY IS '手续费金额折人民币';
COMMENT ON COLUMN CCRS_PM_ETLB.DKDBFS IS '贷款担保方式';
COMMENT ON COLUMN CCRS_PM_ETLB.DKZL IS '贷款质量';
COMMENT ON COLUMN CCRS_PM_ETLB.DKZT IS '贷款状态';
COMMENT ON COLUMN CCRS_PM_ETLB.WTRLX IS '委托人类型';
COMMENT ON COLUMN CCRS_PM_ETLB.WTRZJDM IS '委托人证件代码';
COMMENT ON COLUMN CCRS_PM_ETLB.WTRHY IS '委托人行业';
COMMENT ON COLUMN CCRS_PM_ETLB.WTRDQDM IS '委托人地区代码';
COMMENT ON COLUMN CCRS_PM_ETLB.WTRJJCF IS '委托人经济成分';
COMMENT ON COLUMN CCRS_PM_ETLB.QYWTRQYGM IS '企业委托人企业规模';
COMMENT ON COLUMN CCRS_PM_ETLB.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_ETLB.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_ETLB.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_ETLB.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_ETLB.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_ETLB.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_ETLB.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_ETLB.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_ETLB.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_ETLB.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_ETLB.RSV5 IS '备用5';


DROP TABLE CCRS_PM_ETLF;/*SkipError*/

CREATE TABLE CCRS_PM_ETLF(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE VARCHAR2(10),
    JRJGBM CHAR(14),
    KHLX CHAR(1),
    JKRDM VARCHAR2(38),
    JKRHY CHAR(1),
    JKRDQDM CHAR(12),
    JKRJJCF CHAR(5),
    JKRGM CHAR(4),
    WTDKJJBM VARCHAR2(35),
    WTDKSJTX CHAR(4),
    WTDKFFRQ VARCHAR2(10),
    WTDKDQRQ VARCHAR2(10),
    WTDKBZ CHAR(3),
    WTDKFSJE NUMBER(17,2),
    LLSFGD CHAR(4),
    LLSP NUMBER(13,5),
    SXFJE_CNY NUMBER(17,2),
    DKDBFS VARCHAR2(3),
    WTRLX CHAR(1),
    WTRZJDM VARCHAR2(38),
    WTRHY CHAR(1),
    WTRDQDM CHAR(12),
    WTRJJCF CHAR(5),
    QYWTRQYGM CHAR(4),
    FFSHBZ CHAR(1),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_ETLF IS '委托贷款发生额报文';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_ETLF.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_ETLF.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_ETLF.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_ETLF.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_ETLF.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_ETLF.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_ETLF.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_ETLF.KHLX IS '客户类型';
COMMENT ON COLUMN CCRS_PM_ETLF.JKRDM IS '借款人代码';
COMMENT ON COLUMN CCRS_PM_ETLF.JKRHY IS '借款人行业';
COMMENT ON COLUMN CCRS_PM_ETLF.JKRDQDM IS '借款人地区代码';
COMMENT ON COLUMN CCRS_PM_ETLF.JKRJJCF IS '借款人经济成分';
COMMENT ON COLUMN CCRS_PM_ETLF.JKRGM IS '借款人规模';
COMMENT ON COLUMN CCRS_PM_ETLF.WTDKJJBM IS '委托贷款借据编码';
COMMENT ON COLUMN CCRS_PM_ETLF.WTDKSJTX IS '委托贷款实际投向';
COMMENT ON COLUMN CCRS_PM_ETLF.WTDKFFRQ IS '委托贷款发放日期';
COMMENT ON COLUMN CCRS_PM_ETLF.WTDKDQRQ IS '委托贷款到期日期';
COMMENT ON COLUMN CCRS_PM_ETLF.WTDKBZ IS '委托贷款币种';
COMMENT ON COLUMN CCRS_PM_ETLF.WTDKFSJE IS '委托贷款发生金额';
COMMENT ON COLUMN CCRS_PM_ETLF.LLSFGD IS '利率是否固定';
COMMENT ON COLUMN CCRS_PM_ETLF.LLSP IS '利率水平';
COMMENT ON COLUMN CCRS_PM_ETLF.SXFJE_CNY IS '手续费金额折人民币';
COMMENT ON COLUMN CCRS_PM_ETLF.DKDBFS IS '贷款担保方式';
COMMENT ON COLUMN CCRS_PM_ETLF.WTRLX IS '委托人类型';
COMMENT ON COLUMN CCRS_PM_ETLF.WTRZJDM IS '委托人证件代码';
COMMENT ON COLUMN CCRS_PM_ETLF.WTRHY IS '委托人行业';
COMMENT ON COLUMN CCRS_PM_ETLF.WTRDQDM IS '委托人地区代码';
COMMENT ON COLUMN CCRS_PM_ETLF.WTRJJCF IS '委托人经济成分';
COMMENT ON COLUMN CCRS_PM_ETLF.QYWTRQYGM IS '企业委托人企业规模';
COMMENT ON COLUMN CCRS_PM_ETLF.FFSHBZ IS '发放收回标志';
COMMENT ON COLUMN CCRS_PM_ETLF.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_ETLF.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_ETLF.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_ETLF.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_ETLF.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_ETLF.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_ETLF.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_ETLF.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_ETLF.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_ETLF.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_ETLF.RSV5 IS '备用5';


DROP TABLE CCRS_PM_LOAB;/*SkipError*/

CREATE TABLE CCRS_PM_LOAB(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE VARCHAR2(10),
    JRJGBM CHAR(14),
    KHLX CHAR(1),
    JKRDM VARCHAR2(38),
    DKZTHYLB CHAR(1),
    JKRZCDBM CHAR(12),
    QYCZRJJCF CHAR(5),
    QYGM CHAR(4),
    DKJJBM VARCHAR2(35),
    CPLB VARCHAR2(6),
    DKSJTX CHAR(4),
    DKFFRQ VARCHAR2(10),
    DKDQRQ VARCHAR2(10),
    ZQDQRQ VARCHAR2(10),
    DKBZ CHAR(3),
    DKYE NUMBER(17,2),
    LLSFGD CHAR(4),
    LLSP NUMBER(13,5),
    DKDBFS VARCHAR2(3),
    DKZL CHAR(4),
    DKZT CHAR(4),
    SXJE NUMBER(17,2),
    SXBS CHAR(2),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_LOAB IS '贷款余额报文';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_LOAB.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_LOAB.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_LOAB.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_LOAB.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_LOAB.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_LOAB.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_LOAB.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_LOAB.KHLX IS '客户类型';
COMMENT ON COLUMN CCRS_PM_LOAB.JKRDM IS '借款人代码';
COMMENT ON COLUMN CCRS_PM_LOAB.DKZTHYLB IS '贷款主体行业类别';
COMMENT ON COLUMN CCRS_PM_LOAB.JKRZCDBM IS '借款人注册地编码';
COMMENT ON COLUMN CCRS_PM_LOAB.QYCZRJJCF IS '企业出资人经济成分';
COMMENT ON COLUMN CCRS_PM_LOAB.QYGM IS '企业规模';
COMMENT ON COLUMN CCRS_PM_LOAB.DKJJBM IS '贷款借据编码';
COMMENT ON COLUMN CCRS_PM_LOAB.CPLB IS '产品类别';
COMMENT ON COLUMN CCRS_PM_LOAB.DKSJTX IS '贷款实际投向';
COMMENT ON COLUMN CCRS_PM_LOAB.DKFFRQ IS '贷款发放日期';
COMMENT ON COLUMN CCRS_PM_LOAB.DKDQRQ IS '贷款到期日期';
COMMENT ON COLUMN CCRS_PM_LOAB.ZQDQRQ IS '展期到期日期';
COMMENT ON COLUMN CCRS_PM_LOAB.DKBZ IS '贷款币种';
COMMENT ON COLUMN CCRS_PM_LOAB.DKYE IS '贷款余额';
COMMENT ON COLUMN CCRS_PM_LOAB.LLSFGD IS '利率是否固定';
COMMENT ON COLUMN CCRS_PM_LOAB.LLSP IS '利率水平';
COMMENT ON COLUMN CCRS_PM_LOAB.DKDBFS IS '贷款担保方式';
COMMENT ON COLUMN CCRS_PM_LOAB.DKZL IS '贷款质量';
COMMENT ON COLUMN CCRS_PM_LOAB.DKZT IS '贷款状态';
COMMENT ON COLUMN CCRS_PM_LOAB.SXJE IS '授信金额';
COMMENT ON COLUMN CCRS_PM_LOAB.SXBS IS '属性标识';
COMMENT ON COLUMN CCRS_PM_LOAB.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_LOAB.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_LOAB.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_LOAB.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_LOAB.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_LOAB.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_LOAB.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_LOAB.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_LOAB.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_LOAB.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_LOAB.RSV5 IS '备用5';


DROP TABLE CCRS_PM_LOAF;/*SkipError*/

CREATE TABLE CCRS_PM_LOAF(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE VARCHAR2(10),
    JRJGBM CHAR(14),
    KHLX CHAR(1),
    JKRDM VARCHAR2(38),
    DKZTHYLB CHAR(1),
    JKRZCDBM CHAR(12),
    QYCZRJJCF CHAR(5),
    QYGM CHAR(4),
    DKJJBM VARCHAR2(35),
    CPLB VARCHAR2(6),
    DKSJTX CHAR(4),
    DKFFRQ VARCHAR2(10),
    DKDQRQ VARCHAR2(10),
    DKSJZZRQ VARCHAR2(10),
    DKBZ CHAR(3),
    DKFSJE NUMBER(17,2),
    LLSFGD CHAR(4),
    LLSP NUMBER(13,5),
    DKDBFS VARCHAR2(3),
    DKZT CHAR(4),
    DKFFSHBS CHAR(1),
    SXJE NUMBER(17,2),
    SXBS CHAR(2),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_LOAF IS '贷款发生额报文';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_LOAF.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_LOAF.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_LOAF.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_LOAF.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_LOAF.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_LOAF.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_LOAF.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_LOAF.KHLX IS '客户类型';
COMMENT ON COLUMN CCRS_PM_LOAF.JKRDM IS '借款人代码';
COMMENT ON COLUMN CCRS_PM_LOAF.DKZTHYLB IS '贷款主体行业类别';
COMMENT ON COLUMN CCRS_PM_LOAF.JKRZCDBM IS '借款人注册地编码';
COMMENT ON COLUMN CCRS_PM_LOAF.QYCZRJJCF IS '企业出资人经济成分';
COMMENT ON COLUMN CCRS_PM_LOAF.QYGM IS '企业规模';
COMMENT ON COLUMN CCRS_PM_LOAF.DKJJBM IS '贷款借据编码';
COMMENT ON COLUMN CCRS_PM_LOAF.CPLB IS '产品类别';
COMMENT ON COLUMN CCRS_PM_LOAF.DKSJTX IS '贷款实际投向';
COMMENT ON COLUMN CCRS_PM_LOAF.DKFFRQ IS '贷款发放日期';
COMMENT ON COLUMN CCRS_PM_LOAF.DKDQRQ IS '贷款到期日期';
COMMENT ON COLUMN CCRS_PM_LOAF.DKSJZZRQ IS '贷款实际终止日期';
COMMENT ON COLUMN CCRS_PM_LOAF.DKBZ IS '贷款币种';
COMMENT ON COLUMN CCRS_PM_LOAF.DKFSJE IS '贷款发生金额';
COMMENT ON COLUMN CCRS_PM_LOAF.LLSFGD IS '利率是否固定';
COMMENT ON COLUMN CCRS_PM_LOAF.LLSP IS '利率水平';
COMMENT ON COLUMN CCRS_PM_LOAF.DKDBFS IS '贷款担保方式';
COMMENT ON COLUMN CCRS_PM_LOAF.DKZT IS '贷款状态';
COMMENT ON COLUMN CCRS_PM_LOAF.DKFFSHBS IS '贷款发放收回标识';
COMMENT ON COLUMN CCRS_PM_LOAF.SXJE IS '授信金额';
COMMENT ON COLUMN CCRS_PM_LOAF.SXBS IS '属性标识';
COMMENT ON COLUMN CCRS_PM_LOAF.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_LOAF.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_LOAF.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_LOAF.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_LOAF.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_LOAF.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_LOAF.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_LOAF.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_LOAF.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_LOAF.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_LOAF.RSV5 IS '备用5';


drop table ccrs_ITF_LOAF;
create table ccrs_ITF_LOAF as select * from ccrs_PM_LOAF where 1=2;
drop table ccrs_BM_CHK_E_LOAF;
create table ccrs_BM_CHK_E_LOAF as select * from ccrs_BM_CHK_ERRORS;
alter table ccrs_ITF_LOAF modify DATA_DATE VARCHAR2(10);
alter table ccrs_ITF_LOAF modify DATA_RPT_DATE VARCHAR2(10);
alter table ccrs_ITF_LOAF modify SJRQ_DATE VARCHAR2(10);
alter table ccrs_ITF_LOAF modify DATA_CRT_DATE VARCHAR2(10);
alter table ccrs_ITF_LOAF modify DATA_CHG_DATE VARCHAR2(10);
alter table ccrs_ITF_LOAF modify DATA_APV_DATE VARCHAR2(10);
drop table ccrs_ITF_LOAB;
create table ccrs_ITF_LOAB as select * from ccrs_PM_LOAB where 1=2;
drop table ccrs_BM_CHK_E_LOAB;
create table ccrs_BM_CHK_E_LOAB as select * from ccrs_BM_CHK_ERRORS;
alter table ccrs_ITF_LOAB modify DATA_DATE VARCHAR2(10);
alter table ccrs_ITF_LOAB modify DATA_RPT_DATE VARCHAR2(10);
alter table ccrs_ITF_LOAB modify SJRQ_DATE VARCHAR2(10);
alter table ccrs_ITF_LOAB modify DATA_CRT_DATE VARCHAR2(10);
alter table ccrs_ITF_LOAB modify DATA_CHG_DATE VARCHAR2(10);
alter table ccrs_ITF_LOAB modify DATA_APV_DATE VARCHAR2(10);
drop table ccrs_ITF_DEPB;
create table ccrs_ITF_DEPB as select * from ccrs_PM_DEPB where 1=2;
drop table ccrs_BM_CHK_E_DEPB;
create table ccrs_BM_CHK_E_DEPB as select * from ccrs_BM_CHK_ERRORS;
alter table ccrs_ITF_DEPB modify DATA_DATE VARCHAR2(10);
alter table ccrs_ITF_DEPB modify DATA_RPT_DATE VARCHAR2(10);
alter table ccrs_ITF_DEPB modify SJRQ_DATE VARCHAR2(10);
alter table ccrs_ITF_DEPB modify DATA_CRT_DATE VARCHAR2(10);
alter table ccrs_ITF_DEPB modify DATA_CHG_DATE VARCHAR2(10);
alter table ccrs_ITF_DEPB modify DATA_APV_DATE VARCHAR2(10);
drop table ccrs_ITF_ETLF;
create table ccrs_ITF_ETLF as select * from ccrs_PM_ETLF where 1=2;
drop table ccrs_BM_CHK_E_ETLF;
create table ccrs_BM_CHK_E_ETLF as select * from ccrs_BM_CHK_ERRORS;
alter table ccrs_ITF_ETLF modify DATA_DATE VARCHAR2(10);
alter table ccrs_ITF_ETLF modify DATA_RPT_DATE VARCHAR2(10);
alter table ccrs_ITF_ETLF modify SJRQ_DATE VARCHAR2(10);
alter table ccrs_ITF_ETLF modify DATA_CRT_DATE VARCHAR2(10);
alter table ccrs_ITF_ETLF modify DATA_CHG_DATE VARCHAR2(10);
alter table ccrs_ITF_ETLF modify DATA_APV_DATE VARCHAR2(10);
drop table ccrs_ITF_ETLB;
create table ccrs_ITF_ETLB as select * from ccrs_PM_ETLB where 1=2;
drop table ccrs_BM_CHK_E_ETLB;
create table ccrs_BM_CHK_E_ETLB as select * from ccrs_BM_CHK_ERRORS;
alter table ccrs_ITF_ETLB modify DATA_DATE VARCHAR2(10);
alter table ccrs_ITF_ETLB modify DATA_RPT_DATE VARCHAR2(10);
alter table ccrs_ITF_ETLB modify SJRQ_DATE VARCHAR2(10);
alter table ccrs_ITF_ETLB modify DATA_CRT_DATE VARCHAR2(10);
alter table ccrs_ITF_ETLB modify DATA_CHG_DATE VARCHAR2(10);
alter table ccrs_ITF_ETLB modify DATA_APV_DATE VARCHAR2(10);