delete from GP_QC_RULE where DATA_ID in ('JS2771','JS2772','JS2773','JS2776','JS2777','JS2778','JS2779');
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2771', null, null, null, null, 'gfdr', 'CLDWDK', '贷款余额折人民币一般应在1000元至100亿元之间', '贷款余额折人民币一般应在1000元至100亿元之间', '表内逻辑校验', '人民银行', 'DKYEZRMBYE_AMT', '贷款余额折人民币余额', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value)){
                return ($value as BigDecimal) <= 100000000000 && ($value as BigDecimal) >= 1000
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2771', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2772', null, null, null, null, 'gfdr', 'FTYKHX', '授信额度一般不能大于1000亿', '授信额度一般不能大于1000亿', '表内逻辑校验', '人民银行', 'SXED_AMT', '授信额度', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value)){
                return ($value as BigDecimal) <= 100000000000
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2772', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2773', null, null, null, null, 'gfdr', 'FTYKHX', '已用额度一般不能大于1000亿', '已用额度一般不能大于1000亿', '表内逻辑校验', '人民银行', 'YYED_AMT', '已用额度', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value)){
                return ($value as BigDecimal) <= 100000000000
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2773', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2776', null, null, null, null, 'gfdr', 'DBHTXX', '担保合同金额折人民币一般应在1000元至1000亿元范围内', '担保合同金额折人民币一般应在1000元至1000亿元范围内', '表内逻辑校验', '人民银行', 'DBHTJEZRMB_AMT', '担保合同金额折人民币', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value)){
                return ($value as BigDecimal) <= 100000000000 && ($value as BigDecimal) >= 1000
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2776', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2777', null, null, null, null, 'gfdr', 'DBHTXX', '抵质押合同的抵质押率应大于等于1', '抵质押合同的抵质押率应大于等于1', '表内逻辑校验', '人民银行', 'DZYL', '抵质押率', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value)){
                return ($value as BigDecimal) >= 1
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2777', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2778', null, null, null, null, 'gfdr', 'DBWXX', '评估价值一般在1000元至100亿元范围内', '评估价值一般在1000元至100亿元范围内', '表内逻辑校验', '人民银行', 'PGJZ_AMT', '评估价值', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value)){
                return ($value as BigDecimal) <= 100000000000 && ($value as BigDecimal) >= 1000
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2778', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2779', null, null, null, null, 'gfdr', 'DBWXX', '当担保物票面价值不为空时，担保物票面价值一般在1000元至100亿元范围内', '当担保物票面价值不为空时，担保物票面价值一般在1000元至100亿元范围内', '表内逻辑校验', '人民银行', 'DBWPMJZ_AMT', '担保物票面价值', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value)){
                return ($value as BigDecimal) <= 100000000000 && ($value as BigDecimal) >= 1000
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2779', 'R', null, null, null);