
update GP_QC_RULE set rsv2='Q' where 1=1;
UPDATE GP_QC_RULE SET DATA_DATE = null, CORP_ID = null, ORG_ID = null, GROUP_ID = null, INQ_ORG_ID = 'ccrs', INQ_GROUP_ID = 'TYCDYE', RULE_DESC = '存单于当前上报期截止日期前已到期，存单实际到期日期不能为空', RULE_MESSAGE = '存单于当前上报期截止日期前已到期，存单实际到期日期不能为空', RULE_TYPE = '非空校验', RULE_SOURCE = '人民银行', FIELD = 'CDSJDQRQ_DATE', FIELD_NAME = '存单实际到期日期', TRIMMABLE = null, NULLABLE = 'Y', TYPE_ID = null, ENCODING = null, MIN_LENGTH = null, MAX_LENGTH = null, MIN_VALUE = null, MAX_VALUE = null, MAX_PRECISION = null, MIN_SCALE = null, MAX_SCALE = null, ENUMERATION = null, PATTERN = null, IN_ENTITY = null, IN_FIELD = null, EXISTS_SQL = null, DATA_HASH = null, SCRIPT = '
            if(CDXYDQRQ_DATE <= DATA_RPT_DATE){
                return isNotEmpty($value)
            }
            return true', BEAN = null, CHECK_FLAG = null, CHECK_DESC = null, CHECK_ERR_TYPE = null, NEXT_ACTION = null, DATA_STATUS = null, DATA_FLAG = null, DATA_OP = null, DATA_SOURCE = null, DATA_VERSION = null, DATA_REJ_DESC = null, DATA_DEL_DESC = null, DATA_CRT_USER = 'auto_generator', DATA_CRT_DATE = null, DATA_CRT_TIME = null, DATA_CHG_USER = null, DATA_CHG_DATE = null, DATA_CHG_TIME = null, DATA_APV_USER = null, DATA_APV_DATE = null, DATA_APV_TIME = null, RSV1 = 'FK0077', RSV2 = 'Q', RSV3 = 'R', RSV4 = null, RSV5 = null WHERE DATA_ID = 'FK0077';
UPDATE GP_QC_RULE SET DATA_DATE = null, CORP_ID = null, ORG_ID = null, GROUP_ID = null, INQ_ORG_ID = 'ccrs', INQ_GROUP_ID = 'TYCDFSE', RULE_DESC = '存单于当前上报期截止日期前已到期，存单实际到期日期不能为空', RULE_MESSAGE = '存单于当前上报期截止日期前已到期，存单实际到期日期不能为空', RULE_TYPE = '非空校验', RULE_SOURCE = '人民银行', FIELD = 'CDSJDQRQ_DATE', FIELD_NAME = '存单实际到期日期', TRIMMABLE = null, NULLABLE = 'Y', TYPE_ID = null, ENCODING = null, MIN_LENGTH = null, MAX_LENGTH = null, MIN_VALUE = null, MAX_VALUE = null, MAX_PRECISION = null, MIN_SCALE = null, MAX_SCALE = null, ENUMERATION = null, PATTERN = null, IN_ENTITY = null, IN_FIELD = null, EXISTS_SQL = null, DATA_HASH = null, SCRIPT = '
            if(CDXYDQRQ_DATE <= DATA_RPT_DATE){
                return isNotEmpty($value)
            }
            return true', BEAN = null, CHECK_FLAG = null, CHECK_DESC = null, CHECK_ERR_TYPE = null, NEXT_ACTION = null, DATA_STATUS = null, DATA_FLAG = null, DATA_OP = null, DATA_SOURCE = null, DATA_VERSION = null, DATA_REJ_DESC = null, DATA_DEL_DESC = null, DATA_CRT_USER = 'auto_generator', DATA_CRT_DATE = null, DATA_CRT_TIME = null, DATA_CHG_USER = null, DATA_CHG_DATE = null, DATA_CHG_TIME = null, DATA_APV_USER = null, DATA_APV_DATE = null, DATA_APV_TIME = null, RSV1 = 'FK0093', RSV2 = 'Q', RSV3 = 'R', RSV4 = null, RSV5 = null WHERE DATA_ID = 'FK0093';
UPDATE GP_QC_RULE SET DATA_DATE = null, CORP_ID = null, ORG_ID = null, GROUP_ID = null, INQ_ORG_ID = 'ccrs', INQ_GROUP_ID = 'DECDYE', RULE_DESC = '存单于当前上报期截止日期前已到期，存单实际到期日期不能为空', RULE_MESSAGE = '存单于当前上报期截止日期前已到期，存单实际到期日期不能为空', RULE_TYPE = '非空校验', RULE_SOURCE = '人民银行', FIELD = 'CDSJDQRQ_DATE', FIELD_NAME = '存单实际到期日期', TRIMMABLE = null, NULLABLE = 'Y', TYPE_ID = null, ENCODING = null, MIN_LENGTH = null, MAX_LENGTH = null, MIN_VALUE = null, MAX_VALUE = null, MAX_PRECISION = null, MIN_SCALE = null, MAX_SCALE = null, ENUMERATION = null, PATTERN = null, IN_ENTITY = null, IN_FIELD = null, EXISTS_SQL = null, DATA_HASH = null, SCRIPT = '
            if(CDXYDQRQ_DATE <= DATA_RPT_DATE){
                return isNotEmpty($value)
            }
            return true', BEAN = null, CHECK_FLAG = null, CHECK_DESC = null, CHECK_ERR_TYPE = null, NEXT_ACTION = null, DATA_STATUS = null, DATA_FLAG = null, DATA_OP = null, DATA_SOURCE = null, DATA_VERSION = null, DATA_REJ_DESC = null, DATA_DEL_DESC = null, DATA_CRT_USER = 'auto_generator', DATA_CRT_DATE = null, DATA_CRT_TIME = null, DATA_CHG_USER = null, DATA_CHG_DATE = null, DATA_CHG_TIME = null, DATA_APV_USER = null, DATA_APV_DATE = null, DATA_APV_TIME = null, RSV1 = 'FK0116', RSV2 = 'Q', RSV3 = 'R', RSV4 = null, RSV5 = null WHERE DATA_ID = 'FK0116';
UPDATE GP_QC_RULE SET DATA_DATE = null, CORP_ID = null, ORG_ID = null, GROUP_ID = null, INQ_ORG_ID = 'ccrs', INQ_GROUP_ID = 'DECDFSE', RULE_DESC = '存单于当前上报期截止日期前已到期，存单实际到期日期不能为空', RULE_MESSAGE = '存单于当前上报期截止日期前已到期，存单实际到期日期不能为空', RULE_TYPE = '非空校验', RULE_SOURCE = '人民银行', FIELD = 'CDSJDQRQ_DATE', FIELD_NAME = '存单实际到期日期', TRIMMABLE = null, NULLABLE = 'Y', TYPE_ID = null, ENCODING = null, MIN_LENGTH = null, MAX_LENGTH = null, MIN_VALUE = null, MAX_VALUE = null, MAX_PRECISION = null, MIN_SCALE = null, MAX_SCALE = null, ENUMERATION = null, PATTERN = null, IN_ENTITY = null, IN_FIELD = null, EXISTS_SQL = null, DATA_HASH = null, SCRIPT = '
            if(CDXYDQRQ_DATE <= DATA_RPT_DATE){
                return isNotEmpty($value)
            }
            return true', BEAN = null, CHECK_FLAG = null, CHECK_DESC = null, CHECK_ERR_TYPE = null, NEXT_ACTION = null, DATA_STATUS = null, DATA_FLAG = null, DATA_OP = null, DATA_SOURCE = null, DATA_VERSION = null, DATA_REJ_DESC = null, DATA_DEL_DESC = null, DATA_CRT_USER = 'auto_generator', DATA_CRT_DATE = null, DATA_CRT_TIME = null, DATA_CHG_USER = null, DATA_CHG_DATE = null, DATA_CHG_TIME = null, DATA_APV_USER = null, DATA_APV_DATE = null, DATA_APV_TIME = null, RSV1 = 'FK0136', RSV2 = 'Q', RSV3 = 'R', RSV4 = null, RSV5 = null WHERE DATA_ID = 'FK0136';

commit;