DELETE FROM GP_QC_RULE WHERE DATA_ID='MBT_210I2100A12002';

INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, "SQL", SQL_EXTRA_KEY, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES('MBT_210I2100A12002', '20200716', 'TESTCORP', '72', 'XD', NULL, NULL, '若账户信息记录中的“报告时点说明代码”为“20-账户关闭”时，信息记录的信息报告日期 T 与账户关闭日期 t 必须满足 T-t<30。', '若账户信息记录中的“报告时点说明代码”为“20-账户关闭”时，信息记录的信息报告日期 T 与账户关闭日期 t 必须满足 T-t<30。', NULL, 'BUSI', 'DATA_ID', NULL, NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import java.text.SimpleDateFormat
if (!isEmpty(B_RPT_DATE)&& !isEmpty(J_CLOSE_DATE)&&B_RPT_DATE_CODE=="20") {
   SimpleDateFormat format = new SimpleDateFormat("yyyyMMdd")
    String rptDate = B_RPT_DATE;
    def newdate = format.parse(rptDate)
    String openDate = J_CLOSE_DATE;
    def newdate1 = format.parse(openDate)
    long diffMilliseconds = newdate.getTime() - newdate1.getTime()
    BigDecimal diffDays = diffMilliseconds / (24 * 60 * 60 * 1000)
    if (diffDays>=30)
      return false
}
return true', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'mbtrule', '1');

DELETE FROM GP_QC_RULE_MAP WHERE DATA_ID='MBT_210I2100A12002';
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES('MBT_210I2100A12002', '20200716', 'TESTCORP', '72', 'XD', NULL, NULL, 'MBT_210_2019020101', 'MBT_210I2100A12002', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'mbtrule', NULL);
