UPDATE GP_QC_RULE SET DATA_DATE='20190628', CORP_ID='TESTCORP', ORG_ID='72', GROUP_ID='XD', INQ_ORG_ID=NULL, INQ_GROUP_ID=NULL, RULE_DESC='若账户信息记录中的“报告时点说明代码”为“10-新开户”时，账户信息记录的信息报告日期T与开户日期t必须满足T-t<30。', RULE_MESSAGE='若账户信息记录中的“报告时点说明代码”为“10-新开户”时，账户信息记录的信息报告日期T与开户日期t必须满足T-t<30。', RULE_TYPE=NULL, RULE_SOURCE='BUSI', FIELD='DATA_ID', FIELD_NAME=NULL, TRIMMABLE=NULL, NULLABLE='Y', TYPE_ID=NULL, ENCODING=NULL, MIN_LENGTH=NULL, MAX_LENGTH=NULL, MIN_VALUE=NULL, MAX_VALUE=NULL, MAX_PRECISION=NULL, MIN_SCALE=NULL, MAX_SCALE=NULL, ENUMERATION=NULL, PATTERN=NULL, IN_ENTITY=NULL, IN_FIELD=NULL, "SQL"=NULL, SQL_EXTRA_KEY=NULL, SCRIPT='import java.text.SimpleDateFormat
if (!isEmpty(B_RPT_DATE)&& !isEmpty(C_OPEN_DATE)&&B_RPT_DATE_CODE=="10") {
   SimpleDateFormat format = new SimpleDateFormat("yyyyMMdd")
    String rptDate = B_RPT_DATE;
    def newdate = format.parse(rptDate)
    String openDate = C_OPEN_DATE;
    def newdate1 = format.parse(openDate)
    long diffMilliseconds = newdate.getTime() - newdate1.getTime()
    BigDecimal diffDays = diffMilliseconds / (24 * 60 * 60 * 1000)
    if (diffDays>=30)
      return false
}
return true', BEAN=NULL, CHECK_FLAG=NULL, CHECK_DESC=NULL, CHECK_ERR_TYPE=NULL, NEXT_ACTION=NULL, DATA_STATUS=NULL, DATA_FLAG=NULL, DATA_OP=NULL, DATA_SOURCE=NULL, DATA_VERSION=NULL, DATA_REJ_DESC=NULL, DATA_DEL_DESC=NULL, DATA_CRT_USER=NULL, DATA_CRT_DATE=NULL, DATA_CRT_TIME=NULL, DATA_CHG_USER=NULL, DATA_CHG_DATE=NULL, DATA_CHG_TIME=NULL, DATA_APV_USER=NULL, DATA_APV_DATE=NULL, DATA_APV_TIME=NULL, RSV1='5a768fe23981452390adf89953c668e0', RSV2=NULL, RSV3=NULL, RSV4='mbtrule', RSV5='1' WHERE DATA_ID='MBT_210I2100A11I2100A1101I2100A1102';

DELETE FROM GP_QC_RULE WHERE DATA_ID='MBT_210I2100A12001';

INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, "SQL", SQL_EXTRA_KEY, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES('MBT_210I2100A12001', '20200716', 'TESTCORP', '72', 'XD', NULL, NULL, '若账户信息记录中的“报告时点说明代码”为“20-账户关闭”时，信息记录的信息报告日期 T 与账户关闭日期 t 必须满足 T-t<30。', '若账户信息记录中的“报告时点说明代码”为“20-账户关闭”时，信息记录的信息报告日期 T 与账户关闭日期 t 必须满足 T-t<30。', NULL, 'BUSI', 'DATA_ID', NULL, NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import java.text.SimpleDateFormat
if (!isEmpty(B_RPT_DATE)&& !isEmpty(H_CLOSE_DATE)&&B_RPT_DATE_CODE=="20") {
   SimpleDateFormat format = new SimpleDateFormat("yyyyMMdd")
    String rptDate = B_RPT_DATE;
    def newdate = format.parse(rptDate)
    String openDate = H_CLOSE_DATE;
    def newdate1 = format.parse(openDate)
    long diffMilliseconds = newdate.getTime() - newdate1.getTime()
    BigDecimal diffDays = diffMilliseconds / (24 * 60 * 60 * 1000)
    if (diffDays>=30)
      return false
}
return true', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'mbtrule', '1');

DELETE FROM GP_QC_RULE_MAP WHERE DATA_ID='MBT_210I2100A12001';
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES('MBT_210I2100A12001', '20200716', 'TESTCORP', '72', 'XD', NULL, NULL, 'MBT_210_2019020101', 'MBT_210I2100A12001', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'mbtrule', NULL);


UPDATE GP_QC_RULE SET DATA_DATE='20190620', CORP_ID='TESTCORP', ORG_ID='72', GROUP_ID='002', INQ_ORG_ID=NULL, INQ_GROUP_ID=NULL, RULE_DESC='若“账户状态”为“2-结束”，则“账户关闭日期”不能为空值。', RULE_MESSAGE='若“账户状态”为“2-结束”，则“账户关闭日期”不能为空值。', RULE_TYPE=NULL, RULE_SOURCE='BUSI', FIELD='DATA_ID', FIELD_NAME=NULL, TRIMMABLE=NULL, NULLABLE='Y', TYPE_ID=NULL, ENCODING=NULL, MIN_LENGTH=NULL, MAX_LENGTH=NULL, MIN_VALUE=NULL, MAX_VALUE=NULL, MAX_PRECISION=NULL, MIN_SCALE=NULL, MAX_SCALE=NULL, ENUMERATION=NULL, PATTERN=NULL, IN_ENTITY=NULL, IN_FIELD=NULL, "SQL"=NULL, SQL_EXTRA_KEY=NULL, SCRIPT='if (J_ACCT_STATUS == "2"&&B_ACCT_TYPE=="C1") {
    if (!isEmpty(J_CLOSE_DATE)) {
        return true
    }
    return false
}
return true', BEAN=NULL, CHECK_FLAG=NULL, CHECK_DESC=NULL, CHECK_ERR_TYPE=NULL, NEXT_ACTION=NULL, DATA_STATUS=NULL, DATA_FLAG=NULL, DATA_OP=NULL, DATA_SOURCE=NULL, DATA_VERSION=NULL, DATA_REJ_DESC=NULL, DATA_DEL_DESC=NULL, DATA_CRT_USER=NULL, DATA_CRT_DATE=NULL, DATA_CRT_TIME=NULL, DATA_CHG_USER=NULL, DATA_CHG_DATE=NULL, DATA_CHG_TIME=NULL, DATA_APV_USER=NULL, DATA_APV_DATE=NULL, DATA_APV_TIME=NULL, RSV1='90e4f8fcc73948eab4478a428c83a46d', RSV2=NULL, RSV3=NULL, RSV4='mbtrule', RSV5='1' WHERE DATA_ID='MBT_210I2100J04I2100J0401I2100J0402';
UPDATE GP_QC_RULE SET DATA_DATE='20190620', CORP_ID='TESTCORP', ORG_ID='72', GROUP_ID='002', INQ_ORG_ID=NULL, INQ_GROUP_ID=NULL, RULE_DESC='若“账户状态”为“2-结束”，则“余额”应为0。', RULE_MESSAGE='若“账户状态”为“2-结束”，则“余额”应为0。', RULE_TYPE=NULL, RULE_SOURCE='BUSI', FIELD='DATA_ID', FIELD_NAME=NULL, TRIMMABLE=NULL, NULLABLE='Y', TYPE_ID=NULL, ENCODING=NULL, MIN_LENGTH=NULL, MAX_LENGTH=NULL, MIN_VALUE=NULL, MAX_VALUE=NULL, MAX_PRECISION=NULL, MIN_SCALE=NULL, MAX_SCALE=NULL, ENUMERATION=NULL, PATTERN=NULL, IN_ENTITY=NULL, IN_FIELD=NULL, "SQL"=NULL, SQL_EXTRA_KEY=NULL, SCRIPT='if (J_ACCT_STATUS == "2" &&B_ACCT_TYPE=="C1") {
    if (J_ACCT_BAL == "0") {
        return true
    }
    return false
}
return true', BEAN=NULL, CHECK_FLAG=NULL, CHECK_DESC=NULL, CHECK_ERR_TYPE=NULL, NEXT_ACTION=NULL, DATA_STATUS=NULL, DATA_FLAG=NULL, DATA_OP=NULL, DATA_SOURCE=NULL, DATA_VERSION=NULL, DATA_REJ_DESC=NULL, DATA_DEL_DESC=NULL, DATA_CRT_USER=NULL, DATA_CRT_DATE=NULL, DATA_CRT_TIME=NULL, DATA_CHG_USER=NULL, DATA_CHG_DATE=NULL, DATA_CHG_TIME=NULL, DATA_APV_USER=NULL, DATA_APV_DATE=NULL, DATA_APV_TIME=NULL, RSV1='addcb153d8f645d482adc48b1c0bb411', RSV2=NULL, RSV3=NULL, RSV4='mbtrule', RSV5='1' WHERE DATA_ID='MBT_210I2100J05I2100J0501I2100J0502';
