
alter table CCRS_PM_CKYEKZ modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_DBHT modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_DBWXX modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_DECDFSE modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_DECDYE modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_DKFSEKZ modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_DKYEKZ modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_DWKH modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_DYBCDKQD modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_GRKH modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_JRJGXXBCB modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_PPPZDXMRZQK modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_PSLDYZCQD modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_RZXBH modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_SXHT modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_TXFSE modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_TXYE modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_TYCDFSE modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_TYCDYE modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_WTDKFSE modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_WTDKYE modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_XDHT modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_XYZKL modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_YHCDHPKL modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_YSZKZYDK modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_ZDKSYQK modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_ZDXMZJPHJCBFSE modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_ZQCX modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_ZQCXPZ modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_ZQCY modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_ZSCQZYDK modify CHECK_DESC varchar2(3072);
alter table CCRS_PM_ZXZQZCTDLYFZQK modify CHECK_DESC varchar2(3072);

--如果drop报错请忽略，部分索引原来就不存在
drop index U_TYCDYE;
drop index U_TYCDFSE;
drop index U_DECDYE;
drop index U_DECDFSE;
drop index U_SXHT;
drop index U_XDHT;
drop index U_DBHT;
drop index U_DBWXX;
drop index U_DKYEKZ;
drop index U_DKFSEKZ;
drop index U_TXYE;
drop index U_TXFSE;
drop index U_RZXBH;
drop index U_YHCDHPKL;
drop index U_XYZKL;
drop index U_WTDKYE;
drop index U_WTDKFSE;
drop index U_ZQCX;
drop index U_ZQCY;
drop index U_JRJGXXBCB;
drop index U_ZDKSYQK;
drop index U_PSLDYZCQD;
drop index U_DYBCDKQD;
drop index U_ZDXMZJPHJCBFSE;
drop index U_PPPZDXMRZQK;
drop index U_YSZKZYDK;
drop index U_ZSCQZYDK;
drop index U_ZQCXPZ;
drop index U_ZXZQZCTDLYFZQK;
drop index U_GRKH;
drop index U_DWKH;
drop index U_CKYEKZ;


create unique index U_DBHT on CCRS_PM_DBHT(DATA_RPT_DATE,XDHTBH,DBHTBH,JRJGBM,SJRQ_DATE);
create unique index U_DWKH on CCRS_PM_DWKH(DATA_RPT_DATE,KHBH,JRJGBM,SJRQ_DATE);
create unique index U_GRKH on CCRS_PM_GRKH(DATA_RPT_DATE,KHBH,JRJGBM,SJRQ_DATE);
create unique index U_SXHT on CCRS_PM_SXHT(DATA_RPT_DATE,SXHTBH,JRJGBM,SJRQ_DATE);
create unique index U_TXYE on CCRS_PM_TXYE(DATA_RPT_DATE,PJBM,JRJGBM,SJRQ_DATE);
create unique index U_XDHT on CCRS_PM_XDHT(DATA_RPT_DATE,XDHTBH,JRJGBM,SJRQ_DATE);
create unique index U_ZQCX on CCRS_PM_ZQCX(DATA_RPT_DATE,ZQDM,JRJGBM,SJRQ_DATE);
create unique index U_ZQCY on CCRS_PM_ZQCY(DATA_RPT_DATE,ZQDM,JRJGBM,SJRQ_DATE);
create unique index U_DBWXX on CCRS_PM_DBWXX(DATA_RPT_DATE,BZRZJHM,YPBH,DBHTBH,JRJGBM,SJRQ_DATE);
create unique index U_RZXBH on CCRS_PM_RZXBH(DATA_RPT_DATE,BHBH,JRJGBM,SJRQ_DATE);
create unique index U_TXFSE on CCRS_PM_TXFSE(DATA_RPT_DATE,PJBM,JRJGBM,SJRQ_DATE);
create unique index U_XYZKL on CCRS_PM_XYZKL(DATA_RPT_DATE,XYZBM,JRJGBM,SJRQ_DATE);
create unique index U_CKYEKZ on CCRS_PM_CKYEKZ(DATA_RPT_DATE,CKZHDM,JRJGBM,SJRQ_DATE);
create unique index U_DECDYE on CCRS_PM_DECDYE(DATA_RPT_DATE,CDXYDM,KHZJHM,KHZJLX,JRJGBM,SJRQ_DATE);
create unique index U_DKYEKZ on CCRS_PM_DKYEKZ(DATA_RPT_DATE,DKJJBM,JRJGBM,SJRQ_DATE);
create unique index U_TYCDYE on CCRS_PM_TYCDYE(DATA_RPT_DATE,CDXYDM,JYDSMC,JRJGBM,SJRQ_DATE);
create unique index U_WTDKYE on CCRS_PM_WTDKYE(DATA_RPT_DATE,DKJJBM,JRJGBM,SJRQ_DATE);
create unique index U_ZQCXPZ on CCRS_PM_ZQCXPZ(DATA_RPT_DATE,ZQDM,JRJGBM,SJRQ_DATE);
create unique index U_DKFSEKZ on CCRS_PM_DKFSEKZ(DATA_RPT_DATE,DKJJBM,JRJGBM,SJRQ_DATE);
create unique index U_TYCDFSE on CCRS_PM_TYCDFSE(DATA_RPT_DATE,CDXYDM,JYDSMC,JRJGBM,SJRQ_DATE);
create unique index U_WTDKFSE on CCRS_PM_WTDKFSE(DATA_RPT_DATE,DKJJBM,JRJGBM,SJRQ_DATE);
create unique index U_ZDKSYQK on CCRS_PM_ZDKSYQK(DATA_RPT_DATE,DKJJBM,JRJGBM,SJRQ_DATE);
create unique index U_DYBCDKQD on CCRS_PM_DYBCDKQD(DATA_RPT_DATE,DKJJBM,JRJGBM,SJRQ_DATE);
create unique index U_YHCDHPKL on CCRS_PM_YHCDHPKL(DATA_RPT_DATE,YHCDHPBM,JRJGBM,SJRQ_DATE);
create unique index U_YSZKZYDK on CCRS_PM_YSZKZYDK(DATA_RPT_DATE,DKJJBM,JRJGBM,SJRQ_DATE);
create unique index U_ZSCQZYDK on CCRS_PM_ZSCQZYDK(DATA_RPT_DATE,DKJJBM,JRJGBM,SJRQ_DATE);
create unique index U_JRJGXXBCB on CCRS_PM_JRJGXXBCB(DATA_RPT_DATE,SJRQ_DATE,JRJGBM);
create unique index U_PSLDYZCQD on CCRS_PM_PSLDYZCQD(DATA_RPT_DATE,DKJJBM,JRJGBM,SJRQ_DATE);
create unique index U_PPPZDXMRZQK on CCRS_PM_PPPZDXMRZQK(DATA_RPT_DATE,XMMC,JRJGBM,SJRQ_DATE);
create unique index U_ZDXMZJPHJCBFSE on CCRS_PM_ZDXMZJPHJCBFSE(DATA_RPT_DATE,XMMC,JRJGBM,SJRQ_DATE);
create unique index U_ZXZQZCTDLYFZQK on CCRS_PM_ZXZQZCTDLYFZQK(DATA_RPT_DATE,DKJJBM,JRJGBM,SJRQ_DATE);
