CREATE TABLE GFDR_BM_RPT_CONDITION(
    DATA_ID VARCHAR(64) NOT NULL   COMMENT '数据ID' ,
    DATA_DATE CHAR(8)    COMMENT '数据日期' ,
    CORP_ID VARCHAR(14)    COMMENT '法人机构号' ,
    ORG_ID VARCHAR(14)    COMMENT '机构号' ,
    GROUP_ID VARCHAR(100)    COMMENT '部门编号' ,
    NBJGH VARCHAR(30)    COMMENT 'NBJGH' ,
    FILE_NAME VARCHAR(64)    COMMENT 'FILE_NAME' ,
    DIVIDE_RULE VARCHAR(2)    COMMENT 'DIVIDE_RULE' ,
    WHERE_CONDITION VARCHAR(400)    COMMENT 'WHERE_CONDITION' ,
    RSV1 VARCHAR(180)    COMMENT '备用1' ,
    RSV2 VARCHAR(180)    COMMENT '备用2' ,
    RSV3 VARCHAR(180)    COMMENT '备用3' ,
    RSV4 VARCHAR(180)    COMMENT '备用4' ,
    RSV5 VARCHAR(180)    COMMENT '备用5' ,
    PRIMARY KEY (DATA_ID)
) COMMENT = 'GFDR_BM_RPT_CONDITION' ENGINE=InnoDB;
