CREATE TABLE GP_BM_KETTLE_LOG(
    ID_BATCH NUMERIC(38)    COMMENT '' ,
    CHANNEL_ID VARCHAR(255)    COMMENT '' ,
    TRANSNAME VARCHAR(255)    COMMENT '' ,
    STATUS VARCHAR(15)    COMMENT '' ,
    LINES_READ NUMERIC(38)    COMMENT '' ,
    LINES_WRITTEN NUMERIC(38)    COMMENT '' ,
    LINES_UPDATED NUMERIC(38)    COMMENT '' ,
    LINES_INPUT NUMERIC(38)    COMMENT '' ,
    LINES_OUTPUT NUMERIC(38)    COMMENT '' ,
    LINES_REJECTED NUMERIC(38)    COMMENT '' ,
    ERRORS NUMERIC(38)    COMMENT '' ,
    STARTDATE DATE    COMMENT '' ,
    ENDDATE DATE    COMMENT '' ,
    LOGDATE DATE    COMMENT '' ,
    DEPDATE DATE    COMMENT '' ,
    REPLAYDATE DATE    COMMENT '' ,
    LOG_FIELD TEXT    COMMENT '' 
) COMMENT = '' ENGINE=InnoDB;
