CREATE TABLE GP_BM_KETTLE_DATA_TYPE(
    DATA_ID VARCHAR(64) NOT NULL   COMMENT '数据ID' ,
    DATA_DATE CHAR(8)    COMMENT '数据日期' ,
    CORP_ID VARCHAR(14)    COMMENT '法人机构号' ,
    ORG_ID VARCHAR(14)    COMMENT '机构号' ,
    BUS_TYPE VARCHAR(64)    COMMENT '' ,
    BUS_TYPE_NAME VARCHAR(64)    COMMENT '' ,
    DATA_TYPE VARCHAR(10)    COMMENT '' ,
    KETTLE_NAME VARCHAR(64)    COMMENT '' ,
    FILE_NAME VARCHAR(100)    COMMENT '' ,
    WILDCARD_CAPTURE VARCHAR(50)    COMMENT '' ,
    KETTLE_FLAG CHAR(1)    COMMENT '' ,
    NEXT_ACTION CHAR(2)    COMMENT '下一动作' ,
    DATA_STATUS CHAR(2)    COMMENT '数据状态' ,
    DATA_VERSION INT    COMMENT '数据版本' ,
    DATA_FLAG CHAR(1)    COMMENT '数据是否已删除' ,
    REMARK VARCHAR(180)    COMMENT '' ,
    PRIMARY KEY (DATA_ID)
) COMMENT = '' ENGINE=InnoDB;
