CREATE TABLE GP_BM_TABLE_FIELDS(
    SYS_ID VARCHAR(30) NOT NULL   COMMENT '系统ID' ,
    FIELD_ID VARCHAR(30)    COMMENT '字段ID' ,
    FIELD_ALIAS VARCHAR(30)    COMMENT '字段别名' ,
    FIELD_NAME VARCHAR(64)    COMMENT '中文名称' ,
    FIELD_TYPE VARCHAR(14)    COMMENT '字段类型' ,
    FIELD_SIZE NUMERIC(38,0)    COMMENT '字段长度' ,
    FIELD_PRECISION NUMERIC(38,0)    COMMENT '字段精度' ,
    FIELD_FORMULA VARCHAR(128)    COMMENT '字段取值规则' ,
    DEFUALT_VALUE VARCHAR(512)    COMMENT '默认值' ,
    REMARKS VARCHAR(512)    COMMENT '备注' ,
    RSV1 VARCHAR(180)    COMMENT '备用1' ,
    RSV2 VARCHAR(180)    COMMENT '备用2' ,
    RSV3 VARCHAR(180)    COMMENT '备用3' ,
    RSV4 VARCHAR(180)    COMMENT '备用4' ,
    RSV5 VARCHAR(180)    COMMENT '备用5' 
) COMMENT = '常用字段配置表' ENGINE=InnoDB;
