CREATE TABLE GP_BM_GLOBAL_INFO(
    ID NUMERIC(38,0) NOT NULL   COMMENT '' ,
    SYSTEM_NAME VARCHAR(20)    COMMENT '' ,
    TBSDY CHAR(8)    COMMENT '' ,
    BHDATE CHAR(8)    COMMENT '' ,
    LBHDATE CHAR(8)    COMMENT '' ,
    STATUS CHAR(1)    COMMENT '' ,
    SYSTEM_TYPE CHAR(2)    COMMENT '' ,
    MISCFLGS VARCHAR(20)    COMMENT '' ,
    DATA_HASH VARCHAR(32)    COMMENT '记录Hash值' ,
    PRIMARY KEY (ID)
) COMMENT = '全局信息表' ENGINE=InnoDB;
