CREATE TABLE GP_BM_ID_FIELDDATA(
    GUID VARCHAR(32) NOT NULL   COMMENT 'UUID' ,
    FIELD_NAME VARCHAR(40) NOT NULL   COMMENT '' ,
    UMW_EXPRESSION VARCHAR(1024) NOT NULL   COMMENT '' ,
    U_DATATYPE VARCHAR(1)    COMMENT '' ,
    UPDATE_WAY VARCHAR(1)    COMMENT '' ,
    UNIQUEKEY_FLAG VARCHAR(1)    COMMENT '' ,
    UPDATE_FLAG VARCHAR(1)    COMMENT '' ,
    FILTER_FLAG VARCHAR(1)    COMMENT '' ,
    FILLER1 VARCHAR(255)    COMMENT '' ,
    FILLER2 VARCHAR(255)    COMMENT '' ,
    FILLER3 VARCHAR(255)    COMMENT '' ,
    PGUID VARCHAR(32)    COMMENT '' ,
    LIMIT_FLAG VARCHAR(1)    COMMENT '' ,
    BUSINESSKEY_FLAG VARCHAR(1)    COMMENT '' ,
    FIELD_COMMENTS VARCHAR(255)    COMMENT '' ,
    DATA_HASH VARCHAR(64)    COMMENT '' ,
    PRIMARY KEY (GUID)
) COMMENT = '数据导入配置表' ENGINE=InnoDB;
