CREATE TABLE GP_BM_ID_FUNCTIONDATA(
    FUNC_NAME VARCHAR(128) NOT NULL   COMMENT '' ,
    FUNC_FLAG VARCHAR(1) NOT NULL   COMMENT '' ,
    FUNC_DESC VARCHAR(510) NOT NULL   COMMENT '' ,
    FILLER1 VARCHAR(255)    COMMENT '' ,
    FILLER2 VARCHAR(255)    COMMENT '' ,
    FILLER3 VARCHAR(255)    COMMENT '' ,
    DATA_HASH VARCHAR(32)    COMMENT '' ,
    PRIMARY KEY (FUNC_NAME)
) COMMENT = '导入函数信息表' ENGINE=InnoDB;
