CREATE TABLE GP_BM_JOB_LOG(
    DATA_ID VARCHAR(64) NOT NULL   COMMENT '数据ID' ,
    JOB_GROUP VARCHAR(256)    COMMENT '' ,
    JOB_ID VARCHAR(256)    COMMENT '' ,
    START_TIME CHAR(14)    COMMENT '' ,
    END_TIME CHAR(14)    COMMENT '' ,
    STATUS VARCHAR(20)    COMMENT '' ,
    MESSAGE VARCHAR(4000)    COMMENT '' ,
    STACK_TRACE VARCHAR(4000)    COMMENT '' ,
    PRIMARY KEY (DATA_ID)
) COMMENT = '定时任务日志表' ENGINE=InnoDB;
