CREATE TABLE GP_BM_DATA_RULES(
    DATA_ID VARCHAR(64) NOT NULL   COMMENT '数据ID' ,
    DATA_DATE CHAR(8)    COMMENT '数据日期' ,
    QUERY_ID VARCHAR(256)    COMMENT '' ,
    OPERATION_ID CHAR(14)    COMMENT '' ,
    COLUMN_NAME CHAR(14)    COMMENT '' ,
    DATA_TYPE VARCHAR(20)    COMMENT '' ,
    VAL_KIND CHAR(2)    COMMENT '' ,
    VAL_TYPE VARCHAR(4)    COMMENT '' ,
    IS_NULL CHAR(1)    COMMENT '' ,
    MAX_VALUE VARCHAR(255)    COMMENT '' ,
    MIN_VALUE VARCHAR(255)    COMMENT '' ,
    MAX_LENGTH VARCHAR(255)    COMMENT '' ,
    MIN_LENGTH VARCHAR(255)    COMMENT '' ,
    REG_EXPRESS VARCHAR(255)    COMMENT '' ,
    EXPRESS VARCHAR(255)    COMMENT '' ,
    VALIDITY_MESSAGE VARCHAR(255)    COMMENT '' 
) COMMENT = '数据校验表' ENGINE=InnoDB;
