CREATE TABLE GP_BM_ID_XMLDATA(
    PUID VARCHAR(32) NOT NULL   COMMENT '' ,
    FUID VARCHAR(32) NOT NULL   COMMENT '' ,
    GUID VARCHAR(32) NOT NULL   COMMENT '' ,
    NODES_NAME VARCHAR(128) NOT NULL   COMMENT '' ,
    NODE_ORDER VARCHAR(2) NOT NULL   COMMENT '' ,
    NODE_XPATH VARCHAR(1024) NOT NULL   COMMENT '' ,
    NODE_PROPERTY VARCHAR(1) NOT NULL   COMMENT '' ,
    NODE_GETVAL VARCHAR(1) NOT NULL   COMMENT '' ,
    NODE_RTVAL VARCHAR(1)    COMMENT '' ,
    FILLER1 VARCHAR(255)    COMMENT '' ,
    FILLER2 VARCHAR(255)    COMMENT '' ,
    FILLER3 VARCHAR(255)    COMMENT '' 
) COMMENT = 'XML配置表' ENGINE=InnoDB;
