CREATE TABLE GP_BM_ID_UPLOADLOG(
    UPLOAD_GUID VARCHAR(32) NOT NULL   COMMENT 'UUID' ,
    WORK_DATE VARCHAR(8)    COMMENT '' ,
    FILE_NAME VARCHAR(256)    COMMENT '' ,
    TARGET_PATH VARCHAR(200)    COMMENT '' ,
    SND_IP VARCHAR(512)    COMMENT '' ,
    REC_IP VARCHAR(512)    COMMENT '' ,
    UPLOAD_TIME VARCHAR(14)    COMMENT '' ,
    UPLOADER VARCHAR(64)    COMMENT '' ,
    FILLER1 VARCHAR(60)    COMMENT '' ,
    FILLER2 VARCHAR(60)    COMMENT '' ,
    FILLER3 VARCHAR(60)    COMMENT '' ,
    UPLOAD_ORG_ID VARCHAR(60)    COMMENT '' ,
    STORE_NAME VARCHAR(80)    COMMENT '' ,
    DATA_RPT_DATE CHAR(8)    COMMENT '报表日期' ,
    REPORT_CODE VARCHAR(32)    COMMENT '' 
) COMMENT = '上传日志表' ENGINE=InnoDB;
