CREATE TABLE GP_BM_EMAIL_LOG(
    DATA_ID VARCHAR(64) NOT NULL   COMMENT '数据ID' ,
    SEND_DATE CHAR(8)    COMMENT '' ,
    SEND_TIME CHAR(14)    COMMENT '' ,
    SEND_EMAIL VARCHAR(64)    COMMENT '' ,
    RECE_EMAIL VARCHAR(64)    COMMENT '' ,
    RECE_TLR_NO VARCHAR(64)    COMMENT '' ,
    TITLE VARCHAR(200)    COMMENT '' ,
    MESS VARCHAR(4000)    COMMENT '' ,
    STATUS CHAR(1)    COMMENT '' ,
    RSV1 VARCHAR(180)    COMMENT '备用1' ,
    RSV2 VARCHAR(180)    COMMENT '备用2' ,
    RSV3 VARCHAR(180)    COMMENT '备用3' ,
    RSV4 VARCHAR(180)    COMMENT '备用4' ,
    RSV5 VARCHAR(180)    COMMENT '备用5' ,
    CORP_ID VARCHAR(14)    COMMENT '法人机构号' 
) COMMENT = '邮件日志表' ENGINE=InnoDB;

ALTER TABLE GP_BM_EMAIL_LOG ADD UNIQUE SYS_C00245249(DATA_ID);