CREATE TABLE GP_BM_MON_CONFIG(
    MONITOR_NAME VARCHAR(512) NOT NULL   COMMENT '' ,
    MONITOR_BEAN VARCHAR(512)    COMMENT '' ,
    TOPIC VARCHAR(32)    COMMENT '' ,
    STATUS VARCHAR(1)    COMMENT '' 
) COMMENT = '监控配置表' ENGINE=InnoDB;
