CREATE TABLE GP_BM_FILE_EXPORT_TSK_INF(
    TSK_ID CHAR(36) NOT NULL   COMMENT '' ,
    TSK_NM VARCHAR(50)    COMMENT '' ,
    TSK_START_TMS CHAR(14)    COMMENT '' ,
    TSK_START_OP VARCHAR(40)    COMMENT '' ,
    TSK_DESC VARCHAR(200)    COMMENT '' ,
    TSK_PARAM1 VARCHAR(2048)    COMMENT '' ,
    TSK_PARAM2 VARCHAR(2048)    COMMENT '' ,
    TSK_OWNER VARCHAR(40)    COMMENT '' ,
    TSK_END_TMS CHAR(14)    COMMENT '' ,
    TSK_RUN_CLASS CHAR(2)    COMMENT '' ,
    EXP_FILE_NM VARCHAR(128)    COMMENT '' ,
    EXP_RCD_NUM NUMERIC(38,0)    COMMENT '' ,
    EXP_RCD_SUM_NUM NUMERIC(38,0)    COMMENT '' ,
    EXP_FILE_SIZE NUMERIC(38,0)    COMMENT '' ,
    TSK_STAT CHAR(1)    COMMENT '' 
) COMMENT = '文件批量导出任务表' ENGINE=InnoDB;
