CREATE TABLE GP_BM_ID_FILTERDATA(
    GUID VARCHAR(32) NOT NULL   COMMENT '' ,
    FIELD_NAME VARCHAR(128) NOT NULL   COMMENT '' ,
    DATA_TYPE VARCHAR(1)    COMMENT '' ,
    FILTER_EXPRESSION VARCHAR(1024)    COMMENT '' ,
    FILLER1 VARCHAR(255)    COMMENT '' ,
    FILLER2 VARCHAR(255)    COMMENT '' ,
    FILLER3 VARCHAR(255)    COMMENT '' 
) COMMENT = '导入数据过滤表' ENGINE=InnoDB;
