CREATE TABLE GP_BM_ID_IMPORTLOGDTL(
    GUID VARCHAR(32) NOT NULL   COMMENT '' ,
    WORK_DATE VARCHAR(8) NOT NULL   COMMENT '' ,
    FILE_OWNER VARCHAR(32) NOT NULL   COMMENT '' ,
    SERICAL_NO NUMERIC(38,0) NOT NULL   COMMENT '' ,
    LINE_NO NUMERIC(38,0) NOT NULL   COMMENT '' ,
    POS_NO VARCHAR(32)    COMMENT '' ,
    ERROR_MESSAGE VARCHAR(1024)    COMMENT '' ,
    MOD_FLG VARCHAR(2)    COMMENT '' ,
    BEGIN_TIME VARCHAR(20)    COMMENT '' ,
    END_TIME VARCHAR(20)    COMMENT '' ,
    ERR_FILENAME VARCHAR(128)    COMMENT '' ,
    FILE_NAME VARCHAR(255)    COMMENT '' ,
    FILLER2 VARCHAR(255)    COMMENT '' ,
    FILLER3 VARCHAR(255)    COMMENT '' 
) COMMENT = '导入日志明细表' ENGINE=InnoDB;
