CREATE TABLE GP_BM_TASK_CONFIG(
    MODE_NAME VARCHAR(150)    COMMENT '' ,
    BEAN_ID VARCHAR(150)    COMMENT '' ,
    DATA_ID VARCHAR(64) NOT NULL   COMMENT '数据ID' ,
    EXT VARCHAR(250)    COMMENT '' ,
    PRIMARY KEY (DATA_ID)
) COMMENT = '批量任务配置表' ENGINE=InnoDB;
