CREATE TABLE TASKM_DEPLOYED_JOB(
    ID NUMERIC(10) NOT NULL   COMMENT '' ,
    CREATED_TIME TIMESTAMP    COMMENT '' ,
    LAST_MODIFIED_TIME TIMESTAMP    COMMENT '' ,
    VERSION NUMERIC(10) NOT NULL   COMMENT '' ,
    DEPLOYED CHAR(1)    COMMENT '' ,
    DEPLOYED_TIME TIMESTAMP    COMMENT '' ,
    DEPLOYED_USER VARCHAR(64)    COMMENT '' ,
    DESIGN TEXT    COMMENT '' ,
    DESIGN_HASH VARCHAR(64)    COMMENT '' ,
    DESIGN_VERSION VARCHAR(32)    COMMENT '' ,
    JOB_DESC VARCHAR(512)    COMMENT '' ,
    JOB_ID VARCHAR(32)    COMMENT '' ,
    JOB_NAME VARCHAR(64)    COMMENT '' ,
    PROJECT_ID VARCHAR(32)    COMMENT '' ,
    STEP_COUNT NUMERIC(10)    COMMENT '' ,
    PRIMARY KEY (ID)
) COMMENT = '' ENGINE=InnoDB;
