CREATE TABLE TASKM_NODE(
    ID NUMERIC(10) NOT NULL   COMMENT '' ,
    CREATED_TIME TIMESTAMP    COMMENT '' ,
    LAST_MODIFIED_TIME TIMESTAMP    COMMENT '' ,
    VERSION NUMERIC(10) NOT NULL   COMMENT '' ,
    CONNECT_TYPE VARCHAR(128)    COMMENT '' ,
    CREATE_USER VARCHAR(256)    COMMENT '' ,
    IP VARCHAR(128)    COMMENT '' ,
    LAST_UPDATE_USER VARCHAR(256)    COMMENT '' ,
    NODE_ID VARCHAR(128)    COMMENT '' ,
    PASSWORD VARCHAR(512)    COMMENT '' ,
    PORT NUMERIC(10)    COMMENT '' ,
    REMARKS VARCHAR(400)    COMMENT '' ,
    STATUS VARCHAR(8)    COMMENT '' ,
    USERNAME VARCHAR(128)    COMMENT '' ,
    PRIMARY KEY (ID)
) COMMENT = '' ENGINE=InnoDB;
