CREATE TABLE TASKM_EXECUTION_LOG(
    ID NUMERIC(10) NOT NULL   COMMENT '' ,
    CREATED_TIME TIMESTAMP    COMMENT '' ,
    LAST_MODIFIED_TIME TIMESTAMP    COMMENT '' ,
    VERSION NUMERIC(10) NOT NULL   COMMENT '' ,
    EXECUTE_BY VARCHAR(512)    COMMENT '' ,
    EXECUTE_TYPE VARCHAR(255)    COMMENT '' ,
    EXECUTION_ID NUMERIC(19)    COMMENT '' ,
    INSTANCE_ID NUMERIC(19)    COMMENT '' ,
    JOB_ID NUMERIC(10)    COMMENT '' ,
    TRIGGER_ID NUMERIC(10)    COMMENT '' ,
    PRIMARY KEY (ID)
) COMMENT = '' ENGINE=InnoDB;
