CREATE TABLE TASKM_JOB_TRIGGER(
    ID NUMERIC(10) NOT NULL   COMMENT '' ,
    CREATED_TIME TIMESTAMP    COMMENT '' ,
    LAST_MODIFIED_TIME TIMESTAMP    COMMENT '' ,
    VERSION NUMERIC(10) NOT NULL   COMMENT '' ,
    CALENDAR VARCHAR(128)    COMMENT '' ,
    CREATED_USER VARCHAR(256)    COMMENT '' ,
    IN_USED CHAR(4)    COMMENT '' ,
    INTERVAL NUMERIC(19)    COMMENT '' ,
    JOB_ID VARCHAR(128)    COMMENT '' ,
    LAST_MODIFIED_USER VARCHAR(256)    COMMENT '' ,
    NODE_ID VARCHAR(256)    COMMENT '' ,
    PATTERN VARCHAR(2048)    COMMENT '' ,
    PROJECT_ID VARCHAR(128)    COMMENT '' ,
    TYPE VARCHAR(1020)    COMMENT '' ,
    PRIMARY KEY (ID)
) COMMENT = '' ENGINE=InnoDB;
