CREATE TABLE TASKM_JOB_NOTIFY_TEMPLATE(
    ID NUMERIC(10) NOT NULL   COMMENT '' ,
    CREATED_TIME TIMESTAMP    COMMENT '' ,
    LAST_MODIFIED_TIME TIMESTAMP    COMMENT '' ,
    VERSION NUMERIC(10) NOT NULL   COMMENT '' ,
    ADDRESS VARCHAR(128)    COMMENT '' ,
    CREATE_TIME TIMESTAMP    COMMENT '' ,
    CREATE_USER VARCHAR(255)    COMMENT '' ,
    LAST_UPDATE_TIME TIMESTAMP    COMMENT '' ,
    LAST_UPDATE_USER VARCHAR(255)    COMMENT '' ,
    REMARKS VARCHAR(255)    COMMENT '' ,
    STATUS CHAR(1)    COMMENT '' ,
    TEMPLATE_ID VARCHAR(32)    COMMENT '' ,
    TYPE VARCHAR(20)    COMMENT '' ,
    PRIMARY KEY (ID)
) COMMENT = '' ENGINE=InnoDB;
