-- qingyong.wang

UPDATE GP_QC_RULE_SET SET RULE_SET_DESC = '个人证件有效期信息记录' WHERE ENTITY = 'MBT_130';
UPDATE GP_QC_RULE_SET SET RULE_SET_DESC = '个人证件整合信息' WHERE ENTITY = 'MBT_140';

--ce43
INSERT INTO "GP_BM_EXPORT_FIELD"("DATA_ID", "DATA_DATE", "CORP_ID", "ORG_ID", "GROUP_ID", "INQ_ORG_ID", "INQ_GROUP_ID", "P_DATA_ID", "COLUMN_NAME", "COLUMN_COMMENTS", "EXPORT_FLAG", "SEQ_NO", "EXPORT_NUM", "PK_FLAG", "WHERE_FLAG", "REMARKS", "CHECK_FLAG", "CHECK_DESC", "CHECK_ERR_TYPE", "NEXT_ACTION", "DATA_STATUS", "DATA_FLAG", "DATA_SOURCE", "DATA_VERSION", "DATA_REJ_DESC", "DATA_DEL_DESC", "DATA_CRT_USER", "DATA_CRT_DATE", "DATA_CRT_TIME", "DATA_CHG_USER", "DATA_CHG_DATE", "DATA_CHG_TIME", "DATA_APV_USER", "DATA_APV_DATE", "DATA_APV_TIME", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5", "READONLY_FLAG", "DATA_DIC_NO") VALUES ('776cdc23a4c543cc975cb6faa0df0844', '20200715', 'HSBC', 'HBCN', NULL, NULL, NULL, '11136554f3614109ad86361b5ca7a363', 'NAME', 'A 姓名', '01', '1', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'admin', '20200715', '20200715145958', 'admin', '20200715', '20200715145958', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', NULL);
INSERT INTO "GP_BM_EXPORT_FIELD"("DATA_ID", "DATA_DATE", "CORP_ID", "ORG_ID", "GROUP_ID", "INQ_ORG_ID", "INQ_GROUP_ID", "P_DATA_ID", "COLUMN_NAME", "COLUMN_COMMENTS", "EXPORT_FLAG", "SEQ_NO", "EXPORT_NUM", "PK_FLAG", "WHERE_FLAG", "REMARKS", "CHECK_FLAG", "CHECK_DESC", "CHECK_ERR_TYPE", "NEXT_ACTION", "DATA_STATUS", "DATA_FLAG", "DATA_SOURCE", "DATA_VERSION", "DATA_REJ_DESC", "DATA_DEL_DESC", "DATA_CRT_USER", "DATA_CRT_DATE", "DATA_CRT_TIME", "DATA_CHG_USER", "DATA_CHG_DATE", "DATA_CHG_TIME", "DATA_APV_USER", "DATA_APV_DATE", "DATA_APV_TIME", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5", "READONLY_FLAG", "DATA_DIC_NO") VALUES ('8ef25fcf8955456d9af3308e4389f4b6', '20200715', 'HSBC', 'HBCN', NULL, NULL, NULL, '11136554f3614109ad86361b5ca7a363', 'ID_TYPE', 'A 证件类型', '01', '2', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'admin', '20200715', '20200715145958', 'admin', '20200715', '20200715145958', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', NULL);
INSERT INTO "GP_BM_EXPORT_FIELD"("DATA_ID", "DATA_DATE", "CORP_ID", "ORG_ID", "GROUP_ID", "INQ_ORG_ID", "INQ_GROUP_ID", "P_DATA_ID", "COLUMN_NAME", "COLUMN_COMMENTS", "EXPORT_FLAG", "SEQ_NO", "EXPORT_NUM", "PK_FLAG", "WHERE_FLAG", "REMARKS", "CHECK_FLAG", "CHECK_DESC", "CHECK_ERR_TYPE", "NEXT_ACTION", "DATA_STATUS", "DATA_FLAG", "DATA_SOURCE", "DATA_VERSION", "DATA_REJ_DESC", "DATA_DEL_DESC", "DATA_CRT_USER", "DATA_CRT_DATE", "DATA_CRT_TIME", "DATA_CHG_USER", "DATA_CHG_DATE", "DATA_CHG_TIME", "DATA_APV_USER", "DATA_APV_DATE", "DATA_APV_TIME", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5", "READONLY_FLAG", "DATA_DIC_NO") VALUES ('cba9d73d846d42f8b5e79f36698150a5', '20200715', 'HSBC', 'HBCN', NULL, NULL, NULL, '11136554f3614109ad86361b5ca7a363', 'ID_NUM', 'A 证件号码', '01', '3', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'admin', '20200715', '20200715145958', 'admin', '20200715', '20200715145958', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', NULL);
INSERT INTO "GP_BM_EXPORT_FIELD"("DATA_ID", "DATA_DATE", "CORP_ID", "ORG_ID", "GROUP_ID", "INQ_ORG_ID", "INQ_GROUP_ID", "P_DATA_ID", "COLUMN_NAME", "COLUMN_COMMENTS", "EXPORT_FLAG", "SEQ_NO", "EXPORT_NUM", "PK_FLAG", "WHERE_FLAG", "REMARKS", "CHECK_FLAG", "CHECK_DESC", "CHECK_ERR_TYPE", "NEXT_ACTION", "DATA_STATUS", "DATA_FLAG", "DATA_SOURCE", "DATA_VERSION", "DATA_REJ_DESC", "DATA_DEL_DESC", "DATA_CRT_USER", "DATA_CRT_DATE", "DATA_CRT_TIME", "DATA_CHG_USER", "DATA_CHG_DATE", "DATA_CHG_TIME", "DATA_APV_USER", "DATA_APV_DATE", "DATA_APV_TIME", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5", "READONLY_FLAG", "DATA_DIC_NO") VALUES ('a6ca594f68794c17ad42d10f2db4aed3', '20200715', 'HSBC', 'HBCN', NULL, NULL, NULL, '11136554f3614109ad86361b5ca7a363', 'FAM_MEM_NAME', 'B 姓名', '01', '4', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'admin', '20200715', '20200715145958', 'admin', '20200715', '20200715145958', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', NULL);
INSERT INTO "GP_BM_EXPORT_FIELD"("DATA_ID", "DATA_DATE", "CORP_ID", "ORG_ID", "GROUP_ID", "INQ_ORG_ID", "INQ_GROUP_ID", "P_DATA_ID", "COLUMN_NAME", "COLUMN_COMMENTS", "EXPORT_FLAG", "SEQ_NO", "EXPORT_NUM", "PK_FLAG", "WHERE_FLAG", "REMARKS", "CHECK_FLAG", "CHECK_DESC", "CHECK_ERR_TYPE", "NEXT_ACTION", "DATA_STATUS", "DATA_FLAG", "DATA_SOURCE", "DATA_VERSION", "DATA_REJ_DESC", "DATA_DEL_DESC", "DATA_CRT_USER", "DATA_CRT_DATE", "DATA_CRT_TIME", "DATA_CHG_USER", "DATA_CHG_DATE", "DATA_CHG_TIME", "DATA_APV_USER", "DATA_APV_DATE", "DATA_APV_TIME", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5", "READONLY_FLAG", "DATA_DIC_NO") VALUES ('396ed08621c741cdbf6530e39c42ac0e', '20200715', 'HSBC', 'HBCN', NULL, NULL, NULL, '11136554f3614109ad86361b5ca7a363', 'FAM_MEM_CET_TYPE', 'B 证件类型', '01', '5', '5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'admin', '20200715', '20200715145958', 'admin', '20200715', '20200715145958', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', NULL);
INSERT INTO "GP_BM_EXPORT_FIELD"("DATA_ID", "DATA_DATE", "CORP_ID", "ORG_ID", "GROUP_ID", "INQ_ORG_ID", "INQ_GROUP_ID", "P_DATA_ID", "COLUMN_NAME", "COLUMN_COMMENTS", "EXPORT_FLAG", "SEQ_NO", "EXPORT_NUM", "PK_FLAG", "WHERE_FLAG", "REMARKS", "CHECK_FLAG", "CHECK_DESC", "CHECK_ERR_TYPE", "NEXT_ACTION", "DATA_STATUS", "DATA_FLAG", "DATA_SOURCE", "DATA_VERSION", "DATA_REJ_DESC", "DATA_DEL_DESC", "DATA_CRT_USER", "DATA_CRT_DATE", "DATA_CRT_TIME", "DATA_CHG_USER", "DATA_CHG_DATE", "DATA_CHG_TIME", "DATA_APV_USER", "DATA_APV_DATE", "DATA_APV_TIME", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5", "READONLY_FLAG", "DATA_DIC_NO") VALUES ('b29e4df9a4684d8b83269806612126ad', '20200715', 'HSBC', 'HBCN', NULL, NULL, NULL, '11136554f3614109ad86361b5ca7a363', 'FAM_MEM_CERT_NUM', 'B 证件号码', '01', '6', '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'admin', '20200715', '20200715145958', 'admin', '20200715', '20200715145958', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', NULL);
INSERT INTO "GP_BM_EXPORT_FIELD"("DATA_ID", "DATA_DATE", "CORP_ID", "ORG_ID", "GROUP_ID", "INQ_ORG_ID", "INQ_GROUP_ID", "P_DATA_ID", "COLUMN_NAME", "COLUMN_COMMENTS", "EXPORT_FLAG", "SEQ_NO", "EXPORT_NUM", "PK_FLAG", "WHERE_FLAG", "REMARKS", "CHECK_FLAG", "CHECK_DESC", "CHECK_ERR_TYPE", "NEXT_ACTION", "DATA_STATUS", "DATA_FLAG", "DATA_SOURCE", "DATA_VERSION", "DATA_REJ_DESC", "DATA_DEL_DESC", "DATA_CRT_USER", "DATA_CRT_DATE", "DATA_CRT_TIME", "DATA_CHG_USER", "DATA_CHG_DATE", "DATA_CHG_TIME", "DATA_APV_USER", "DATA_APV_DATE", "DATA_APV_TIME", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5", "READONLY_FLAG", "DATA_DIC_NO") VALUES ('496ba31bf04d42828bf9f9e0f149f7e0', '20200715', 'HSBC', 'HBCN', NULL, NULL, NULL, '11136554f3614109ad86361b5ca7a363', 'FAM_REL', '家族关系', '01', '7', '7', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'admin', '20200715', '20200715145958', 'admin', '20200715', '20200715145958', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', NULL);
INSERT INTO "GP_BM_EXPORT_FIELD"("DATA_ID", "DATA_DATE", "CORP_ID", "ORG_ID", "GROUP_ID", "INQ_ORG_ID", "INQ_GROUP_ID", "P_DATA_ID", "COLUMN_NAME", "COLUMN_COMMENTS", "EXPORT_FLAG", "SEQ_NO", "EXPORT_NUM", "PK_FLAG", "WHERE_FLAG", "REMARKS", "CHECK_FLAG", "CHECK_DESC", "CHECK_ERR_TYPE", "NEXT_ACTION", "DATA_STATUS", "DATA_FLAG", "DATA_SOURCE", "DATA_VERSION", "DATA_REJ_DESC", "DATA_DEL_DESC", "DATA_CRT_USER", "DATA_CRT_DATE", "DATA_CRT_TIME", "DATA_CHG_USER", "DATA_CHG_DATE", "DATA_CHG_TIME", "DATA_APV_USER", "DATA_APV_DATE", "DATA_APV_TIME", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5", "READONLY_FLAG", "DATA_DIC_NO") VALUES ('6def986d559546f7b91a0168b09cb18c', '20200715', 'HSBC', 'HBCN', NULL, NULL, NULL, '11136554f3614109ad86361b5ca7a363', 'FAM_RELA_ASS_FLAG', '家族关系有效标志', '01', '8', '8', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'admin', '20200715', '20200715145958', 'admin', '20200715', '20200715145958', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', NULL);
INSERT INTO "GP_BM_EXPORT_FIELD"("DATA_ID", "DATA_DATE", "CORP_ID", "ORG_ID", "GROUP_ID", "INQ_ORG_ID", "INQ_GROUP_ID", "P_DATA_ID", "COLUMN_NAME", "COLUMN_COMMENTS", "EXPORT_FLAG", "SEQ_NO", "EXPORT_NUM", "PK_FLAG", "WHERE_FLAG", "REMARKS", "CHECK_FLAG", "CHECK_DESC", "CHECK_ERR_TYPE", "NEXT_ACTION", "DATA_STATUS", "DATA_FLAG", "DATA_SOURCE", "DATA_VERSION", "DATA_REJ_DESC", "DATA_DEL_DESC", "DATA_CRT_USER", "DATA_CRT_DATE", "DATA_CRT_TIME", "DATA_CHG_USER", "DATA_CHG_DATE", "DATA_CHG_TIME", "DATA_APV_USER", "DATA_APV_DATE", "DATA_APV_TIME", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5", "READONLY_FLAG", "DATA_DIC_NO") VALUES ('4702886b9c82480eb3ce3e05c05a3aec', '20200715', 'HSBC', 'HBCN', NULL, NULL, NULL, '11136554f3614109ad86361b5ca7a363', 'DATA_CHG_USER', '数据修改/删除用户', '01', '9', '9', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'admin', '20200715', '20200715145958', 'admin', '20200715', '20200715145958', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', NULL);
INSERT INTO "GP_BM_EXPORT_FIELD"("DATA_ID", "DATA_DATE", "CORP_ID", "ORG_ID", "GROUP_ID", "INQ_ORG_ID", "INQ_GROUP_ID", "P_DATA_ID", "COLUMN_NAME", "COLUMN_COMMENTS", "EXPORT_FLAG", "SEQ_NO", "EXPORT_NUM", "PK_FLAG", "WHERE_FLAG", "REMARKS", "CHECK_FLAG", "CHECK_DESC", "CHECK_ERR_TYPE", "NEXT_ACTION", "DATA_STATUS", "DATA_FLAG", "DATA_SOURCE", "DATA_VERSION", "DATA_REJ_DESC", "DATA_DEL_DESC", "DATA_CRT_USER", "DATA_CRT_DATE", "DATA_CRT_TIME", "DATA_CHG_USER", "DATA_CHG_DATE", "DATA_CHG_TIME", "DATA_APV_USER", "DATA_APV_DATE", "DATA_APV_TIME", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5", "READONLY_FLAG", "DATA_DIC_NO") VALUES ('e519e3f1576a4f6d9e66110593f776ce', '20200715', 'HSBC', 'HBCN', NULL, NULL, NULL, '11136554f3614109ad86361b5ca7a363', 'DATA_CRT_DATE', '数据创建/导入日期', '01', '10', '10', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'admin', '20200715', '20200715145958', 'admin', '20200715', '20200715145958', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', NULL);



--ce47
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19140' where DATA_ID = '20190515000000000000000013434272';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19010' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%证件类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19284' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%信息记录类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19241' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%国籍%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19147' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%性别%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19152' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%婚姻%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19149' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%学位%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19148' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%学历%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '190075' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%反馈状态%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19242' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%区划%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19141' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%单位性质%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19225' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%行业%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19150' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%就业%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19172' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%职业%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19142' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%职务%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19143' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%职称%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '201333' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS='操作类型';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19138' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%记录类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19139' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS LIKE '%报告时%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19144' where TABLE_NAME = 'MBT_110_EX' and  COMMENTS='居住状况';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19010' where TABLE_NAME = 'MBT_110_C_EX' and  COMMENTS='证件类型';



UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19245' where TABLE_NAME = 'MBT_230_EX' and  COMMENTS LIKE '%账户类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19010' where TABLE_NAME = 'MBT_230_EX' and  COMMENTS LIKE '%证件类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'N', DATA_TYPE_NO = '' where TABLE_NAME = 'MBT_230_EX' and  COMMENTS LIKE '%信息记录类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19246' where TABLE_NAME = 'MBT_230_EX' and  COMMENTS LIKE '%报告时%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19041' where TABLE_NAME = 'MBT_230_EX' and  COMMENTS LIKE '%担保业务种类细分%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19243' where TABLE_NAME = 'MBT_230_EX' and  COMMENTS LIKE '%币种%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19249' where TABLE_NAME = 'MBT_230_EX' and  COMMENTS LIKE '%反担保方式%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19250' where TABLE_NAME = 'MBT_230_EX' and  COMMENTS LIKE '%还款保证%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '219270' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%账户状态%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19020' where TABLE_NAME = 'MBT_230_EX' and  COMMENTS LIKE '%代偿%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '190075' where TABLE_NAME = 'MBT_230_EX' and  COMMENTS LIKE '%反馈状态%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '201333' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS='操作类型';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19202' where TABLE_NAME = 'MBT_230_E_EX' and  COMMENTS LIKE '%身份标识类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19253' where TABLE_NAME = 'MBT_230_E_EX' and  COMMENTS LIKE '%联保%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19252' where TABLE_NAME = 'MBT_230_E_EX' and  COMMENTS LIKE '%责任人类型%';



UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '190075' where TABLE_NAME = 'MBT_211' and  COMMENTS LIKE '%反馈状态%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19255' where TABLE_NAME = 'MBT_211' and  COMMENTS LIKE '%记录类型%';


UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19256' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%账户类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19010' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%证件类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19255' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%记录类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19257' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%报告时%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19242' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%区划%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19235' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%资产转让标志%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19259' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%借贷业务种类细分%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19042' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%借贷业务大%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19243' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%币种%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19233' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%分次%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19264' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%业务经营%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19262' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%担保方式%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19265' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%发放形式%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19263' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%保证方式%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19261' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%还款频率%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19260' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%还款方式%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19273' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%还款状态%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '190075' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%反馈状态%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '219270' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS LIKE '%账户状态%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '201333' where TABLE_NAME = 'MBT_210_EX' and  COMMENTS='操作类型';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19202' where TABLE_NAME = 'MBT_210_D_EX' and  COMMENTS LIKE '%身份标识类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19300' where TABLE_NAME = 'MBT_210_D_EX' and  COMMENTS = '身份类别';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19266' where TABLE_NAME = 'MBT_210_D_EX' and  COMMENTS LIKE '%还款责任人%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19267' where TABLE_NAME = 'MBT_210_D_EX' and  COMMENTS LIKE '%联保%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19285' where TABLE_NAME = 'MBT_210_K_EX' and  COMMENTS LIKE '%交易类型%';



UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19278' where TABLE_NAME = 'MBT_220_EX' and  COMMENTS LIKE '%报告时%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19238' where TABLE_NAME = 'MBT_220_EX' and  COMMENTS LIKE '%额度状态%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19046' where TABLE_NAME = 'MBT_220_EX' and  COMMENTS LIKE '%授信额度类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19237' where TABLE_NAME = 'MBT_220_EX' and  COMMENTS LIKE '%额度循环标志%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19243' where TABLE_NAME = 'MBT_220_EX' and  COMMENTS LIKE '%币种%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '190075' where TABLE_NAME = 'MBT_220_EX' and  COMMENTS LIKE '%反馈状态%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '201333' where TABLE_NAME = 'MBT_220_EX' and  COMMENTS='操作类型';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19010' where TABLE_NAME = 'MBT_220_EX' and  COMMENTS LIKE '%受信人身份标识类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19300' where TABLE_NAME = 'MBT_220_C_EX' and  COMMENTS LIKE '%身份类别%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19202' where TABLE_NAME = 'MBT_220_C_EX' and  COMMENTS LIKE '%身份标识类型%';



UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '190075' where TABLE_NAME = 'MBT_130_EX' and  COMMENTS = '反馈状态';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19242' where TABLE_NAME = 'MBT_130_EX' and  COMMENTS LIKE '%区划%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19010' where TABLE_NAME = 'MBT_130_EX' and  COMMENTS LIKE '%证件类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19284' where TABLE_NAME = 'MBT_130_EX' and  COMMENTS LIKE '%信息记录类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '201333' where TABLE_NAME = 'MBT_130_EX' and  COMMENTS='操作类型';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19086' where TABLE_NAME = 'MBT_440_EX' and  COMMENTS LIKE '%账户类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19232' where TABLE_NAME = 'MBT_440_EX' and  COMMENTS LIKE '%身份标识类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19289' where TABLE_NAME = 'MBT_440_EX' and  COMMENTS LIKE '%信息记录类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19087' where TABLE_NAME = 'MBT_440_EX' and  COMMENTS LIKE '%报告时%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19041' where TABLE_NAME = 'MBT_440_EX' and  COMMENTS LIKE '%担保业务%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19041' where TABLE_NAME = 'MBT_440_EX' and  COMMENTS LIKE '%担保业务%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19243' where TABLE_NAME = 'MBT_440_EX' and  COMMENTS LIKE '%币种%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19090' where TABLE_NAME = 'MBT_440_EX' and  COMMENTS LIKE '%担保方式%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19091' where TABLE_NAME = 'MBT_440_EX' and  COMMENTS LIKE '%其他还款%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19094' where TABLE_NAME = 'MBT_440_EX' and  COMMENTS LIKE '%账户状态%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19239' where TABLE_NAME = 'MBT_440_EX' and  COMMENTS LIKE '%代偿%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19052' where TABLE_NAME = 'MBT_440_EX' and  COMMENTS LIKE '%五级分类%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '201333' where TABLE_NAME = 'MBT_440_EX' and  COMMENTS LIKE '%操作类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19232' where TABLE_NAME = 'MBT_440_D_EX' and  COMMENTS LIKE '%身份标识类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19093' where TABLE_NAME = 'MBT_440_D_EX' and  COMMENTS LIKE '%联保%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19092' where TABLE_NAME = 'MBT_440_D_EX' and  COMMENTS LIKE '%还款责任人类型%';


UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19232' where TABLE_NAME = 'MBT_510_EX' and  COMMENTS LIKE '%身份标识类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19300' where TABLE_NAME = 'MBT_510_EX' and  COMMENTS LIKE '%身份类别%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19155' where TABLE_NAME = 'MBT_510_EX' and  COMMENTS LIKE '%报告时%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19158' where TABLE_NAME = 'MBT_510_EX' and  COMMENTS LIKE '%合同状态%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19243' where TABLE_NAME = 'MBT_510_EX' and  COMMENTS LIKE '%币种%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19156' where TABLE_NAME = 'MBT_510_EX' and  COMMENTS LIKE '%合同类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19157' where TABLE_NAME = 'MBT_510_EX' and  COMMENTS LIKE '%担保标志%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '190075' where TABLE_NAME = 'MBT_510_EX' and  COMMENTS LIKE '%反馈状态%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '201333' where TABLE_NAME = 'MBT_510_EX' and  COMMENTS LIKE '%操作类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19232' where TABLE_NAME = 'MBT_510_D_EX' and  COMMENTS LIKE '%身份标识类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19300' where TABLE_NAME = 'MBT_510_D_EX' and  COMMENTS LIKE '%身份类别%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19160' where TABLE_NAME = 'MBT_510_E_EX' and  COMMENTS LIKE '%抵押物识别%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19300' where TABLE_NAME = 'MBT_510_E_EX' and  COMMENTS LIKE '%身份类别%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19242' where TABLE_NAME = 'MBT_510_E_EX' and  COMMENTS LIKE '%区划%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19161' where TABLE_NAME = 'MBT_510_E_EX' and  COMMENTS LIKE '%评估机构类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19243' where TABLE_NAME = 'MBT_510_F_EX' and  COMMENTS LIKE '%币种%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19232' where TABLE_NAME = 'MBT_510_F_EX' and  COMMENTS LIKE '%身份标识类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19127' where TABLE_NAME = 'MBT_310_EX' and  COMMENTS LIKE '%客户资料类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19232' where TABLE_NAME = 'MBT_310_EX' and  COMMENTS LIKE '%身份标识类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19128' where TABLE_NAME = 'MBT_310_EX' and  COMMENTS LIKE '%存续%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19288' where TABLE_NAME = 'MBT_310_EX' and  COMMENTS LIKE '%信息记录%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19135' where TABLE_NAME = 'MBT_310_EX' and  COMMENTS LIKE '%组织机构%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19126' where TABLE_NAME = 'MBT_310_EX' and  COMMENTS LIKE '%报告时%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19242' where TABLE_NAME = 'MBT_310_EX' and  COMMENTS LIKE '%区划%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19240' where TABLE_NAME = 'MBT_310_EX' and  COMMENTS LIKE '%行业分类%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19136' where TABLE_NAME = 'MBT_310_EX' and  COMMENTS LIKE '%经济类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19137' where TABLE_NAME = 'MBT_310_EX' and  COMMENTS LIKE '%企业规模%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19241' where TABLE_NAME = 'MBT_310_EX' and  COMMENTS LIKE '%国别%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19243' where TABLE_NAME = 'MBT_310_EX' and  COMMENTS LIKE '%币种%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19131' where TABLE_NAME = 'MBT_310_EX' and  COMMENTS LIKE '%上级机构类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '201333' where TABLE_NAME = 'MBT_310_EX' and  COMMENTS LIKE '%操作类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19232' where TABLE_NAME = 'MBT_310_C_EX' and  COMMENTS LIKE '%身份标识类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19232' where TABLE_NAME = 'MBT_310_E_EX' and  COMMENTS LIKE '%身份标识类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19202' where TABLE_NAME = 'MBT_310_E_EX' and  COMMENTS LIKE '%证件类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19015' where TABLE_NAME = 'MBT_310_E_EX' and  COMMENTS LIKE '%职位%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19232' where TABLE_NAME = 'MBT_310_F_EX' and  COMMENTS LIKE '%身份标识类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19014' where TABLE_NAME = 'MBT_310_F_EX' and  COMMENTS LIKE '%出资人类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19300' where TABLE_NAME = 'MBT_310_G_EX' and  COMMENTS LIKE '%身份类别%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19232' where TABLE_NAME = 'MBT_310_G_EX' and  COMMENTS LIKE '%身份标识类型%';



UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19289' where TABLE_NAME = 'MBT_411' and  COMMENTS LIKE '%记录类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19097' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%账户类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19232' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%身份标识类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19289' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%信息记录类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19098' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%报告时%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19242' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%区划%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19235' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%资产转让标志%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19030' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%借贷业务种类细分%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19029' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%借贷业务大类%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19243' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%币种%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19233' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%分次放款%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19117' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%业务经营类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19113' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%担保方式%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19115' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%期限分类%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19889' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%贷款发放%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19114' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%其他%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19111' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%还款方式%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19112' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%还款频率%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19236' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%还款状态%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19052' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%五级分类%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19122' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%还款形式%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '201333' where TABLE_NAME = 'MBT_410_EX' and  COMMENTS LIKE '%操作类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19232' where TABLE_NAME = 'MBT_410_D_EX' and  COMMENTS LIKE '%身份标识类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19300' where TABLE_NAME = 'MBT_410_D_EX' and  COMMENTS LIKE '%身份类别%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19118' where TABLE_NAME = 'MBT_410_D_EX' and  COMMENTS LIKE '%还款责任人类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19119' where TABLE_NAME = 'MBT_410_D_EX' and  COMMENTS LIKE '%联保%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19123' where TABLE_NAME = 'MBT_410_I_EX' and  COMMENTS LIKE '%交易类型%';


UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19232' where TABLE_NAME = 'MBT_420_EX' and  COMMENTS LIKE '%身份标识类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19289' where TABLE_NAME = 'MBT_420_EX' and  COMMENTS LIKE '%信息记录类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19082' where TABLE_NAME = 'MBT_420_EX' and  COMMENTS LIKE '%报告时%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19238' where TABLE_NAME = 'MBT_420_EX' and  COMMENTS LIKE '%额度状态%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19083' where TABLE_NAME = 'MBT_420_EX' and  COMMENTS LIKE '%额度类型%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19243' where TABLE_NAME = 'MBT_420_EX' and  COMMENTS LIKE '%币种%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19237' where TABLE_NAME = 'MBT_420_EX' and  COMMENTS LIKE '%额度循环%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19300' where TABLE_NAME = 'MBT_420_C_EX' and  COMMENTS LIKE '%身份类别%';
UPDATE gp_bm_tab_col_cfg SET EXIST_DATADIC = 'Y', DATA_TYPE_NO = '19232' where TABLE_NAME = 'MBT_420_C_EX' and  COMMENTS LIKE '%身份标识类型%';
	
commit;


--ce61
UPDATE GP_BM_INQ_CFG SET SQL_STRING = 'SELECT DATA_APV_USER,DATA_APV_TIME,DATA_REJ_DESC,DATA_DESC,DATA_STATUS,INF_REC_TYPE,OD_BNES_CODE,NW_BNES_CODE,DATA_VERSION,DATA_ID FROM MBT_441_HIS where 1=1 @{_PRIV_COND} and OD_BNES_CODE =:"odBnesCode" and CORP_ID=:"v_corpid"' WHERE DATA_ID= 'Mbt441HisQry';
UPDATE GP_BM_INQ_CFG SET SQL_STRING = 'SELECT DATA_APV_USER,DATA_APV_TIME,DATA_REJ_DESC,DATA_DESC,INF_REC_TYPE,DATA_STATUS,OD_BNES_CODE,NW_BNES_CODE,DATA_VERSION,DATA_ID FROM MBT_441_RPT where 1=1 @{_PRIV_COND} and OD_BNES_CODE =:"odBnesCode" and CORP_ID=:"v_corpid"' WHERE DATA_ID= 'Mbt441RptQry';

--qingyong.wang over

--xiangchong.wang
--ce_51
--MBT_210R2101204R2101204001R2101204002
--待入库个人借贷账户信息记录中的“账户类型”必须与已入库记录的“账户类型”一致。
update gp_qc_rule set sql = 'select 1
  from (select count(*) as tcnt
          FROM MBT_210_RPT
         WHERE (MBT_210_RPT.B_ACCT_CODE=:B_ACCT_CODE)
           AND (MBT_210_RPT.B_ACCT_TYPE=:B_ACCT_TYPE)
        union all
        select case
                 when count(1) = 0 then
                  1
                 else
                  0
               end
          from MBT_210_RPT
         where MBT_210_RPT.B_ACCT_CODE =:B_ACCT_CODE)
 where tcnt > 0'
 where data_id = 'MBT_210R2101204R2101204001R2101204002';


COMMIT;


--CE_12
--MBT_310EI3100E01   新增   
--报送主要组成人员信息段时，法定代表人/非法人组织负责人、董事长、监事长各自只能报一个人
--新增map
insert into gp_qc_rule_map (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
values ('MBT_310EI3100E01', '20190624', 'TESTCORP', '72', '002', null, null, 'MBT_310_1700604', 'MBT_310EI3100E01', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'mbtrule', null);
--新增rule
insert into gp_qc_rule (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, SQL, SQL_EXTRA_KEY, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
values ('MBT_310EI3100E01', '20190624', 'TESTCORP', '72', '002', null, null, '报送主要组成人员信息段时，法定代表人/非法人组织负责人、董事长、监事长各自只能报一 个人', '报送主要组成人员信息段时，法定代表人/非法人组织负责人、董事长、监事长各自只能报一 个人', null, 'BUSI', 'DATA_ID', null, null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, '  select 1
   from (select case
                  when count(*) = 0 and :IS_RPT is not null and
                       substr(:IS_RPT, 7, 1) = 1 then
                   0
                  else
                   1
                end as tcnt
           from (select *
                   from (select MMB_PSTN
                           from mbt_310_e mbt
                          where  PDATA_ID= :DATA_ID and MMB_PSTN in (1, 4, 5)
                          group by MMB_PSTN
                         having count(*) > 1)
                  ))
  where tcnt = 0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
  

--MBT_310_EI3100E02I3100E0201I3100E0202   
--报送主要组成人员信息段时，法定代表人/非法人组织负责人必报。 
update gp_qc_rule set sql = 'select 1
   from (select case
                  when count(*) > 0 and :IS_RPT is not null and
                       substr(:IS_RPT, 7, 1) = 1 then
                   0
                  else
                   1
                end as tcnt
           from (select *
                   from (select MMB_PSTN
                           from mbt_310_e
                          where  PDATA_ID= :DATA_ID and MMB_PSTN in(1)
                          group by MMB_PSTN
                         having count(*) >0)
                  ))
  where tcnt = 0',script = '' where data_id = 'MBT_310_EI3100E02I3100E0201I3100E0202';



--MBT_310I3100E03 新增 
--报送主要组成人员信息段时，董事长、监事长不能是同一个人。 
--新增map
insert into gp_qc_rule_map (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
values ('MBT_310I3100E03', '20200721', 'TESTCORP', '72', '002', null, null, 'MBT_310_1700604', 'MBT_310I3100E03', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'mbtrule', null);
--新增rule
insert into gp_qc_rule (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, SQL, SQL_EXTRA_KEY, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
values ('MBT_310I3100E03', '20200721', 'TESTCORP', '72', '002', null, null, '报送主要组成人员信息段时，董事长、监事长不能是同一个人。', '报送主要组成人员信息段时，董事长、监事长不能是同一个人。', null, 'BUSI', 'DATA_ID', null, null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, 'select 1
   from (select case
                  when count(*) = 0 and :IS_RPT is not null and
                       substr(:IS_RPT, 7, 1) = 1 then
                   0
                  else
                   1
                end as tcnt
           from (select * 
                   from (select MMB_ALIAS
                           from mbt_310_e
                          where  PDATA_ID= :DATA_ID and MMB_PSTN in (4,5) 
                          group by MMB_ALIAS
                         having count(*) > 1)
                  ))
  where tcnt = 0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
  
  
  --CE-56
--MBT_350_10090201I3500B01 新增
-- 企业关联信息记录中两组“企业身份标识类型”、“企业身份标识号码”不能完全相同。
--CMP_VALID_FORM_CFG
INSERT INTO CMP_VALID_FORM_CFG (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FORM_NAME, FUNC_ID, EFFECTIVE_FLAG, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('f497da238eb0439a980c219b63d21022', '20190614', 'TESTCORP', '72', '002', null, null, 'MBT_350', '201801031', '1', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
--CMP_VALID_FORM_LIST
insert into CMP_VALID_FORM_LIST (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FORM_NAME, FORM_DESC_CN, FUNC_ID, FUNC_NAME, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, MAIN_FLAG, FORM_TAG)
values ('b9f8ac099db5441e9f2322bb1cc776eb', '20200720', 'TESTCORP', null, null, null, null, 'MBT_350', '企业关系关联信息', '201801031', '企业关系关联信息', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', 'B');
--gp_qc_rule_set
insert into gp_qc_rule_set (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_DESC, ENTITY, MODULE, ACTION, SOURCE, VERSION, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
values ('MBT_350_10090201', '20200120', 'TESTCORP', null, null, null, null, '企业关联关系信息', 'MBT_350', '201801031', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'mbt', null);
--gp_qc_rule_map
insert into gp_qc_rule_map (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
values ('MBT_350_10090201I3500B01', '20200720', 'TESTCORP', '72', '002', null, null, 'MBT_350_10090201', 'MBT_350_10090201I3500B01', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'mbtrule', null);
--gp_qc_rule
insert into gp_qc_rule (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, SQL, SQL_EXTRA_KEY, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
values ('MBT_350_10090201I3500B01', '20200720', 'TESTCORP', '72', '002', null, null, '企业关联信息记录中两组“企业身份标识类型”、“企业身份标识号码”不能完全相同。 ', '企业关联信息记录中两组“企业身份标识类型”、“企业身份标识号码”不能完全相同。 ', null, 'BUSI', 'DATA_ID', null, null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'return !(B_ENT_CERT_TYPE.equals(B_ASSO_ENT_CERT_TYPE) && B_ENT_CERT_NUM.equals(B_ASSO_ENT_CERT_NUM))', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

--ce_49
--MBT_211I2111B02 
--原业务标识码必须是库中已有且正在使用的
--map表新建
insert into gp_qc_rule_map (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
values ('MBT_211I2111B02', '20191206', 'TESTCORP', '72', '002', null, null, 'MBT_211_2019020201', 'MBT_211I2111B02', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'mbtrule', null);
--rule表新建
insert into gp_qc_rule (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, SQL, SQL_EXTRA_KEY, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
values ('MBT_211I2111B02', '20191206', 'TESTCORP', '72', '002', null, null, '原业务标识码必须是库中已有且正在使用的', '原业务标识码必须是库中已有且正在使用的', null, 'BUSI', 'DATA_ID', null, null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, 'select 1 from (select count(*) as tcnt from mbt_210,mbt_210_rpt 
where (mbt_210.B_ACCT_CODE=:OD_BNES_CODE) 
and (mbt_210_rpt.B_ACCT_CODE=:OD_BNES_CODE))where tcnt>0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);  

--MBT_211I2111B03
--新业务标识码在数据库中必须不存在，或者在库中存在但必须是该账户之前使用过的标识。
--map表新建
insert into gp_qc_rule_map (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
values ('MBT_211I2111B03', '20191206', 'TESTCORP', '72', '002', null, null, 'MBT_211_2019020201', 'MBT_211I2111B03', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'mbtrule', null);
--rule表新建
insert into gp_qc_rule (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, SQL, SQL_EXTRA_KEY, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
values ('MBT_211I2111B03', '20191206', 'TESTCORP', '72', '002', null, null, '新业务标识码在数据库中必须不存在，或者在库中存在但必须是该账户之前使用过的标识。', '新业务标识码在数据库中必须不存在，或者在库中存在但必须是该账户之前使用过的标识。', null, 'BUSI', 'DATA_ID', null, null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, 'select 1
  from (select count(*) as tcnt
          from mbt_210, mbt_211_his
         where (mbt_210.B_ACCT_CODE <> :NW_BNES_CODE)
            or (mbt_211_his.OD_BNES_CODE = :NW_BNES_CODE and mbt_211_his.ODS_DATA_ID = :DATA_ID))
 where tcnt > 0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);


commit;
  




