--向ODS_MBT_110_C中添加业务标识：证件类型+证件号码+信息来源编码
ALTER TABLE ODS_MBT_110_C ADD (B_ID_TYPE VARCHAR2(2));
ALTER TABLE ODS_MBT_110_C ADD (B_ID_NUM NVARCHAR2(20));
ALTER TABLE ODS_MBT_110_C ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN ODS_MBT_110_C.B_ID_TYPE IS '证件类型';
COMMENT ON COLUMN ODS_MBT_110_C.B_ID_NUM IS '证件号码';
COMMENT ON COLUMN ODS_MBT_110_C.B_INF_SURC_CODE IS '信息来源编码';

--向ODS_MBT_110_C_HIS 中添加业务标识：证件类型+证件号码+信息来源编码
ALTER TABLE ODS_MBT_110_C_HIS ADD (B_ID_TYPE VARCHAR2(2));
ALTER TABLE ODS_MBT_110_C_HIS ADD (B_ID_NUM NVARCHAR2(20));
ALTER TABLE ODS_MBT_110_C_HIS ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN ODS_MBT_110_C_HIS.B_ID_TYPE IS '证件类型';
COMMENT ON COLUMN ODS_MBT_110_C_HIS.B_ID_NUM IS '证件号码';
COMMENT ON COLUMN ODS_MBT_110_C_HIS.B_INF_SURC_CODE IS '信息来源编码';

--向MBT_110_C中添加业务标识：证件类型+证件号码+信息来源编码
ALTER TABLE MBT_110_C ADD (B_ID_TYPE VARCHAR2(2));
ALTER TABLE MBT_110_C ADD (B_ID_NUM NVARCHAR2(20));
ALTER TABLE MBT_110_C ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_110_C.B_ID_TYPE IS '证件类型';
COMMENT ON COLUMN MBT_110_C.B_ID_NUM IS '证件号码';
COMMENT ON COLUMN MBT_110_C.B_INF_SURC_CODE IS '信息来源编码';

--向MBT_110_C_HIS中添加业务标识：证件类型+证件号码+信息来源编码
ALTER TABLE MBT_110_C_HIS ADD (B_ID_TYPE VARCHAR2(2));
ALTER TABLE MBT_110_C_HIS ADD (B_ID_NUM NVARCHAR2(20));
ALTER TABLE MBT_110_C_HIS ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_110_C_HIS.B_ID_TYPE IS '证件类型';
COMMENT ON COLUMN MBT_110_C_HIS.B_ID_NUM IS '证件号码';
COMMENT ON COLUMN MBT_110_C_HIS.B_INF_SURC_CODE IS '信息来源编码';

--向MBT_110_C_RPT中添加业务标识：证件类型+证件号码+信息来源编码
ALTER TABLE MBT_110_C_RPT ADD (B_ID_TYPE VARCHAR2(2));
ALTER TABLE MBT_110_C_RPT ADD (B_ID_NUM NVARCHAR2(20));
ALTER TABLE MBT_110_C_RPT ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_110_C_RPT.B_ID_TYPE IS '证件类型';
COMMENT ON COLUMN MBT_110_C_RPT.B_ID_NUM IS '证件号码';
COMMENT ON COLUMN MBT_110_C_RPT.B_INF_SURC_CODE IS '信息来源编码';

--向MBT_110_C_TMP中添加业务标识：证件类型+证件号码+信息来源编码
ALTER TABLE MBT_110_C_TMP ADD (B_ID_TYPE VARCHAR2(2));
ALTER TABLE MBT_110_C_TMP ADD (B_ID_NUM NVARCHAR2(20));
ALTER TABLE MBT_110_C_TMP ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_110_C_TMP.B_ID_TYPE IS '证件类型';
COMMENT ON COLUMN MBT_110_C_TMP.B_ID_NUM IS '证件号码';
COMMENT ON COLUMN MBT_110_C_TMP.B_INF_SURC_CODE IS '信息来源编码';

--向MBT_110_C_TODAY_BAK中添加业务标识：证件类型+证件号码+信息来源编码
ALTER TABLE MBT_110_C_TODAY_BAK ADD (B_ID_TYPE VARCHAR2(2));
ALTER TABLE MBT_110_C_TODAY_BAK ADD (B_ID_NUM NVARCHAR2(20));
ALTER TABLE MBT_110_C_TODAY_BAK ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_110_C_TODAY_BAK.B_ID_TYPE IS '证件类型';
COMMENT ON COLUMN MBT_110_C_TODAY_BAK.B_ID_NUM IS '证件号码';
COMMENT ON COLUMN MBT_110_C_TODAY_BAK.B_INF_SURC_CODE IS '信息来源编码';

--向ODS_MBT_215中添加IS_RPT
ALTER TABLE ODS_MBT_215 ADD (IS_RPT VARCHAR2(64));
COMMENT ON COLUMN ODS_MBT_215.IS_RPT IS '是否上报';

--向ODS_MBT_215_HIS 中添加IS_RPT
ALTER TABLE ODS_MBT_215_HIS ADD (IS_RPT VARCHAR2(64));
COMMENT ON COLUMN ODS_MBT_215_HIS.IS_RPT IS '是否上报';

--向MBT_215中添加IS_RPT
ALTER TABLE MBT_215 ADD (IS_RPT VARCHAR2(64));
COMMENT ON COLUMN MBT_215.IS_RPT IS '是否上报';

--向MBT_215_HIS中添加IS_RPT
ALTER TABLE MBT_215_HIS ADD (IS_RPT VARCHAR2(64));
COMMENT ON COLUMN MBT_215_HIS.IS_RPT IS '是否上报';

--向MBT_215_RPT中添加IS_RPT
ALTER TABLE MBT_215_RPT ADD (IS_RPT VARCHAR2(64));
COMMENT ON COLUMN MBT_215_RPT.IS_RPT IS '是否上报';

--向MBT_215_TMP中添加IS_RPT
ALTER TABLE MBT_215_TMP ADD (IS_RPT VARCHAR2(64));
COMMENT ON COLUMN MBT_215_TMP.IS_RPT IS '是否上报';

--向MBT_215_TODAY_BAK中添加IS_RPT
ALTER TABLE MBT_215_TODAY_BAK ADD (IS_RPT VARCHAR2(64));
COMMENT ON COLUMN MBT_215_TODAY_BAK.IS_RPT IS '是否上报';

--向 ODS_MBT_310_C 中添加B_INF_SURC_CODE
ALTER TABLE ODS_MBT_310_C ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN ODS_MBT_310_C.B_INF_SURC_CODE IS '信息来源编码';
--向 ODS_MBT_310_E 中添加B_INF_SURC_CODE
ALTER TABLE ODS_MBT_310_E ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN ODS_MBT_310_E.B_INF_SURC_CODE IS '信息来源编码';
--向 ODS_MBT_310_F 中添加B_INF_SURC_CODE
ALTER TABLE ODS_MBT_310_F ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN ODS_MBT_310_F.B_INF_SURC_CODE IS '信息来源编码';
--向 ODS_MBT_310_G 中添加B_INF_SURC_CODE
ALTER TABLE ODS_MBT_310_G ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN ODS_MBT_310_G.B_INF_SURC_CODE IS '信息来源编码';


--向 ODS_MBT_310_C_HIS 中添加B_INF_SURC_CODE
ALTER TABLE ODS_MBT_310_C_HIS ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN ODS_MBT_310_C_HIS.B_INF_SURC_CODE IS '信息来源编码';
--向 ODS_MBT_310_E_HIS 中添加B_INF_SURC_CODE
ALTER TABLE ODS_MBT_310_E_HIS ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN ODS_MBT_310_E_HIS.B_INF_SURC_CODE IS '信息来源编码';
--向 ODS_MBT_310_F_HIS 中添加B_INF_SURC_CODE
ALTER TABLE ODS_MBT_310_F_HIS ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN ODS_MBT_310_F_HIS.B_INF_SURC_CODE IS '信息来源编码';
--向 ODS_MBT_310_G_HIS 中添加B_INF_SURC_CODE
ALTER TABLE ODS_MBT_310_G_HIS ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN ODS_MBT_310_G_HIS.B_INF_SURC_CODE IS '信息来源编码';

--向 MBT_310_C 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_C ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_C.B_INF_SURC_CODE IS '信息来源编码';
--向 MBT_310_E 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_E ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_E.B_INF_SURC_CODE IS '信息来源编码';
--向 MBT_310_F 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_F ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_F.B_INF_SURC_CODE IS '信息来源编码';
--向 MBT_310_G 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_G ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_G.B_INF_SURC_CODE IS '信息来源编码';

--向 MBT_310_C_HIS 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_C_HIS ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_C_HIS.B_INF_SURC_CODE IS '信息来源编码';
--向 MBT_310_E_HIS 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_E_HIS ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_E_HIS.B_INF_SURC_CODE IS '信息来源编码';
--向 MBT_310_F_HIS 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_F_HIS ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_F_HIS.B_INF_SURC_CODE IS '信息来源编码';
--向 MBT_310_G_HIS 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_G_HIS ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_G_HIS.B_INF_SURC_CODE IS '信息来源编码';

--向 MBT_310_C_RPT 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_C_RPT ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_C_RPT.B_INF_SURC_CODE IS '信息来源编码';
--向 MBT_310_E_RPT 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_E_RPT ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_E_RPT.B_INF_SURC_CODE IS '信息来源编码';
--向 MBT_310_F_RPT 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_F_RPT ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_F_RPT.B_INF_SURC_CODE IS '信息来源编码';
--向 MBT_310_G_RPT 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_G_RPT ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_G_RPT.B_INF_SURC_CODE IS '信息来源编码';

--向 MBT_310_C_TMP 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_C_TMP ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_C_TMP.B_INF_SURC_CODE IS '信息来源编码';
--向 MBT_310_E_TMP 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_E_TMP ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_E_TMP.B_INF_SURC_CODE IS '信息来源编码';
--向 MBT_310_F_TMP 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_F_TMP ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_F_TMP.B_INF_SURC_CODE IS '信息来源编码';
--向 MBT_310_G_TMP 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_G_TMP ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_G_TMP.B_INF_SURC_CODE IS '信息来源编码';

--向 MBT_310_C_TODAY_BAK 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_C_TODAY_BAK ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_C_TODAY_BAK.B_INF_SURC_CODE IS '信息来源编码';
--向 MBT_310_E_TODAY_BAK 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_E_TODAY_BAK ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_E_TODAY_BAK.B_INF_SURC_CODE IS '信息来源编码';
--向 MBT_310_F_TODAY_BAK 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_F_TODAY_BAK ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_F_TODAY_BAK.B_INF_SURC_CODE IS '信息来源编码';
--向 MBT_310_G_TODAY_BAK 中添加B_INF_SURC_CODE
ALTER TABLE MBT_310_G_TODAY_BAK ADD (B_INF_SURC_CODE VARCHAR2(20));
COMMENT ON COLUMN MBT_310_G_TODAY_BAK.B_INF_SURC_CODE IS '信息来源编码';

