create view GP_BM_FUNCTION as
select *
from (SELECT menu.DATA_ID,
             menu.MENU_ID   FUNCID,
             menu.MENU_NAME FUNCNAME,
             menu.LOCATION,
             menu.ICON_CLS,
             menu.LASTDIRECTORY,
             menu.ISDIRECTORY,
             menu.SHOWSEQ,
             page.PAGE_PATH PAGEPATH,
             menu.ISVALID   STATUS,
             1              WORKFLOW_FLAG,
             menu.PARENT_ID UP_FUNC_CODE,
             ''             TIMESTAMPS,
             ''             SYS_NUM,
             ''             RSV5,
             ''             RSV4,
             ''             RSV3,
             ''             RSV2,
             ''             RSV1,
             ''             REMARKS,
             1              MISCFLGS,
             ''             MISC,
             menu.NEXT_ACTION,
             menu.ORG_ID,
             menu.CORP_ID,
             menu.GROUP_ID,
             page.PAGE_TYPE,
             '0'            FUNC_TYPE,
             ''             FUNC_DESC,
             ''             FUNC_CLASS,
             ''             EXPIRE_DATE,
             ''             EFFECT_DATE,
             0              DATA_VERSION,
             ''             DATA_STATUS,
             ''             DATA_SOURCE,
             ''             DATA_REJ_DESC,
             ''             DATA_FLAG,
             ''             DATA_DEL_DESC,
             ''             CHECK_FLAG,
             ''             CHECK_DESC,
             ''             CHECK_ERR_TYPE,
             menu.DATA_DATE,
             menu.DATA_CRT_USER,
             menu.DATA_CRT_TIME,
             menu.DATA_CRT_DATE,
             menu.DATA_CHG_USER,
             menu.DATA_CHG_TIME,
             menu.DATA_CHG_DATE,
             menu.DATA_APV_USER,
             menu.DATA_APV_TIME,
             menu.DATA_APV_DATE
      FROM GP_BM_MENU menu
               LEFT JOIN GP_BM_RES_PAGES page ON menu.PAGE_ID = page.PAGE_ID
      UNION
      select pageBtn.DATA_ID,
             pageBtn.BTN_ID   FUNCID,
             pageBtn.BTN_NAME FUNCNAME,
             1                LOCATION,
             ''               ICON_CLS,
             menu.MENU_ID     LASTDIRECTORY,
             0                ISDIRECTORY,
             0                SHOWSEQ,
             pageBtn.BTN_PATH PAGEPATH,
             menu.ISVALID     STATUS,
             1                WORKFLOW_FLAG,
             menu.MENU_ID     UP_FUNC_CODE,
             ''               TIMESTAMPS,
             ''               SYS_NUM,
             ''               RSV5,
             ''               RSV4,
             ''               RSV3,
             ''               RSV2,
             ''               RSV1,
             ''               REMARKS,
             1                MISCFLGS,
             ''               MISC,
             pageBtn.NEXT_ACTION,
             pageBtn.ORG_ID,
             pageBtn.CORP_ID,
             pageBtn.GROUP_ID,
             page.PAGE_TYPE,
             '1'              FUNC_TYPE,
             ''               FUNC_DESC,
             ''               FUNC_CLASS,
             ''               EXPIRE_DATE,
             ''               EFFECT_DATE,
             0                DATA_VERSION,
             ''               DATA_STATUS,
             ''               DATA_SOURCE,
             ''               DATA_REJ_DESC,
             ''               DATA_FLAG,
             ''               DATA_DEL_DESC,
             ''               CHECK_FLAG,
             ''               CHECK_DESC,
             ''               CHECK_ERR_TYPE,
             pageBtn.DATA_DATE,
             pageBtn.DATA_CRT_USER,
             pageBtn.DATA_CRT_TIME,
             pageBtn.DATA_CRT_DATE,
             pageBtn.DATA_CHG_USER,
             pageBtn.DATA_CHG_TIME,
             pageBtn.DATA_CHG_DATE,
             pageBtn.DATA_APV_USER,
             pageBtn.DATA_APV_TIME,
             pageBtn.DATA_APV_DATE
      from GP_BM_RES_PAGE_BTN pageBtn
               inner join GP_BM_RES_PAGES page on pageBtn.PAGE_ID = page.PAGE_ID
               inner join GP_BM_MENU menu on menu.PAGE_ID = page.PAGE_ID) T
order by SHOWSEQ