delete from GP_QC_RULE where DATA_ID in ('JS2455','JS2462','JS2038','JS2040','JS1113','JS1114','JS1143','JS1144');
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1113', null, null, null, null, 'gfdr', 'CLWTDK', '当委托人国民经济部门不为特定目的载体时，委托人地区代码不能为空', '当委托人国民经济部门不为特定目的载体时，委托人地区代码不能为空', '非空校验', '人民银行', 'WTRDQDM', '委托人地区代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(WTRGMJJBM != "B09"){
                return isNotEmpty($value)
            }
            return true', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1113', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1114', null, null, null, null, 'gfdr', 'CLWTDK', '当委托人不为个人、境外非居民、境内非企业以及特定目的载体时，委托人经济成分不能为空', '当委托人不为个人、境外非居民、境内非企业以及特定目的载体时，委托人经济成分不能为空', '非空校验', '人民银行', 'WTRJJCF', '委托人经济成分', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(!(WTRHY in ["100","200"])  && WTRQYGM != "CS05"  && WTRGMJJBM != "B09" ){
                return isNotEmpty($value)
            }
            return true', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1114', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1143', null, null, null, null, 'gfdr', 'WTDKFS', '当委托人国民经济部门不为特定目的载体时，委托人地区代码不能为空', '当委托人国民经济部门不为特定目的载体时，委托人地区代码不能为空', '非空校验', '人民银行', 'WTRDQDM', '委托人地区代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(WTRGMJJBM != "B09"){
                return isNotEmpty($value)
            }
            return true', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1143', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1144', null, null, null, null, 'gfdr', 'WTDKFS', '当委托人不为个人、境外、境内非企业以及特定目的载体时，委托人经济成分不能为空', '当委托人不为个人、境外、境内非企业以及特定目的载体时，委托人经济成分不能为空', '非空校验', '人民银行', 'WTRJJCF', '委托人经济成分', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(!(WTRHY in ["100","200"])  && WTRQYGM != "CS05" && WTRGMJJBM != "B09"){
                return isNotEmpty($value)
            }
            return true', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1144', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2038', null, null, null, null, 'gfdr', 'CLWTDK', '当委托人为个人、境外非居民、境内非企业或特定目的载体时，委托人经济成分必须为空', '当委托人为个人、境外非居民、境内非企业或特定目的载体时，委托人经济成分必须为空', '表内逻辑校验', '人民银行', 'WTRJJCF', '委托人经济成分', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value) && (WTRHY in ["100","200"]  || WTRQYGM == "CS05"  || WTRGMJJBM == "B09")){
                return Objects.toString(WTRJJCF, "").length() == 0
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2038', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2040', null, null, null, null, 'gfdr', 'WTDKFS', '当委托人为个人、境外非居民、境内非企业或特定目的载体时，委托人经济成分必须为空', '当委托人为个人、境外非居民、境内非企业或特定目的载体时，委托人经济成分必须为空', '表内逻辑校验', '人民银行', 'WTRJJCF', '委托人经济成分', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value) && (WTRHY in ["100","200"]  || WTRQYGM == "CS05"  || WTRGMJJBM == "B09" )){
                return Objects.toString(WTRJJCF, "").length() == 0
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2040', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2455', null, null, null, null, 'gfdr', 'CLWTDK', '手续费金额折人民币应大于0', '手续费金额折人民币应大于0', '表内逻辑校验', '人民银行', 'SXFJEZRMB_AMT', '手续费金额折人民币', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value)){
                return (SXFJEZRMB_AMT as BigDecimal) > 0 
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2455', 'Q', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2462', null, null, null, null, 'gfdr', 'WTDKFS', '手续费金额折人民币应大于0', '手续费金额折人民币应大于0', '表内逻辑校验', '人民银行', 'SXFJEZRMB_AMT', '手续费金额折人民币', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value)){
                return (SXFJEZRMB_AMT as BigDecimal) > 0 
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2462', 'Q', null, null, null);