update GFDR_BM_RPT_CFG_DTL set SEQ_NO = 3 where REPORT_CODE = 'WTDKFS' and COLUMN_NAME = 'JKRZJLX';
update GFDR_BM_RPT_CFG_DTL set SEQ_NO = 4 where REPORT_CODE = 'WTDKFS' and COLUMN_NAME = 'JKRZJDM';
update GFDR_BM_RPT_CFG_DTL set SEQ_NO = 5 where REPORT_CODE = 'WTDKFS' and COLUMN_NAME = 'JKRGMJJBM';


