delete from GP_BM_ID_FUNCTIONDATA where FUNC_NAME in ('headPatternDataId(${value})', 'headPatternSpecificField(${value})');
INSERT INTO GP_BM_ID_FUNCTIONDATA (FUNC_NAME, FUNC_FLAG, FUNC_DESC, FILLER1, FILLER2, FILLER3, DATA_HASH) VALUES ('headPatternDataId(${value})', '1', '表头模式主键字段${value}为空字符串时，生成guid', null, null, null, null);
INSERT INTO GP_BM_ID_FUNCTIONDATA (FUNC_NAME, FUNC_FLAG, FUNC_DESC, FILLER1, FILLER2, FILLER3, DATA_HASH) VALUES ('headPatternSpecificField(${value})', '1', '表头模式取源值', null, null, null, null);

delete from GP_BM_DATA_DIC where DATA_TYPE_NO = 4010 and DATA_NO not in ('7','8','9');

delete from GP_QC_RULE where DATA_ID in ('JS2455', 'JS1708','JS1709','JS1719','JS1720','JS1898','JS1899','JS1900','JS1901','JS1902','JS1903','JS1904','JS1905','JS1906','JS1907','JS2048','JS2049','JS2050','JS2655','JS2656','JS2657','JS2658','JS2659','JS2660','JS2661','JS2662','JS2663','JS2664');

INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2455', null, null, null, null, 'gfdr', 'CLWTDK', '手续费金额折人民币应大于0', '手续费金额折人民币应大于0', '表内逻辑校验', '人民银行', 'SXFJEZRMB_AMT', '手续费金额折人民币', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value)){
                return (SXFJEZRMB_AMT as BigDecimal) > 0 
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2455', 'Q', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1708', null, null, null, null, 'gfdr', 'WTDKFS', '借款人证件类型与存量委托贷款信息的借款人证件类型应该一致', '借款人证件类型与存量委托贷款信息的借款人证件类型应该一致', '关联一致校验', '人民银行', 'JKRZJLX', '借款人证件类型', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'isEmpty($value) || !exists("CLWTDK", ["NBJGH":NBJGH, "WTDKHTBM":WTDKHTBM, "WTDKJJBM":WTDKJJBM]) || exists("CLWTDK", ["NBJGH":NBJGH, "WTDKHTBM":WTDKHTBM, "WTDKJJBM":WTDKJJBM, "JKRZJLX":JKRZJLX])', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1708', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1709', null, null, null, null, 'gfdr', 'WTDKFS', '借款人证件代码与存量委托贷款信息的借款人证件代码应该一致', '借款人证件代码与存量委托贷款信息的借款人证件代码应该一致', '关联一致校验', '人民银行', 'JKRZJDM', '借款人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'isEmpty($value) || !exists("CLWTDK", ["NBJGH":NBJGH, "WTDKHTBM":WTDKHTBM, "WTDKJJBM":WTDKJJBM]) || exists("CLWTDK", ["NBJGH":NBJGH, "WTDKHTBM":WTDKHTBM, "WTDKJJBM":WTDKJJBM, "JKRZJDM":JKRZJDM])', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1709', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1719', null, null, null, null, 'gfdr', 'WTDKFS', '委托人证件类型与存量委托贷款信息的委托人证件类型应该一致', '委托人证件类型与存量委托贷款信息的委托人证件类型应该一致', '关联一致校验', '人民银行', 'WTRZJLX', '委托人证件类型', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'isEmpty($value) || !exists("CLWTDK", ["NBJGH":NBJGH, "WTDKHTBM":WTDKHTBM, "WTDKJJBM":WTDKJJBM]) || exists("CLWTDK", ["NBJGH":NBJGH, "WTDKHTBM":WTDKHTBM, "WTDKJJBM":WTDKJJBM, "WTRZJLX":WTRZJLX])', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1719', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1720', null, null, null, null, 'gfdr', 'WTDKFS', '委托人证件代码与存量委托贷款信息的委托人证件代码应该一致', '委托人证件代码与存量委托贷款信息的委托人证件代码应该一致', '关联一致校验', '人民银行', 'WTRZJDM', '委托人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'isEmpty($value) || !exists("CLWTDK", ["NBJGH":NBJGH, "WTDKHTBM":WTDKHTBM, "WTDKJJBM":WTDKJJBM]) || exists("CLWTDK", ["NBJGH":NBJGH, "WTDKHTBM":WTDKHTBM, "WTDKJJBM":WTDKJJBM, "WTRZJDM":WTRZJDM])', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1720', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1898', null, null, null, null, 'gfdr', 'CLWTDK', '委托人为同业客户的证件代码应该在同业客户基础信息.客户代码中存在', '委托人为同业客户的证件代码应该在同业客户基础信息.客户代码中存在', '关联存在校验', '人民银行', 'WTRZJDM', '委托人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if((WTRGMJJBM?.startsWith("B") && WTRGMJJBM!="B09") ||  WTRGMJJBM=="E03"){
                return exists("TYKHXX", "KHDM", JKRZJDM)
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1898', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1899', null, null, null, null, 'gfdr', 'WTDKFS', '委托人为同业客户的证件代码应该在同业客户基础信息.客户代码中存在', '委托人为同业客户的证件代码应该在同业客户基础信息.客户代码中存在', '关联存在校验', '人民银行', 'WTRZJDM', '委托人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if((WTRGMJJBM?.startsWith("B") && WTRGMJJBM!="B09") ||  WTRGMJJBM=="E03"){
                return exists("TYKHXX", "KHDM", JKRZJDM)
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1899', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1900', null, null, null, null, 'gfdr', 'CLWTDK', '委托人为非同业单位客户的证件代码应该在非同业单位客户基础信息.客户证件代码中存在', '委托人为非同业单位客户的证件代码应该在非同业单位客户基础信息.客户证件代码中存在', '关联存在校验', '人民银行', 'WTRZJDM', '委托人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(!(!WTRGMJJBM?.startsWith("B") && WTRGMJJBM in ["D01","E03"]) && WTRZJLX?.startsWith("A")){
                return exists("FTYKHX", "KHZJDM", JKRZJDM)
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1900', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1901', null, null, null, null, 'gfdr', 'WTDKFS', '委托人为非同业单位客户的证件代码应该在非同业单位客户基础信息.客户证件代码中存在', '委托人为非同业单位客户的证件代码应该在非同业单位客户基础信息.客户证件代码中存在', '关联存在校验', '人民银行', 'WTRZJDM', '委托人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(!(!WTRGMJJBM?.startsWith("B") && WTRGMJJBM in ["D01","E03"]) && WTRZJLX?.startsWith("A")){
                return exists("FTYKHX", "KHZJDM", JKRZJDM)
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1901', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1902', null, null, null, null, 'gfdr', 'CLWTDK', '委托人为个人客户的证件代码应该在个人客户基础信息.客户证件代码中存在', '委托人为个人客户的证件代码应该在个人客户基础信息.客户证件代码中存在', '关联存在校验', '人民银行', 'WTRZJDM', '委托人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(WTRZJLX?.startsWith("B")){
                return exists("GRKHXX", ["KHZJDM":JKRZJDM, "KHZJLX":JKRZJLX])
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1902', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1903', null, null, null, null, 'gfdr', 'WTDKFS', '委托人为个人客户的证件代码应该在个人客户基础信息.客户证件代码中存在', '委托人为个人客户的证件代码应该在个人客户基础信息.客户证件代码中存在', '关联存在校验', '人民银行', 'WTRZJDM', '委托人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(WTRZJLX?.startsWith("B")){
                return exists("GRKHXX", ["KHZJDM":JKRZJDM, "KHZJLX":JKRZJLX])
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1903', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1904', null, null, null, null, 'gfdr', 'CLWTDK', '借款人为非同业单位客户的证件代码应该在非同业单位客户基础信息.客户证件代码中存在', '借款人为非同业单位客户的证件代码应该在非同业单位客户基础信息.客户证件代码中存在', '关联存在校验', '人民银行', 'JKRZJDM', '借款人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(!(JKRZJLX?.startsWith("A") && !JKRGMJJBM?.startsWith("B") && JKRGMJJBM in ["D01","E03"])){
                return exists("FTYKHX", "KHZJDM", JKRZJDM)
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1904', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1905', null, null, null, null, 'gfdr', 'WTDKFS', '借款人为非同业单位客户的证件代码应该在非同业单位客户基础信息.客户证件代码中存在', '借款人为非同业单位客户的证件代码应该在非同业单位客户基础信息.客户证件代码中存在', '关联存在校验', '人民银行', 'JKRZJDM', '借款人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(!(JKRZJLX?.startsWith("A") && !JKRGMJJBM?.startsWith("B") && JKRGMJJBM in ["D01","E03"])){
                return exists("FTYKHX", "KHZJDM", JKRZJDM)
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1905', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1906', null, null, null, null, 'gfdr', 'CLWTDK', '借款人为个人客户的证件代码应该在个人客户基础信息.客户证件代码中存在', '借款人为个人客户的证件代码应该在个人客户基础信息.客户证件代码中存在', '关联存在校验', '人民银行', 'JKRZJDM', '借款人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(JKRZJLX?.startsWith("B")){
                return exists("GRKHXX", ["KHZJDM":JKRZJDM, "KHZJLX":JKRZJLX])
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1906', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS1907', null, null, null, null, 'gfdr', 'WTDKFS', '借款人为个人客户的证件代码应该在个人客户基础信息.客户证件代码中存在', '借款人为个人客户的证件代码应该在个人客户基础信息.客户证件代码中存在', '关联存在校验', '人民银行', 'JKRZJDM', '借款人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(JKRZJLX?.startsWith("B")){
                return exists("GRKHXX", ["KHZJDM":JKRZJDM, "KHZJLX":JKRZJLX])
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS1907', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2048', null, null, null, null, 'gfdr', 'CLWTDK', '委托人为同业客户的委托存款应该在存量同业存款信息中存在', '委托人为同业客户的委托存款应该在存量同业存款信息中存在', '关联存在校验', '人民银行', 'WTRZJDM', '委托人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if((WTRGMJJBM?.startsWith("B") && WTRGMJJBM!="B09") ||  WTRGMJJBM=="E03"){
                return exists("CLTYCK", "JYDSDM", JKRZJDM)
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2048', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2049', null, null, null, null, 'gfdr', 'CLWTDK', '委托人为非同业单位客户的委托存款应该在存量非同业单位存款信息中存在', '委托人为非同业单位客户的委托存款应该在存量非同业单位存款信息中存在', '关联存在校验', '人民银行', 'WTRZJDM', '委托人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(!(!WTRGMJJBM?.startsWith("B") && WTRGMJJBM in ["D01","E03","E05"]) && WTRZJLX?.startsWith("A")){
                return exists("FTYDWC", "KHZJDM", JKRZJDM)
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2049', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2050', null, null, null, null, 'gfdr', 'CLWTDK', '委托人为个人客户的委托存款应该在存量个人存款信息中存在', '委托人为个人客户的委托存款应该在存量个人存款信息中存在', '关联存在校验', '人民银行', 'WTRZJDM', '委托人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(WTRZJLX?.startsWith("B")){
                return exists("CLGRCK", ["KHZJDM":JKRZJDM, "KHZJLX":JKRZJLX])
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2050', 'R', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2655', null, null, null, null, 'gfdr', 'CLGRDK', '借款人证件类型为B01-身份证或者B08-临时身份证的，借款人证件代码应为15或18位', '借款人证件类型为B01-身份证或者B08-临时身份证的，借款人证件代码应为15或18位', '表内逻辑校验', '人民银行', 'JKRZJDM', '借款人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value) && (JKRZJLX in ["B01","B08"])){
                return length(JKRZJDM) == 15 || length(JKRZJDM) == 18
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2655', 'Q', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2656', null, null, null, null, 'gfdr', 'GRDKFS', '借款人证件类型为B01-身份证或者B08-临时身份证的，借款人证件代码应为15或18位', '借款人证件类型为B01-身份证或者B08-临时身份证的，借款人证件代码应为15或18位', '表内逻辑校验', '人民银行', 'JKRZJDM', '借款人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value) && (JKRZJLX in ["B01","B08"])){
                return length(JKRZJDM) == 15 || length(JKRZJDM) == 18
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2656', 'Q', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2657', null, null, null, null, 'gfdr', 'CLWTDK', '借款人证件类型为B01-身份证或者B08-临时身份证的，借款人证件代码应为15或18位', '借款人证件类型为B01-身份证或者B08-临时身份证的，借款人证件代码应为15或18位', '表内逻辑校验', '人民银行', 'JKRZJDM', '借款人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value) && (JKRZJLX in ["B01","B08"])){
                return length(JKRZJDM) == 15 || length(JKRZJDM) == 18
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2657', 'Q', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2658', null, null, null, null, 'gfdr', 'CLWTDK', '委托人证件类型为B01-身份证或者B08-临时身份证的，委托人证件代码应为15或18位', '委托人证件类型为B01-身份证或者B08-临时身份证的，委托人证件代码应为15或18位', '表内逻辑校验', '人民银行', 'WTRZJDM', '委托人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value) && (WTRZJLX in ["B01","B08"])){
                return length(WTRZJDM) == 15 || length(WTRZJDM) == 18
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2658', 'Q', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2659', null, null, null, null, 'gfdr', 'WTDKFS', '借款人证件类型为B01-身份证或者B08-临时身份证的，借款人证件代码应为15或18位', '借款人证件类型为B01-身份证或者B08-临时身份证的，借款人证件代码应为15或18位', '表内逻辑校验', '人民银行', 'JKRZJDM', '借款人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value) && (JKRZJLX in ["B01","B08"])){
                return length(JKRZJDM) == 15 || length(JKRZJDM) == 18
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2659', 'Q', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2660', null, null, null, null, 'gfdr', 'WTDKFS', '委托人证件类型为B01-身份证或者B08-临时身份证的，委托人证件代码应为15或18位', '委托人证件类型为B01-身份证或者B08-临时身份证的，委托人证件代码应为15或18位', '表内逻辑校验', '人民银行', 'WTRZJDM', '委托人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value) && (WTRZJLX in ["B01","B08"])){
                return length(WTRZJDM) == 15 || length(WTRZJDM) == 18
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2660', 'Q', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2661', null, null, null, null, 'gfdr', 'GRKHXX', '客户证件类型为B01-身份证或者B08-临时身份证的，客户证件代码应为15或18位', '客户证件类型为B01-身份证或者B08-临时身份证的，客户证件代码应为15或18位', '表内逻辑校验', '人民银行', 'KHZJDM', '客户证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value) && (KHZJLX in ["B01","B08"])){
                return length(KHZJDM) == 15 || length(KHZJDM) == 18
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2661', 'Q', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2662', null, null, null, null, 'gfdr', 'CLGRCK', '客户证件类型为B01-身份证或者B08-临时身份证的，客户证件代码应为15或18位', '客户证件类型为B01-身份证或者B08-临时身份证的，客户证件代码应为15或18位', '表内逻辑校验', '人民银行', 'KHZJDM', '客户证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value) && (KHZJLX in ["B01","B08"])){
                return length(KHZJDM) == 15 || length(KHZJDM) == 18
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2662', 'Q', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2663', null, null, null, null, 'gfdr', 'GRCKFS', '客户证件类型为B01-身份证或者B08-临时身份证的，客户证件代码应为15或18位', '客户证件类型为B01-身份证或者B08-临时身份证的，客户证件代码应为15或18位', '表内逻辑校验', '人民银行', 'KHZJDM', '客户证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value) && (KHZJLX in ["B01","B08"])){
                return length(KHZJDM) == 15 || length(KHZJDM) == 18
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2663', 'Q', null, null, null);
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, DATA_HASH, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('JS2664', null, null, null, null, 'gfdr', 'DBHTXX', '担保人证件类型为B01-身份证或者B08-临时身份证的，担保人证件代码应为15或18位', '担保人证件类型为B01-身份证或者B08-临时身份证的，担保人证件代码应为15或18位', '表内逻辑校验', '人民银行', 'DBRZJDM', '担保人证件代码', null, 'Y', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '
            if(isNotEmpty($value) && (DBRZJLX in ["B01","B08"])){
                return length(DBRZJDM) == 15 || length(DBRZJDM) == 18
            }
            return true
            ', null, null, null, null, null, null, null, null, null, null, null, null, 'auto_generator', null, null, null, null, null, null, null, null, 'JS2664', 'Q', null, null, null);
delete from GP_QC_RULE_MAP where RULE_ID in ('JS1708','JS1709','JS1719','JS1720','JS1898','JS1899','JS1900','JS1901','JS1902','JS1903','JS1904','JS1905','JS1906','JS1907','JS2048','JS2049','JS2050','JS2655','JS2656','JS2657','JS2658','JS2659','JS2660','JS2661','JS2662','JS2663','JS2664');
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072075210E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-CLGRCK', 'JS2662', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072075310E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-CLGRDK', 'JS2655', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072075410E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-CLWTDK', 'JS2658', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072075510E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-CLWTDK', 'JS2657', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072075610E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-CLWTDK', 'JS2050', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072075710E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-CLWTDK', 'JS2049', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072075810E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-CLWTDK', 'JS2048', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072075910E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-CLWTDK', 'JS1906', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072075A10E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-CLWTDK', 'JS1904', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072075B10E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-CLWTDK', 'JS1902', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072075C10E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-CLWTDK', 'JS1900', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072075D10E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-CLWTDK', 'JS1898', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072075E10E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-DBHTXX', 'JS2664', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072075F10E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-GRCKFS', 'JS2663', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072076010E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-GRDKFS', 'JS2656', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072076110E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-GRKHXX', 'JS2661', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072076210E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-WTDKFS', 'JS2660', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072076310E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-WTDKFS', 'JS2659', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072076410E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-WTDKFS', 'JS1907', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072076510E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-WTDKFS', 'JS1905', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072076610E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-WTDKFS', 'JS1903', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072076710E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-WTDKFS', 'JS1901', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072076810E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-WTDKFS', 'JS1899', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072076910E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-WTDKFS', 'JS1720', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072076A10E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-WTDKFS', 'JS1719', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072076B10E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-WTDKFS', 'JS1709', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072076C10E4E0531202000AFB69', null, null, null, null, null, null, 'BASIC-WTDKFS', 'JS1708', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072076D10E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00010201', 'JS2664', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072076E10E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00010701', 'JS2655', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072076F10E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00010801', 'JS2656', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072077010E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011001', 'JS2658', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072077110E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011001', 'JS2657', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072077210E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011001', 'JS2050', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072077310E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011001', 'JS2049', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072077410E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011001', 'JS2048', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072077510E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011001', 'JS1906', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072077610E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011001', 'JS1904', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072077710E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011001', 'JS1902', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072077810E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011001', 'JS1900', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072077910E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011001', 'JS1898', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072077A10E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011101', 'JS2660', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072077B10E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011101', 'JS2659', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072077C10E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011101', 'JS1907', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072077D10E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011101', 'JS1905', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072077E10E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011101', 'JS1903', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072077F10E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011101', 'JS1901', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072078010E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011101', 'JS1899', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072078110E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011101', 'JS1720', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072078210E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011101', 'JS1719', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072078310E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011101', 'JS1709', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072078410E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00011101', 'JS1708', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072078510E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00020301', 'JS2661', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072078610E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00040501', 'JS2662', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BA6CC072078710E4E0531202000AFB69', null, null, null, null, null, null, 'UI-gfdr_00040601', 'JS2663', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);


delete from GP_BM_GNO_TOPIC where TOPIC_NAME = 'test';

update GP_BM_ID_FILEDATA set END_COLUMN = null;

update GP_BM_INTER_CONFIG set INTER_COLUMN = 'INTEGER_1' where DATA_ID = 'GPMS_GP_BM_HOLIDAY_1';

update GP_BM_RES_PAGES set PAGE_PATH = '/pages/gfdr/rpt/JGXX/FRZCFX/ftl/GfdrFRZCFX.ftl' where PAGE_ID = 'PAGE@gfdr_00030401';


delete from GP_BM_SYS_PARAM where PARAM_ID in ('FEEDBACK_TEL', 'FEEDBACK_CONTACT', 'FEEDBACK_NAME', 'FEEDBACK_ABBR_NAME', 'VALIDATE_SYNC', 'FILE_GEN_SYNC', 'NEED_FORCE_CHECK');

INSERT INTO GP_BM_SYS_PARAM (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, PARAM_GROUP_ID, PARAM_ID, PARAM_NAME, PARAM_VALUE, REMARKS, CATALOG, LOAD_TYPE, IF_CANMODIFY, PARAM_START_DT, PARAM_END_DT, LAST_UPD_TLR, LAST_UPD_FUNC, LAST_UPD_DATE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('024fc12f51bb412a8dd17b81710d8595', null, null, null, 'GFDR', 'GFDR', 'FEEDBACK_TEL', '反馈文件导出联系人电话', '010-123456', null, '反馈文件配置', 'I', 'Y', null, null, null, null, null, '99', '04', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_BM_SYS_PARAM (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, PARAM_GROUP_ID, PARAM_ID, PARAM_NAME, PARAM_VALUE, REMARKS, CATALOG, LOAD_TYPE, IF_CANMODIFY, PARAM_START_DT, PARAM_END_DT, LAST_UPD_TLR, LAST_UPD_FUNC, LAST_UPD_DATE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('024fcf2f5bb1412a8dd17b81710d8595', null, null, null, 'GFDR', 'GFDR', 'FEEDBACK_CONTACT', '反馈文件导出联系人', '赵某某', null, '反馈文件配置', 'I', 'Y', null, null, null, null, null, '99', '04', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_BM_SYS_PARAM (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, PARAM_GROUP_ID, PARAM_ID, PARAM_NAME, PARAM_VALUE, REMARKS, CATALOG, LOAD_TYPE, IF_CANMODIFY, PARAM_START_DT, PARAM_END_DT, LAST_UPD_TLR, LAST_UPD_FUNC, LAST_UPD_DATE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('024fcf2f5bbb411a8dd17b81710d8595', null, null, null, 'GFDR', 'GFDR', 'FEEDBACK_NAME', '反馈文件导出银行全称', '某某银行股份有限公司', null, '反馈文件配置', 'I', 'Y', null, null, null, null, null, '99', '04', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_BM_SYS_PARAM (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, PARAM_GROUP_ID, PARAM_ID, PARAM_NAME, PARAM_VALUE, REMARKS, CATALOG, LOAD_TYPE, IF_CANMODIFY, PARAM_START_DT, PARAM_END_DT, LAST_UPD_TLR, LAST_UPD_FUNC, LAST_UPD_DATE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('024fcf2f5bbb412a8dd17b81710d8595', null, null, null, 'GFDR', 'GFDR', 'FEEDBACK_ABBR_NAME', '反馈文件导出银行简称', '某某银行', null, '反馈文件配置', 'I', 'Y', null, null, null, null, null, '99', '04', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO GP_BM_SYS_PARAM (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, PARAM_GROUP_ID, PARAM_ID, PARAM_NAME, PARAM_VALUE, REMARKS, CATALOG, LOAD_TYPE, IF_CANMODIFY, PARAM_START_DT, PARAM_END_DT, LAST_UPD_TLR, LAST_UPD_FUNC, LAST_UPD_DATE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('20195a5158104707bbdb950ce9e0f001', '20191225', null, null, 'GFDR', 'GFDR', 'VALIDATE_SYNC', '校验是否以同步的方式调用', 'N', '校验是否同步 Y-是 N-否', '数据校验', 'E', 'Y', null, null, null, null, null, '99', '04', null, null, null, null, null, null, null, null, 'admin', '20171024', null, 'admin', '20171024', null, null, null, null, null, null, null, null, null);
INSERT INTO GP_BM_SYS_PARAM (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, PARAM_GROUP_ID, PARAM_ID, PARAM_NAME, PARAM_VALUE, REMARKS, CATALOG, LOAD_TYPE, IF_CANMODIFY, PARAM_START_DT, PARAM_END_DT, LAST_UPD_TLR, LAST_UPD_FUNC, LAST_UPD_DATE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('20195a5158104707bbdb950ce9e0f002', '20191225', null, null, 'GFDR', 'GFDR', 'FILE_GEN_SYNC', '文件生成是否以同步的方式调用', 'N', '文件生成是否以同步的方式调用 Y-是 N-否', '文件生成', 'E', 'Y', null, null, null, null, null, '99', '04', null, null, null, null, null, null, null, null, 'admin', '20171024', null, 'admin', '20171024', null, null, null, null, null, null, null, null, null);
INSERT INTO GP_BM_SYS_PARAM (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, PARAM_GROUP_ID, PARAM_ID, PARAM_NAME, PARAM_VALUE, REMARKS, CATALOG, LOAD_TYPE, IF_CANMODIFY, PARAM_START_DT, PARAM_END_DT, LAST_UPD_TLR, LAST_UPD_FUNC, LAST_UPD_DATE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('20195a5158104707bbdb950ce9e20001', '20191225', null, null, 'GFDR', 'GFDR', 'NEED_FORCE_CHECK', '是否强制提交的时候进行对生成文件的必要条件进行校验', 'N', '是否强制提交的时候进行对生成文件的必要条件进行校验 Y-是 N-否', '数据校验', 'E', 'Y', null, null, null, null, null, '99', '04', null, null, null, null, null, null, null, null, 'admin', '20171024', null, 'admin', '20171024', null, null, null, null, null, null, null, null, null);

update GP_BM_SYS_PARAM set PARAM_VALUE = '***********' where PARAM_ID = 'SMTP_PASSWORD';





