prompt Importing table GP_BM_EXPORT_FUNCTION...
set feedback off
set define off
insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('74a3ee3cef9c4858b2df1be0b9f54bad', null, null, null, null, null, null, '20170153', '个人证件有效期变更申请查询', null, null, '74a3ee3cef9c4858b2df1be0b9f54bad', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人证件有效期变更申请查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('35e5622f7a48424d837e87186f3ef75e', null, null, null, null, null, null, '20170135', '个人证件整合上报查询', null, null, '35e5622f7a48424d837e87186f3ef75e', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人证件整合上报查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('4cfa259c255848dcb3eea6a878f1e1c8', null, null, null, null, null, null, '20170105', '个人基本上报查询', null, null, '4cfa259c255848dcb3eea6a878f1e1c8', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人基本上报查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('7e527a67971d40029e96fb35acd07c6a', null, null, null, null, null, null, '20170125', '个人证件有效期上报查询', null, null, '7e527a67971d40029e96fb35acd07c6a', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人证件有效期上报查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('daf63a2a2179421988d20479a33d31a3', null, null, null, null, null, null, '20170143', '个人基本信息变更申请查询', null, null, 'daf63a2a2179421988d20479a33d31a3', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人基本信息变更申请查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('edcdc78bcc954301a980557124d3ff1f', null, null, null, null, null, null, '20170165', '个人基本信息上报变更处理查询', null, null, 'edcdc78bcc954301a980557124d3ff1f', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人基本信息上报变更处理查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('95314f80c49d4b1986ac65a63614085f', null, null, null, null, null, null, '20170175', '个人证件有效期信息上报变更处理查询', null, null, '95314f80c49d4b1986ac65a63614085f', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人证件有效期信息上报变更处理查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('21fb2bce5d1e41da96cd3f3cf9f1d71a', null, null, null, null, null, null, '20170115', '家族关系上报查询', null, null, '21fb2bce5d1e41da96cd3f3cf9f1d71a', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_家族关系上报查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('4039c4e78c204868bf0bd9c5d19c2548', null, null, null, null, null, null, '2019020105', '个人借贷上报查询', null, null, '4039c4e78c204868bf0bd9c5d19c2548', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人借贷上报查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('90543391185e448eb1223c27c2cd2e94', null, null, null, null, null, null, '2019020205', '个人借贷标识变更上报查询', null, null, '90543391185e448eb1223c27c2cd2e94', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人借贷标识变更上报查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('baf66604e59b4be08bbaa2b88f9bebd8', null, null, null, null, null, null, '2019020303', '个人借贷信息变更申请查询', null, null, 'baf66604e59b4be08bbaa2b88f9bebd8', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人借贷信息变更申请查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('55fc2ecd02494de29e82ae7e32f8af99', null, null, null, null, null, null, '2019020405', '个人借贷信息上报变更处理查询', null, null, '55fc2ecd02494de29e82ae7e32f8af99', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人借贷信息上报变更处理查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('3fbc661983764dc4a139ba8e8c76f2e8', null, null, null, null, null, null, '2019020505', '个人借贷账户特殊事件说明上报记录查询', null, null, '3fbc661983764dc4a139ba8e8c76f2e8', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人借贷账户特殊事件说明上报.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('16541565d3574f5d8cd8bf2087c1f0b6', null, null, null, null, null, null, '29001105', '个人担保标识变更上报记录查询', null, null, '16541565d3574f5d8cd8bf2087c1f0b6', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '	ExcelTemplate_个人担保标识变更上报记录查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('a0b6c47aeca4436490de0ba6f22ee655', null, null, null, null, null, null, '29001203', '个人担保信息变更申请查询', null, null, 'a0b6c47aeca4436490de0ba6f22ee655', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '	ExcelTemplate_个人担保信息变更申请查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('e79e10062227447994f6de6829ea0388', null, null, null, null, null, null, '29001305', '个人担保信息上报变更处理查询', null, null, 'e79e10062227447994f6de6829ea0388', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人担保信息上报变更处理查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('b75d4805054242458fc0e9818a28ad75', null, null, null, null, null, null, '290005', '个人担保上报查询', null, null, 'b75d4805054242458fc0e9818a28ad75', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人担保上报查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('6773241d170b463dbd0b1ddcba6a6fa8', null, null, null, null, null, null, '280005', '个人授信上报查询', null, null, '6773241d170b463dbd0b1ddcba6a6fa8', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人授信上报查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('bebe9d7d9ffc45aebcc84c4f275439a2', null, null, null, null, null, null, '280015', '个人授信标识变更上报记录查询', null, null, 'bebe9d7d9ffc45aebcc84c4f275439a2', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人授信标识变更上报记录查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('e4b28ac4bce84742835633aef3649be6', null, null, null, null, null, null, '280023', '个人授信信息变更申请查询', null, null, 'e4b28ac4bce84742835633aef3649be6', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人授信信息变更申清查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('84ba62cbba504ee2ae929cb622b4074e', null, null, null, null, null, null, '280035', '个人授信信息上报变更处理查询', null, null, '84ba62cbba504ee2ae929cb622b4074e', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_个人授信信息上报变更处理查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('d48a64d572e149b18f964ac63b8708d5', null, null, null, null, null, null, '28010303', '抵(质)押信息变更申请查询', null, null, 'd48a64d572e149b18f964ac63b8708d5', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '	ExcelTemplate_抵(质)押信息变更申请查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('ea09d71cfaa0416bad99d9bf3655c783', null, null, null, null, null, null, '28010105', '抵(质)押物上报查询', null, null, 'ea09d71cfaa0416bad99d9bf3655c783', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '	ExcelTemplate_抵(质)押物上报查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('9f85cd21f0124391a5331c8fe9b33410', null, null, null, null, null, null, '28010405', '抵(质)押信息上报变更处理查询', null, null, '9f85cd21f0124391a5331c8fe9b33410', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '	ExcelTemplate_抵(质)押信息上报变更处理查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('d7056b004d7a499e893b9041d1702718', null, null, null, null, null, null, '28010205', '抵(质)押合同标识变更上报数据查询', null, null, 'd7056b004d7a499e893b9041d1702718', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '	ExcelTemplate_抵(质)押合同标识变更上报数据查询.xlsx', 'XLS', 'onlyExport');

prompt Done.
