CREATE TABLE CCRS_PM_DKFSEKZ(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE CHAR(8),
    JRJGBM CHAR(14),
    DKJJBM VARCHAR2(105),
    KHZJLX CHAR(2),
    WJKRZCDBM CHAR(12),
    XDHTBH VARCHAR2(300),
    CPXX VARCHAR2(10),
    DKYT VARCHAR2(1500),
    FFFS CHAR(2),
    SXBS CHAR(2),
    RMYHDKZXJCBS CHAR(50),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_DKFSEKZ IS '贷款发生额扩展报文';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DKJJBM IS '贷款借据编码';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.KHZJLX IS '客户证件类型';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.WJKRZCDBM IS '12位借款人注册地编码';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.XDHTBH IS '信贷合同编号';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.CPXX IS '产品细项';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DKYT IS '贷款用途';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.FFFS IS '发放方式';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.SXBS IS '属性标识';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.RMYHDKZXJCBS IS '人民银行贷款专项监测标识';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_DKFSEKZ.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_DKFSEKZ ON CCRS_PM_DKFSEKZ(DATA_RPT_DATE,SJRQ_DATE,XDHTBH);
