CREATE TABLE CCRS_PM_ZDKSYQK(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE CHAR(8),
    JRJGBM CHAR(14),
    DKJJBM VARCHAR2(105),
    ZDKLX CHAR(2),
    WBZXFS CHAR(2),
    DKHXXX CHAR(2),
    DDPKRKS NUMBER(8),
    ZDKHTBH VARCHAR2(300),
    ZDKFFMS CHAR(2),
    DDJDLKPKHFS CHAR(2),
    DDFPLYLX CHAR(2),
    RMYHZDKZXJCBS CHAR(50),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_ZDKSYQK IS '再贷款使用情况报文';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DKJJBM IS '贷款借据编码';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.ZDKLX IS '再贷款类型';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.WBZXFS IS '外部增信方式';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DKHXXX IS '贷款划型细项';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DDPKRKS IS '带动贫困人口数';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.ZDKHTBH IS '再贷款合同编号';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.ZDKFFMS IS '再贷款发放模式';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DDJDLKPKHFS IS '带动建档立卡贫困户方式';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DDFPLYLX IS '定点扶贫领域类型';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.RMYHZDKZXJCBS IS '人民银行再贷款专项监测标识';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_ZDKSYQK.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_ZDKSYQK ON CCRS_PM_ZDKSYQK(DATA_RPT_DATE,SJRQ_DATE,ZDKHTBH);
