CREATE TABLE CCRS_PM_XYZKL(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE CHAR(8),
    JRJGBM CHAR(14),
    XYZBM VARCHAR2(50),
    SXHTBH VARCHAR2(300),
    KZSQRMC VARCHAR2(300),
    KZSQRZJLX CHAR(2),
    KZSQRDM VARCHAR2(50),
    KZSQRJJCF VARCHAR2(5),
    BZ CHAR(3),
    XYZJE_AMT NUMBER,
    XYZKZRQ_DATE CHAR(8),
    XYZDQRQ_DATE CHAR(8),
    XYZSKRMC VARCHAR2(300),
    XYZBZJBZ CHAR(3),
    XYZBZJJE_AMT NUMBER,
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_XYZKL IS '信用证开立报文';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_XYZKL.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_XYZKL.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_XYZKL.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_XYZKL.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_XYZKL.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_XYZKL.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_XYZKL.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_XYZKL.XYZBM IS '信用证编码';
COMMENT ON COLUMN CCRS_PM_XYZKL.SXHTBH IS '授信合同编号';
COMMENT ON COLUMN CCRS_PM_XYZKL.KZSQRMC IS '开证申请人名称';
COMMENT ON COLUMN CCRS_PM_XYZKL.KZSQRZJLX IS '开证申请人证件类型';
COMMENT ON COLUMN CCRS_PM_XYZKL.KZSQRDM IS '开证申请人代码';
COMMENT ON COLUMN CCRS_PM_XYZKL.KZSQRJJCF IS '开证申请人经济成分';
COMMENT ON COLUMN CCRS_PM_XYZKL.BZ IS '币种';
COMMENT ON COLUMN CCRS_PM_XYZKL.XYZJE_AMT IS '信用证金额';
COMMENT ON COLUMN CCRS_PM_XYZKL.XYZKZRQ_DATE IS '信用证开证日期';
COMMENT ON COLUMN CCRS_PM_XYZKL.XYZDQRQ_DATE IS '信用证到期日期';
COMMENT ON COLUMN CCRS_PM_XYZKL.XYZSKRMC IS '信用证收款人名称';
COMMENT ON COLUMN CCRS_PM_XYZKL.XYZBZJBZ IS '信用证保证金币种';
COMMENT ON COLUMN CCRS_PM_XYZKL.XYZBZJJE_AMT IS '信用证保证金金额';
COMMENT ON COLUMN CCRS_PM_XYZKL.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_XYZKL.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_XYZKL.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_XYZKL.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_XYZKL.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_XYZKL.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_XYZKL.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_XYZKL.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_XYZKL.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_XYZKL.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_XYZKL.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_XYZKL ON CCRS_PM_XYZKL(DATA_RPT_DATE,SJRQ_DATE,XYZBM);
