CREATE TABLE CCRS_PM_TXFSE(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE CHAR(8),
    JRJGBM CHAR(14),
    TXQYZJLX CHAR(2),
    TXQYDM VARCHAR2(50),
    TXQYMC VARCHAR2(300),
    DQXZQHDMTXQYZCSZD CHAR(12),
    TXQYGM CHAR(4),
    TXQYHYFL CHAR(1),
    TXQYJJCF VARCHAR2(5),
    PJBM VARCHAR2(50),
    PJLX CHAR(2),
    PJJZ CHAR(2),
    TXLX VARCHAR2(6),
    TRTCBS CHAR(2),
    CPRQ_DATE CHAR(8),
    PJJE_AMT NUMBER,
    PJDQRQ_DATE CHAR(8),
    KPQYMC VARCHAR2(300),
    KPQYZJLX CHAR(2),
    KPQYDM VARCHAR2(50),
    RMYHPJZXJCBS CHAR(50),
    FKHHH CHAR(12),
    FKHMC VARCHAR2(300),
    SKRMC VARCHAR2(300),
    TXYWFSRQ_DATE CHAR(8),
    TXLL NUMBER,
    BZ CHAR(3),
    BSZRCS NUMBER(8),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_TXFSE IS '贴现发生额报文';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_TXFSE.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_TXFSE.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_TXFSE.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_TXFSE.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_TXFSE.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_TXFSE.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_TXFSE.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_TXFSE.TXQYZJLX IS '贴现企业证件类型';
COMMENT ON COLUMN CCRS_PM_TXFSE.TXQYDM IS '贴现企业代码';
COMMENT ON COLUMN CCRS_PM_TXFSE.TXQYMC IS '贴现企业名称';
COMMENT ON COLUMN CCRS_PM_TXFSE.DQXZQHDMTXQYZCSZD IS '地区行政区划代码（贴现企业注册所在地）';
COMMENT ON COLUMN CCRS_PM_TXFSE.TXQYGM IS '贴现企业规模';
COMMENT ON COLUMN CCRS_PM_TXFSE.TXQYHYFL IS '贴现企业行业分类';
COMMENT ON COLUMN CCRS_PM_TXFSE.TXQYJJCF IS '贴现企业经济成分';
COMMENT ON COLUMN CCRS_PM_TXFSE.PJBM IS '票据编码';
COMMENT ON COLUMN CCRS_PM_TXFSE.PJLX IS '票据类型';
COMMENT ON COLUMN CCRS_PM_TXFSE.PJJZ IS '票据介质';
COMMENT ON COLUMN CCRS_PM_TXFSE.TXLX IS '贴现类型';
COMMENT ON COLUMN CCRS_PM_TXFSE.TRTCBS IS '贴入/贴出标识';
COMMENT ON COLUMN CCRS_PM_TXFSE.CPRQ_DATE IS '出票日期';
COMMENT ON COLUMN CCRS_PM_TXFSE.PJJE_AMT IS '票据金额';
COMMENT ON COLUMN CCRS_PM_TXFSE.PJDQRQ_DATE IS '票据到期日期';
COMMENT ON COLUMN CCRS_PM_TXFSE.KPQYMC IS '开票企业名称';
COMMENT ON COLUMN CCRS_PM_TXFSE.KPQYZJLX IS '开票企业证件类型';
COMMENT ON COLUMN CCRS_PM_TXFSE.KPQYDM IS '开票企业代码';
COMMENT ON COLUMN CCRS_PM_TXFSE.RMYHPJZXJCBS IS '人民银行票据专项监测标识';
COMMENT ON COLUMN CCRS_PM_TXFSE.FKHHH IS '付款行行号';
COMMENT ON COLUMN CCRS_PM_TXFSE.FKHMC IS '付款行名称';
COMMENT ON COLUMN CCRS_PM_TXFSE.SKRMC IS '收款人名称';
COMMENT ON COLUMN CCRS_PM_TXFSE.TXYWFSRQ_DATE IS '贴现业务发生日期';
COMMENT ON COLUMN CCRS_PM_TXFSE.TXLL IS '贴现利率';
COMMENT ON COLUMN CCRS_PM_TXFSE.BZ IS '币种';
COMMENT ON COLUMN CCRS_PM_TXFSE.BSZRCS IS '背书转让次数';
COMMENT ON COLUMN CCRS_PM_TXFSE.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_TXFSE.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_TXFSE.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_TXFSE.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_TXFSE.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_TXFSE.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_TXFSE.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_TXFSE.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_TXFSE.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_TXFSE.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_TXFSE.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_TXFSE ON CCRS_PM_TXFSE(DATA_RPT_DATE,SJRQ_DATE,PJBM);
