CREATE TABLE CCRS_PM_TYCDFSE(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE CHAR(8),
    JRJGBM CHAR(14),
    JYDSMC VARCHAR2(300),
    CDXYDM VARCHAR2(150),
    CDMC VARCHAR2(300),
    CDXYQSRQ_DATE CHAR(8),
    CDXYDQRQ_DATE CHAR(8),
    CDSJDQRQ_DATE CHAR(8),
    BZ CHAR(3),
    CDFXGM_AMT NUMBER,
    LLSFGD CHAR(4),
    LLSP NUMBER,
    TYCDQXLX CHAR(2),
    JZLLZL CHAR(2),
    FXPL CHAR(2),
    CDFSLX CHAR(2),
    TYCDDFBJ_AMT NUMBER,
    TYCDDFLX_AMT NUMBER,
    CDFSJE_AMT NUMBER,
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_TYCDFSE IS '同业存单发生额报文';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.JYDSMC IS '交易对手名称';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.CDXYDM IS '存单协议代码';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.CDMC IS '存单名称';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.CDXYQSRQ_DATE IS '存单协议起始日期';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.CDXYDQRQ_DATE IS '存单协议到期日期';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.CDSJDQRQ_DATE IS '存单实际到期日期';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.BZ IS '币种';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.CDFXGM_AMT IS '存单发行规模';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.LLSFGD IS '利率是否固定';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.LLSP IS '利率水平';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.TYCDQXLX IS '同业存单期限类型';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.JZLLZL IS '基准利率种类';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.FXPL IS '付息频率';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.CDFSLX IS '存单发生类型';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.TYCDDFBJ_AMT IS '同业存单兑付本金';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.TYCDDFLX_AMT IS '同业存单兑付利息';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.CDFSJE_AMT IS '存单发生金额';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_TYCDFSE.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_TYCDFSE ON CCRS_PM_TYCDFSE(DATA_RPT_DATE,SJRQ_DATE,CDXYDM);
