CREATE TABLE CCRS_PM_WTDKYE(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE CHAR(8),
    JRJGBM CHAR(14),
    XDHTBH VARCHAR2(300),
    KHLX CHAR(1),
    KHZJLX CHAR(2),
    JKRDM VARCHAR2(50),
    WTRZJLX CHAR(2),
    WTRDM VARCHAR2(50),
    DKZTHYLB CHAR(1),
    WJKRZCDBM CHAR(12),
    QYCZRJJCF VARCHAR2(5),
    QYGM CHAR(4),
    DKJJBM VARCHAR2(105),
    CPXX VARCHAR2(10),
    DKSJTX CHAR(4),
    DKYT VARCHAR2(1500),
    DKFFRQ_DATE CHAR(8),
    FFFS CHAR(2),
    WTDKSXFJE_AMT NUMBER,
    DKDQRQ_DATE CHAR(8),
    ZQDQRQ_DATE CHAR(8),
    BZ CHAR(3),
    DKYE_AMT NUMBER,
    LLSFGD CHAR(4),
    LLSP NUMBER,
    DKDBFS VARCHAR2(3),
    DKZL CHAR(4),
    DKZS CHAR(4),
    WTDKJJZE_AMT NUMBER,
    SXBS CHAR(2),
    RMYHDKZXJCBS CHAR(50),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_WTDKYE IS '委托贷款余额报文';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_WTDKYE.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_WTDKYE.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_WTDKYE.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_WTDKYE.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_WTDKYE.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_WTDKYE.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_WTDKYE.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_WTDKYE.XDHTBH IS '信贷合同编号';
COMMENT ON COLUMN CCRS_PM_WTDKYE.KHLX IS '客户类型';
COMMENT ON COLUMN CCRS_PM_WTDKYE.KHZJLX IS '客户证件类型';
COMMENT ON COLUMN CCRS_PM_WTDKYE.JKRDM IS '借款人代码';
COMMENT ON COLUMN CCRS_PM_WTDKYE.WTRZJLX IS '委托人证件类型';
COMMENT ON COLUMN CCRS_PM_WTDKYE.WTRDM IS '委托人代码';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DKZTHYLB IS '贷款主体行业类别';
COMMENT ON COLUMN CCRS_PM_WTDKYE.WJKRZCDBM IS '12位借款人注册地编码';
COMMENT ON COLUMN CCRS_PM_WTDKYE.QYCZRJJCF IS '企业出资人经济成分';
COMMENT ON COLUMN CCRS_PM_WTDKYE.QYGM IS '企业规模';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DKJJBM IS '贷款借据编码';
COMMENT ON COLUMN CCRS_PM_WTDKYE.CPXX IS '产品细项';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DKSJTX IS '贷款实际投向';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DKYT IS '贷款用途';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DKFFRQ_DATE IS '贷款发放日期';
COMMENT ON COLUMN CCRS_PM_WTDKYE.FFFS IS '发放方式';
COMMENT ON COLUMN CCRS_PM_WTDKYE.WTDKSXFJE_AMT IS '委托贷款手续费金额';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DKDQRQ_DATE IS '贷款到期日期';
COMMENT ON COLUMN CCRS_PM_WTDKYE.ZQDQRQ_DATE IS '展期到期日期';
COMMENT ON COLUMN CCRS_PM_WTDKYE.BZ IS '币种';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DKYE_AMT IS '贷款余额';
COMMENT ON COLUMN CCRS_PM_WTDKYE.LLSFGD IS '利率是否固定';
COMMENT ON COLUMN CCRS_PM_WTDKYE.LLSP IS '利率水平';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DKDBFS IS '贷款担保方式';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DKZL IS '贷款质量';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DKZS IS '贷款状态';
COMMENT ON COLUMN CCRS_PM_WTDKYE.WTDKJJZE_AMT IS '委托贷款基金总额';
COMMENT ON COLUMN CCRS_PM_WTDKYE.SXBS IS '属性标识';
COMMENT ON COLUMN CCRS_PM_WTDKYE.RMYHDKZXJCBS IS '人民银行贷款专项监测标识';
COMMENT ON COLUMN CCRS_PM_WTDKYE.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_WTDKYE.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_WTDKYE.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_WTDKYE.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_WTDKYE.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_WTDKYE.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_WTDKYE.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_WTDKYE.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_WTDKYE.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_WTDKYE.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_WTDKYE.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_WTDKYE ON CCRS_PM_WTDKYE(DATA_RPT_DATE,SJRQ_DATE,XDHTBH);
