CREATE TABLE CCRS_PM_ZXZQZCTDLYFZQK(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE CHAR(8),
    JRJGBM CHAR(14),
    DKJJBM VARCHAR2(105),
    ZJLY CHAR(2),
    ZXZQDKYT VARCHAR2(4),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_ZXZQZCTDLYFZQK IS '专项债券支持特定领域发展情况报文';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DKJJBM IS '贷款借据编码';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.ZJLY IS '资金来源';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.ZXZQDKYT IS '专项债券贷款用途';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_ZXZQZCTDLYFZQK.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_ZXZQZCTDLYFZQK ON CCRS_PM_ZXZQZCTDLYFZQK(DATA_RPT_DATE,SJRQ_DATE,DKJJBM);
