CREATE TABLE CCRS_PM_DBWXX(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE CHAR(8),
    JRJGBM CHAR(14),
    DBHTBH VARCHAR2(120),
    DKDBFS VARCHAR2(3),
    YPBH VARCHAR2(300),
    YPMC VARCHAR2(300),
    YPLX VARCHAR2(4),
    DBWJZ_AMT NUMBER,
    BZ CHAR(3),
    DZYL NUMBER,
    BZRMC VARCHAR2(300),
    BZRZJLX CHAR(2),
    BZRZJHM VARCHAR2(50),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_DBWXX IS '担保物信息报文';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_DBWXX.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_DBWXX.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_DBWXX.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_DBWXX.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_DBWXX.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_DBWXX.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_DBWXX.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_DBWXX.DBHTBH IS '担保合同编号';
COMMENT ON COLUMN CCRS_PM_DBWXX.DKDBFS IS '贷款担保方式';
COMMENT ON COLUMN CCRS_PM_DBWXX.YPBH IS '押品编号';
COMMENT ON COLUMN CCRS_PM_DBWXX.YPMC IS '押品名称';
COMMENT ON COLUMN CCRS_PM_DBWXX.YPLX IS '押品类型';
COMMENT ON COLUMN CCRS_PM_DBWXX.DBWJZ_AMT IS '担保物价值';
COMMENT ON COLUMN CCRS_PM_DBWXX.BZ IS '币种';
COMMENT ON COLUMN CCRS_PM_DBWXX.DZYL IS '抵质押率';
COMMENT ON COLUMN CCRS_PM_DBWXX.BZRMC IS '保证人名称';
COMMENT ON COLUMN CCRS_PM_DBWXX.BZRZJLX IS '保证人证件类型';
COMMENT ON COLUMN CCRS_PM_DBWXX.BZRZJHM IS '保证人证件号码';
COMMENT ON COLUMN CCRS_PM_DBWXX.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_DBWXX.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_DBWXX.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_DBWXX.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_DBWXX.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_DBWXX.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_DBWXX.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_DBWXX.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_DBWXX.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_DBWXX.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_DBWXX.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_DBWXX ON CCRS_PM_DBWXX(DATA_RPT_DATE,SJRQ_DATE,DBHTBH,YPBH,BZRZJLX,BZRZJHM);
