CREATE TABLE CCRS_PM_ZQCX(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE CHAR(8),
    JRJGBM CHAR(14),
    SFZCXS CHAR(1),
    ZQCXJE_AMT NUMBER,
    ZQMC VARCHAR2(300),
    ZQJC VARCHAR2(300),
    ZQLX VARCHAR2(4),
    ZQDM VARCHAR2(20),
    ZQFXBZ CHAR(3),
    ZQFXJE_AMT NUMBER,
    ZQFXRZJLX CHAR(2),
    ZQFXRDM VARCHAR2(50),
    DQXZQHDMZQFXRZCSZD CHAR(12),
    ZQFXRKGLX VARCHAR2(5),
    ZQFXRZTHYLB CHAR(1),
    ZQFXSZTPJ CHAR(2),
    ZXPJ CHAR(2),
    ZQFXRQ_DATE CHAR(8),
    ZQDQRQ_DATE CHAR(8),
    ZQQXRQ_DATE CHAR(8),
    ZQFXLL NUMBER,
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_ZQCX IS '债券承销报文';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_ZQCX.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_ZQCX.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_ZQCX.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_ZQCX.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_ZQCX.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_ZQCX.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_ZQCX.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_ZQCX.SFZCXS IS '是否主承销商';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZQCXJE_AMT IS '债券承销金额';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZQMC IS '债券名称';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZQJC IS '债券简称';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZQLX IS '债券类型';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZQDM IS '债券代码';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZQFXBZ IS '债券发行币种';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZQFXJE_AMT IS '债券发行金额';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZQFXRZJLX IS '债券发行人证件类型';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZQFXRDM IS '债券发行人代码';
COMMENT ON COLUMN CCRS_PM_ZQCX.DQXZQHDMZQFXRZCSZD IS '地区行政区划代码（债券发行人注册所在地）';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZQFXRKGLX IS '债券发行人控股类型';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZQFXRZTHYLB IS '债券发行人主体行业类别';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZQFXSZTPJ IS '债券发行时主体评级';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZXPJ IS '债项评级';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZQFXRQ_DATE IS '债券发行日期';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZQDQRQ_DATE IS '债券到期日期';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZQQXRQ_DATE IS '债券起息日期';
COMMENT ON COLUMN CCRS_PM_ZQCX.ZQFXLL IS '债券发行利率';
COMMENT ON COLUMN CCRS_PM_ZQCX.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_ZQCX.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_ZQCX.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_ZQCX.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_ZQCX.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_ZQCX.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_ZQCX.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_ZQCX.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_ZQCX.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_ZQCX.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_ZQCX.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_ZQCX ON CCRS_PM_ZQCX(DATA_RPT_DATE,SJRQ_DATE,ZQDM);
