CREATE TABLE CCRS_PM_WTDKFSE(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE CHAR(8),
    JRJGBM CHAR(14),
    XDHTBH VARCHAR2(300),
    KHLX CHAR(1),
    KHZJLX CHAR(2),
    JKRDM VARCHAR2(50),
    DKZTHYLB CHAR(1),
    WJKRZCDBM CHAR(12),
    WTRZJLX CHAR(2),
    WTRDM VARCHAR2(50),
    QYCZRJJCF VARCHAR2(5),
    QYGM CHAR(4),
    DKJJBM VARCHAR2(105),
    CPXX VARCHAR2(10),
    DKSJTX CHAR(4),
    DKYT VARCHAR2(1500),
    DKFFRQ_DATE CHAR(8),
    FFFS CHAR(2),
    WTDKSXFJE_AMT NUMBER,
    DKDQRQ_DATE CHAR(8),
    DKSJZZRQ_DATE CHAR(8),
    BZ CHAR(3),
    DKFSJE_AMT NUMBER,
    LLSFGD CHAR(4),
    LLSP NUMBER,
    DKDBFS VARCHAR2(3),
    DKZS CHAR(4),
    FFSHBS CHAR(1),
    SXBS CHAR(2),
    RMYHDKZXJCBS CHAR(50),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_WTDKFSE IS '委托贷款发生额报文';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.XDHTBH IS '信贷合同编号';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.KHLX IS '客户类型';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.KHZJLX IS '客户证件类型';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.JKRDM IS '借款人代码';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DKZTHYLB IS '贷款主体行业类别';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.WJKRZCDBM IS '12位借款人注册地编码';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.WTRZJLX IS '委托人证件类型';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.WTRDM IS '委托人代码';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.QYCZRJJCF IS '企业出资人经济成分';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.QYGM IS '企业规模';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DKJJBM IS '贷款借据编码';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.CPXX IS '产品细项';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DKSJTX IS '贷款实际投向';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DKYT IS '贷款用途';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DKFFRQ_DATE IS '贷款发放日期';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.FFFS IS '发放方式';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.WTDKSXFJE_AMT IS '委托贷款手续费金额';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DKDQRQ_DATE IS '贷款到期日期';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DKSJZZRQ_DATE IS '贷款实际终止日期';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.BZ IS '币种';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DKFSJE_AMT IS '贷款发生金额';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.LLSFGD IS '利率是否固定';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.LLSP IS '利率水平';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DKDBFS IS '贷款担保方式';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DKZS IS '贷款状态';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.FFSHBS IS '发放/收回标识';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.SXBS IS '属性标识';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.RMYHDKZXJCBS IS '人民银行贷款专项监测标识';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_WTDKFSE.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_WTDKFSE ON CCRS_PM_WTDKFSE(DATA_RPT_DATE,SJRQ_DATE,XDHTBH);
