CREATE TABLE CCRS_PM_DWKH(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE CHAR(8),
    JRJGBM CHAR(14),
    JRJGMC VARCHAR2(300),
    KHBH VARCHAR2(300),
    KHMC VARCHAR2(300),
    DWKHLX VARCHAR2(2),
    TYSHXYDM CHAR(18),
    DWZJYXQX_DATE CHAR(8),
    ZZJGDM CHAR(10),
    YYZZZCH VARCHAR2(18),
    QSZJLXHM VARCHAR2(100),
    NSRSBH VARCHAR2(20),
    TSJGDM VARCHAR2(300),
    HY CHAR(1),
    QYGM CHAR(4),
    DWYWFW VARCHAR2(3000),
    DWLXR VARCHAR2(300),
    DWLXDH VARCHAR2(20),
    DWDZYX VARCHAR2(300),
    DWZCDZ VARCHAR2(300),
    DQXZQHDMDWZCD CHAR(12),
    GJ CHAR(3),
    ZCZBBZ CHAR(3),
    ZCZB_AMT NUMBER,
    DWCLRQ_DATE CHAR(8),
    FRDBMC VARCHAR2(300),
    FRDBZJLX CHAR(2),
    FRDBZJYXQX_DATE CHAR(8),
    FRDBZJHM VARCHAR2(50),
    QYCZRJJCF VARCHAR2(5),
    SYSYRMC VARCHAR2(300),
    SYSYRZJLX CHAR(2),
    SYSYRZJYXQ_DATE CHAR(8),
    SYSYRZJHM VARCHAR2(50),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_DWKH IS '单位客户报文';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_DWKH.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_DWKH.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_DWKH.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_DWKH.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_DWKH.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_DWKH.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_DWKH.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_DWKH.JRJGMC IS '金融机构名称';
COMMENT ON COLUMN CCRS_PM_DWKH.KHBH IS '客户编号';
COMMENT ON COLUMN CCRS_PM_DWKH.KHMC IS '客户名称';
COMMENT ON COLUMN CCRS_PM_DWKH.DWKHLX IS '单位客户类型';
COMMENT ON COLUMN CCRS_PM_DWKH.TYSHXYDM IS '统一社会信用代码';
COMMENT ON COLUMN CCRS_PM_DWKH.DWZJYXQX_DATE IS '单位证件有效期限';
COMMENT ON COLUMN CCRS_PM_DWKH.ZZJGDM IS '组织机构代码';
COMMENT ON COLUMN CCRS_PM_DWKH.YYZZZCH IS '营业执照注册号';
COMMENT ON COLUMN CCRS_PM_DWKH.QSZJLXHM IS '其他证件类型号码';
COMMENT ON COLUMN CCRS_PM_DWKH.NSRSBH IS '纳税人识别号';
COMMENT ON COLUMN CCRS_PM_DWKH.TSJGDM IS '特殊机构代码';
COMMENT ON COLUMN CCRS_PM_DWKH.HY IS '行业';
COMMENT ON COLUMN CCRS_PM_DWKH.QYGM IS '企业规模';
COMMENT ON COLUMN CCRS_PM_DWKH.DWYWFW IS '单位业务范围';
COMMENT ON COLUMN CCRS_PM_DWKH.DWLXR IS '单位联系人';
COMMENT ON COLUMN CCRS_PM_DWKH.DWLXDH IS '单位联系电话';
COMMENT ON COLUMN CCRS_PM_DWKH.DWDZYX IS '单位电子邮箱';
COMMENT ON COLUMN CCRS_PM_DWKH.DWZCDZ IS '单位注册地址';
COMMENT ON COLUMN CCRS_PM_DWKH.DQXZQHDMDWZCD IS '地区行政区划代码（单位注册地）';
COMMENT ON COLUMN CCRS_PM_DWKH.GJ IS '国家';
COMMENT ON COLUMN CCRS_PM_DWKH.ZCZBBZ IS '注册资本币种';
COMMENT ON COLUMN CCRS_PM_DWKH.ZCZB_AMT IS '注册资本';
COMMENT ON COLUMN CCRS_PM_DWKH.DWCLRQ_DATE IS '单位成立日期';
COMMENT ON COLUMN CCRS_PM_DWKH.FRDBMC IS '法人代表名称';
COMMENT ON COLUMN CCRS_PM_DWKH.FRDBZJLX IS '法人代表证件类型';
COMMENT ON COLUMN CCRS_PM_DWKH.FRDBZJYXQX_DATE IS '法人代表证件有效期限';
COMMENT ON COLUMN CCRS_PM_DWKH.FRDBZJHM IS '法人代表证件号码';
COMMENT ON COLUMN CCRS_PM_DWKH.QYCZRJJCF IS '企业出资人经济成分';
COMMENT ON COLUMN CCRS_PM_DWKH.SYSYRMC IS '受益所有人名称';
COMMENT ON COLUMN CCRS_PM_DWKH.SYSYRZJLX IS '受益所有人证件类型';
COMMENT ON COLUMN CCRS_PM_DWKH.SYSYRZJYXQ_DATE IS '受益所有人证件有效期';
COMMENT ON COLUMN CCRS_PM_DWKH.SYSYRZJHM IS '受益所有人证件号码';
COMMENT ON COLUMN CCRS_PM_DWKH.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_DWKH.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_DWKH.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_DWKH.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_DWKH.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_DWKH.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_DWKH.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_DWKH.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_DWKH.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_DWKH.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_DWKH.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_DWKH ON CCRS_PM_DWKH(DATA_RPT_DATE,SJRQ_DATE,KHBH);
