CREATE TABLE CCRS_PM_XDHT(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE CHAR(8),
    JRJGBM CHAR(14),
    XDHTBH VARCHAR2(300),
    KHBH VARCHAR2(300),
    KHMC VARCHAR2(300),
    KHLX CHAR(1),
    KHZJLX CHAR(2),
    KHZJHM VARCHAR2(50),
    SXHTBH VARCHAR2(300),
    CPXX VARCHAR2(10),
    BZ CHAR(3),
    DKHTJE_AMT NUMBER,
    DKSJTX CHAR(4),
    DKYT VARCHAR2(1500),
    HTQSRQ_DATE CHAR(8),
    HTDQRQ_DATE CHAR(8),
    HKFS CHAR(2),
    GRZFAJDKLX CHAR(2),
    GRZFAJDKGFZJ_AMT NUMBER,
    SFZFDBJJDB CHAR(1),
    RMYHDKZXJCBS CHAR(50),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_XDHT IS '信贷合同报文';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_XDHT.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_XDHT.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_XDHT.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_XDHT.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_XDHT.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_XDHT.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_XDHT.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_XDHT.XDHTBH IS '信贷合同编号';
COMMENT ON COLUMN CCRS_PM_XDHT.KHBH IS '客户编号';
COMMENT ON COLUMN CCRS_PM_XDHT.KHMC IS '客户名称';
COMMENT ON COLUMN CCRS_PM_XDHT.KHLX IS '客户类型';
COMMENT ON COLUMN CCRS_PM_XDHT.KHZJLX IS '客户证件类型';
COMMENT ON COLUMN CCRS_PM_XDHT.KHZJHM IS '客户证件号码';
COMMENT ON COLUMN CCRS_PM_XDHT.SXHTBH IS '授信合同编号';
COMMENT ON COLUMN CCRS_PM_XDHT.CPXX IS '产品细项';
COMMENT ON COLUMN CCRS_PM_XDHT.BZ IS '币种';
COMMENT ON COLUMN CCRS_PM_XDHT.DKHTJE_AMT IS '贷款合同金额';
COMMENT ON COLUMN CCRS_PM_XDHT.DKSJTX IS '贷款实际投向';
COMMENT ON COLUMN CCRS_PM_XDHT.DKYT IS '贷款用途';
COMMENT ON COLUMN CCRS_PM_XDHT.HTQSRQ_DATE IS '合同起始日期';
COMMENT ON COLUMN CCRS_PM_XDHT.HTDQRQ_DATE IS '合同到期日期';
COMMENT ON COLUMN CCRS_PM_XDHT.HKFS IS '还款方式';
COMMENT ON COLUMN CCRS_PM_XDHT.GRZFAJDKLX IS '个人住房按揭贷款类型';
COMMENT ON COLUMN CCRS_PM_XDHT.GRZFAJDKGFZJ_AMT IS '个人住房按揭贷款购房总价';
COMMENT ON COLUMN CCRS_PM_XDHT.SFZFDBJJDB IS '是否政府担保基金担保';
COMMENT ON COLUMN CCRS_PM_XDHT.RMYHDKZXJCBS IS '人民银行贷款专项监测标识';
COMMENT ON COLUMN CCRS_PM_XDHT.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_XDHT.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_XDHT.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_XDHT.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_XDHT.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_XDHT.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_XDHT.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_XDHT.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_XDHT.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_XDHT.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_XDHT.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_XDHT ON CCRS_PM_XDHT(DATA_RPT_DATE,SJRQ_DATE,XDHTBH);
