CREATE TABLE CCRS_PM_JRJGXXBCB(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    JRJGBM CHAR(14),
    JRJGMC VARCHAR2(300),
    ZCDQXZQHDM CHAR(12),
    HX1MC CHAR(2),
    HX2MC CHAR(2),
    JD VARCHAR2(11),
    WD VARCHAR2(10),
    D1DGDMC VARCHAR2(600),
    D1DGDZJLX CHAR(2),
    D1DGDZJHM VARCHAR2(50),
    D1DGDZJYXQX_DATE CHAR(8),
    D2DGDMC VARCHAR2(600),
    D2DGDZJLX CHAR(2),
    D2DGDZJHM VARCHAR2(50),
    D2DGDZJYXQX_DATE CHAR(8),
    D3DGDMC VARCHAR2(600),
    D3DGDZJLX CHAR(2),
    D3DGDZJHM VARCHAR2(50),
    D3DGDZJYXQX_DATE CHAR(8),
    D4DGDMC VARCHAR2(600),
    D4DGDZJLX CHAR(2),
    D4DGDZJHM VARCHAR2(50),
    D4DGDZJYXQX_DATE CHAR(8),
    D5DGDMC VARCHAR2(600),
    D5DGDZJLX CHAR(2),
    D5DGDZJHM VARCHAR2(50),
    D5DGDZJYXQX_DATE CHAR(8),
    D6DGDMC VARCHAR2(600),
    D6DGDZJLX CHAR(2),
    D6DGDZJHM VARCHAR2(50),
    D6DGDZJYXQX_DATE CHAR(8),
    D7DGDMC VARCHAR2(600),
    D7DGDZJLX CHAR(2),
    D7DGDZJHM VARCHAR2(50),
    D7DGDZJYXQX_DATE CHAR(8),
    D8DGDMC VARCHAR2(600),
    D8DGDZJLX CHAR(2),
    D8DGDZJHM VARCHAR2(50),
    D8DGDZJYXQX_DATE CHAR(8),
    D9DGDMC VARCHAR2(600),
    D9DGDZJLX CHAR(2),
    D9DGDZJHM VARCHAR2(50),
    D9DGDZJYXQX_DATE CHAR(8),
    D10DGDMC VARCHAR2(600),
    D10DGDZJLX CHAR(2),
    D10DGDZJHM VARCHAR2(50),
    D10DGDZJYXQX_DATE CHAR(8),
    SJRQ_DATE CHAR(8),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_JRJGXXBCB IS '金融机构信息补充表报文';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.JRJGMC IS '金融机构名称';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.ZCDQXZQHDM IS '注册地区行政区划代码';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.HX1MC IS '划型1名称';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.HX2MC IS '划型2名称';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.JD IS '经度';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.WD IS '纬度';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D1DGDMC IS '第1大股东名称';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D1DGDZJLX IS '第1大股东证件类型';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D1DGDZJHM IS '第1大股东证件号码';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D1DGDZJYXQX_DATE IS '第1大股东证件有效期限';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D2DGDMC IS '第2大股东名称';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D2DGDZJLX IS '第2大股东证件类型';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D2DGDZJHM IS '第2大股东证件号码';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D2DGDZJYXQX_DATE IS '第2大股东证件有效期限';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D3DGDMC IS '第3大股东名称';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D3DGDZJLX IS '第3大股东证件类型';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D3DGDZJHM IS '第3大股东证件号码';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D3DGDZJYXQX_DATE IS '第3大股东证件有效期限';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D4DGDMC IS '第4大股东名称';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D4DGDZJLX IS '第4大股东证件类型';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D4DGDZJHM IS '第4大股东证件号码';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D4DGDZJYXQX_DATE IS '第4大股东证件有效期限';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D5DGDMC IS '第5大股东名称';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D5DGDZJLX IS '第5大股东证件类型';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D5DGDZJHM IS '第5大股东证件号码';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D5DGDZJYXQX_DATE IS '第5大股东证件有效期限';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D6DGDMC IS '第6大股东名称';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D6DGDZJLX IS '第6大股东证件类型';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D6DGDZJHM IS '第6大股东证件号码';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D6DGDZJYXQX_DATE IS '第6大股东证件有效期限';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D7DGDMC IS '第7大股东名称';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D7DGDZJLX IS '第7大股东证件类型';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D7DGDZJHM IS '第7大股东证件号码';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D7DGDZJYXQX_DATE IS '第7大股东证件有效期限';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D8DGDMC IS '第8大股东名称';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D8DGDZJLX IS '第8大股东证件类型';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D8DGDZJHM IS '第8大股东证件号码';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D8DGDZJYXQX_DATE IS '第8大股东证件有效期限';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D9DGDMC IS '第9大股东名称';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D9DGDZJLX IS '第9大股东证件类型';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D9DGDZJHM IS '第9大股东证件号码';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D9DGDZJYXQX_DATE IS '第9大股东证件有效期限';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D10DGDMC IS '第10大股东名称';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D10DGDZJLX IS '第10大股东证件类型';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D10DGDZJHM IS '第10大股东证件号码';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.D10DGDZJYXQX_DATE IS '第10大股东证件有效期限';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_JRJGXXBCB.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_JRJGXXBCB ON CCRS_PM_JRJGXXBCB(DATA_RPT_DATE,JRJGBM,SJRQ_DATE);
