CREATE TABLE CCRS_PM_RZXBH(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE CHAR(8),
    JRJGBM CHAR(14),
    SXHTBH VARCHAR2(300),
    SQRMC VARCHAR2(300),
    SQRZJLX CHAR(2),
    SQRJJCF VARCHAR2(5),
    SQRDM VARCHAR2(50),
    BHBH VARCHAR2(50),
    BHSXRQ_DATE CHAR(8),
    BHDQRQ_DATE CHAR(8),
    BHBZ CHAR(3),
    BHJE_AMT NUMBER,
    BHLX CHAR(2),
    BZJBZ CHAR(3),
    BZJJE_AMT NUMBER,
    SXFL NUMBER,
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_RZXBH IS '融资性保函报文';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_RZXBH.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_RZXBH.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_RZXBH.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_RZXBH.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_RZXBH.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_RZXBH.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_RZXBH.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_RZXBH.SXHTBH IS '授信合同编号';
COMMENT ON COLUMN CCRS_PM_RZXBH.SQRMC IS '申请人名称';
COMMENT ON COLUMN CCRS_PM_RZXBH.SQRZJLX IS '申请人证件类型';
COMMENT ON COLUMN CCRS_PM_RZXBH.SQRJJCF IS '申请人经济成分';
COMMENT ON COLUMN CCRS_PM_RZXBH.SQRDM IS '申请人代码';
COMMENT ON COLUMN CCRS_PM_RZXBH.BHBH IS '保函编号';
COMMENT ON COLUMN CCRS_PM_RZXBH.BHSXRQ_DATE IS '保函生效日期';
COMMENT ON COLUMN CCRS_PM_RZXBH.BHDQRQ_DATE IS '保函到期日期';
COMMENT ON COLUMN CCRS_PM_RZXBH.BHBZ IS '保函币种';
COMMENT ON COLUMN CCRS_PM_RZXBH.BHJE_AMT IS '保函金额';
COMMENT ON COLUMN CCRS_PM_RZXBH.BHLX IS '保函类型';
COMMENT ON COLUMN CCRS_PM_RZXBH.BZJBZ IS '保证金币种';
COMMENT ON COLUMN CCRS_PM_RZXBH.BZJJE_AMT IS '保证金金额';
COMMENT ON COLUMN CCRS_PM_RZXBH.SXFL IS '手续费率';
COMMENT ON COLUMN CCRS_PM_RZXBH.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_RZXBH.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_RZXBH.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_RZXBH.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_RZXBH.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_RZXBH.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_RZXBH.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_RZXBH.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_RZXBH.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_RZXBH.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_RZXBH.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_RZXBH ON CCRS_PM_RZXBH(DATA_RPT_DATE,SJRQ_DATE,BHBH);
