CREATE TABLE CCRS_PM_GRKH(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE CHAR(8),
    JRJGBM CHAR(14),
    JRJGMC VARCHAR2(300),
    KHBH VARCHAR2(300),
    KHMC VARCHAR2(300),
    GRZJLX CHAR(2),
    GRZJYXQX_DATE CHAR(8),
    GRZJHM VARCHAR2(50),
    CSRQ_DATE CHAR(8),
    GJ CHAR(3),
    MZ CHAR(2),
    XB CHAR(2),
    XL CHAR(2),
    XW CHAR(1),
    HYZK CHAR(2),
    POZJLX CHAR(2),
    POZJHM VARCHAR2(50),
    POXM VARCHAR2(300),
    DQXZQHDMGRJTZZ CHAR(12),
    JTZZ VARCHAR2(300),
    GRLXDH VARCHAR2(20),
    ZY CHAR(2),
    GRDWMC VARCHAR2(300),
    GRDWDZ VARCHAR2(300),
    SFSNH CHAR(1),
    RMYHGRXXZXJCBS CHAR(50),
    HJSZD VARCHAR2(300),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_GRKH IS '个人客户报文';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_GRKH.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_GRKH.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_GRKH.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_GRKH.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_GRKH.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_GRKH.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_GRKH.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_GRKH.JRJGMC IS '金融机构名称';
COMMENT ON COLUMN CCRS_PM_GRKH.KHBH IS '客户编号';
COMMENT ON COLUMN CCRS_PM_GRKH.KHMC IS '客户名称';
COMMENT ON COLUMN CCRS_PM_GRKH.GRZJLX IS '个人证件类型';
COMMENT ON COLUMN CCRS_PM_GRKH.GRZJYXQX_DATE IS '个人证件有效期限';
COMMENT ON COLUMN CCRS_PM_GRKH.GRZJHM IS '个人证件号码';
COMMENT ON COLUMN CCRS_PM_GRKH.CSRQ_DATE IS '出生日期';
COMMENT ON COLUMN CCRS_PM_GRKH.GJ IS '国籍';
COMMENT ON COLUMN CCRS_PM_GRKH.MZ IS '民族';
COMMENT ON COLUMN CCRS_PM_GRKH.XB IS '性别';
COMMENT ON COLUMN CCRS_PM_GRKH.XL IS '学历';
COMMENT ON COLUMN CCRS_PM_GRKH.XW IS '学位';
COMMENT ON COLUMN CCRS_PM_GRKH.HYZK IS '婚姻状况';
COMMENT ON COLUMN CCRS_PM_GRKH.POZJLX IS '配偶证件类型';
COMMENT ON COLUMN CCRS_PM_GRKH.POZJHM IS '配偶证件号码';
COMMENT ON COLUMN CCRS_PM_GRKH.POXM IS '配偶姓名';
COMMENT ON COLUMN CCRS_PM_GRKH.DQXZQHDMGRJTZZ IS '地区行政区划代码（个人家庭住址）';
COMMENT ON COLUMN CCRS_PM_GRKH.JTZZ IS '家庭住址';
COMMENT ON COLUMN CCRS_PM_GRKH.GRLXDH IS '个人联系电话';
COMMENT ON COLUMN CCRS_PM_GRKH.ZY IS '职业';
COMMENT ON COLUMN CCRS_PM_GRKH.GRDWMC IS '个人单位名称';
COMMENT ON COLUMN CCRS_PM_GRKH.GRDWDZ IS '个人单位地址';
COMMENT ON COLUMN CCRS_PM_GRKH.SFSNH IS '是否是农户';
COMMENT ON COLUMN CCRS_PM_GRKH.RMYHGRXXZXJCBS IS '人民银行个人信息专项监测标识';
COMMENT ON COLUMN CCRS_PM_GRKH.HJSZD IS '户籍所在地';
COMMENT ON COLUMN CCRS_PM_GRKH.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_GRKH.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_GRKH.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_GRKH.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_GRKH.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_GRKH.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_GRKH.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_GRKH.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_GRKH.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_GRKH.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_GRKH.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_GRKH ON CCRS_PM_GRKH(DATA_RPT_DATE,SJRQ_DATE,KHBH);
