CREATE TABLE CCRS_PM_YHCDHPKL(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE CHAR(8),
    JRJGBM CHAR(14),
    YHCDHPBM VARCHAR2(30),
    SXHTBH VARCHAR2(300),
    KPQYMC VARCHAR2(300),
    KPQYZJLX CHAR(2),
    KPQYDM VARCHAR2(50),
    KPQYJJCF VARCHAR2(5),
    BZ CHAR(3),
    PMJE_AMT NUMBER,
    CPRQ_DATE CHAR(8),
    PJDQRQ_DATE CHAR(8),
    PJSKRMC VARCHAR2(300),
    PJDBBZ CHAR(3),
    PJDBJE_AMT NUMBER,
    PJDBLX CHAR(2),
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_YHCDHPKL IS '银行承兑汇票开立报文';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.YHCDHPBM IS '银行承兑汇票编码';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.SXHTBH IS '授信合同编号';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.KPQYMC IS '开票企业名称';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.KPQYZJLX IS '开票企业证件类型';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.KPQYDM IS '开票企业代码';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.KPQYJJCF IS '开票企业经济成分';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.BZ IS '币种';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.PMJE_AMT IS '票面金额';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.CPRQ_DATE IS '出票日期';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.PJDQRQ_DATE IS '票据到期日期';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.PJSKRMC IS '票据收款人名称';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.PJDBBZ IS '票据担保币种';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.PJDBJE_AMT IS '票据担保金额';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.PJDBLX IS '票据担保类型';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_YHCDHPKL.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_YHCDHPKL ON CCRS_PM_YHCDHPKL(DATA_RPT_DATE,SJRQ_DATE,YHCDHPBM);
