CREATE TABLE CCRS_PM_DECDYE(
    DATA_ID VARCHAR2(64) NOT NULL,
    DATA_DATE CHAR(8),
    DATA_RPT_DATE CHAR(8),
    CORP_ID VARCHAR2(14),
    ORG_ID VARCHAR2(14),
    GROUP_ID VARCHAR2(14),
    INQ_ORG_ID CHAR(24),
    INQ_GROUP_ID CHAR(24),
    SJRQ_DATE CHAR(8),
    JRJGBM CHAR(14),
    KHLX CHAR(1),
    KHMC VARCHAR2(300),
    KHZJLX CHAR(2),
    KHZJHM VARCHAR2(50),
    DQXZQHDMCDFXRZCD CHAR(12),
    CDXYDM VARCHAR2(150),
    CDMC VARCHAR2(300),
    CDXYQSRQ_DATE CHAR(8),
    CDXYDQRQ_DATE CHAR(8),
    CDSJDQRQ_DATE CHAR(8),
    BZ CHAR(3),
    CDFXGM_AMT NUMBER,
    LLSFGD CHAR(4),
    LLSP NUMBER,
    DECDQXLX CHAR(2),
    JZLLZL CHAR(2),
    FXPL CHAR(2),
    CDYE_AMT NUMBER,
    REMARKS VARCHAR2(14),
    CHECK_FLAG CHAR(1),
    CHECK_DESC VARCHAR2(512),
    CHECK_ERR_TYPE CHAR(1),
    NEXT_ACTION CHAR(2),
    DATA_STATUS CHAR(2),
    DATA_FLAG CHAR(1),
    DATA_SOURCE CHAR(1),
    DATA_VERSION NUMBER(8),
    DATA_REJ_DESC VARCHAR2(128),
    DATA_DEL_DESC VARCHAR2(128),
    DATA_CRT_USER VARCHAR2(20),
    DATA_CRT_DATE CHAR(8),
    DATA_CRT_TIME CHAR(14),
    DATA_CHG_USER VARCHAR2(20),
    DATA_CHG_DATE CHAR(8),
    DATA_CHG_TIME CHAR(14),
    DATA_APV_USER VARCHAR2(20),
    DATA_APV_DATE CHAR(8),
    DATA_APV_TIME CHAR(14),
    RSV1 VARCHAR2(180),
    RSV2 VARCHAR2(180),
    RSV3 VARCHAR2(180),
    RSV4 VARCHAR2(180),
    RSV5 VARCHAR2(180),
    PRIMARY KEY (DATA_ID)
);

COMMENT ON TABLE CCRS_PM_DECDYE IS '大额存单余额报文';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_ID IS '数据ID';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_RPT_DATE IS '报表日期';
COMMENT ON COLUMN CCRS_PM_DECDYE.CORP_ID IS '法人机构号';
COMMENT ON COLUMN CCRS_PM_DECDYE.ORG_ID IS '机构号';
COMMENT ON COLUMN CCRS_PM_DECDYE.GROUP_ID IS '部门编号';
COMMENT ON COLUMN CCRS_PM_DECDYE.INQ_ORG_ID IS '查询机构号';
COMMENT ON COLUMN CCRS_PM_DECDYE.INQ_GROUP_ID IS '查询组号';
COMMENT ON COLUMN CCRS_PM_DECDYE.SJRQ_DATE IS '数据日期';
COMMENT ON COLUMN CCRS_PM_DECDYE.JRJGBM IS '金融机构编码';
COMMENT ON COLUMN CCRS_PM_DECDYE.KHLX IS '客户类型';
COMMENT ON COLUMN CCRS_PM_DECDYE.KHMC IS '客户名称';
COMMENT ON COLUMN CCRS_PM_DECDYE.KHZJLX IS '客户证件类型';
COMMENT ON COLUMN CCRS_PM_DECDYE.KHZJHM IS '客户证件号码';
COMMENT ON COLUMN CCRS_PM_DECDYE.DQXZQHDMCDFXRZCD IS '地区行政区划代码（存单发行人注册地）';
COMMENT ON COLUMN CCRS_PM_DECDYE.CDXYDM IS '存单协议代码';
COMMENT ON COLUMN CCRS_PM_DECDYE.CDMC IS '存单名称';
COMMENT ON COLUMN CCRS_PM_DECDYE.CDXYQSRQ_DATE IS '存单协议起始日期';
COMMENT ON COLUMN CCRS_PM_DECDYE.CDXYDQRQ_DATE IS '存单协议到期日期';
COMMENT ON COLUMN CCRS_PM_DECDYE.CDSJDQRQ_DATE IS '存单实际到期日期';
COMMENT ON COLUMN CCRS_PM_DECDYE.BZ IS '币种';
COMMENT ON COLUMN CCRS_PM_DECDYE.CDFXGM_AMT IS '存单发行规模';
COMMENT ON COLUMN CCRS_PM_DECDYE.LLSFGD IS '利率是否固定';
COMMENT ON COLUMN CCRS_PM_DECDYE.LLSP IS '利率水平';
COMMENT ON COLUMN CCRS_PM_DECDYE.DECDQXLX IS '大额存单期限类型';
COMMENT ON COLUMN CCRS_PM_DECDYE.JZLLZL IS '基准利率种类';
COMMENT ON COLUMN CCRS_PM_DECDYE.FXPL IS '付息频率';
COMMENT ON COLUMN CCRS_PM_DECDYE.CDYE_AMT IS '存单余额';
COMMENT ON COLUMN CCRS_PM_DECDYE.REMARKS IS '备注';
COMMENT ON COLUMN CCRS_PM_DECDYE.CHECK_FLAG IS '校验标识';
COMMENT ON COLUMN CCRS_PM_DECDYE.CHECK_DESC IS '校验结果';
COMMENT ON COLUMN CCRS_PM_DECDYE.CHECK_ERR_TYPE IS '校验失败类型';
COMMENT ON COLUMN CCRS_PM_DECDYE.NEXT_ACTION IS '下一动作';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_STATUS IS '数据状态';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_FLAG IS '数据是否已删除';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_VERSION IS '数据版本';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_REJ_DESC IS '数据审核拒绝原因';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_DEL_DESC IS '数据删除描述';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_CRT_USER IS '数据创建/导入用户';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_CRT_DATE IS '数据创建/导入日期';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_CRT_TIME IS '数据创建/导入时间';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_CHG_USER IS '数据修改/删除用户';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_CHG_DATE IS '数据修改/删除日期';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_CHG_TIME IS '数据修改/删除时间';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_APV_USER IS '数据审核/拒绝用户';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_APV_DATE IS '数据审核/拒绝日期';
COMMENT ON COLUMN CCRS_PM_DECDYE.DATA_APV_TIME IS '数据审核/拒绝时间';
COMMENT ON COLUMN CCRS_PM_DECDYE.RSV1 IS '备用1';
COMMENT ON COLUMN CCRS_PM_DECDYE.RSV2 IS '备用2';
COMMENT ON COLUMN CCRS_PM_DECDYE.RSV3 IS '备用3';
COMMENT ON COLUMN CCRS_PM_DECDYE.RSV4 IS '备用4';
COMMENT ON COLUMN CCRS_PM_DECDYE.RSV5 IS '备用5';

CREATE UNIQUE INDEX U_DECDYE ON CCRS_PM_DECDYE(DATA_RPT_DATE,SJRQ_DATE,CDXYDM);
