update GP_BM_INQ_CFG set sql_string ='select DATA_ID,DATA_VERSION, PART_TYPE,OPT_TYPE,PART_NAME,DATA_STATUS, B_NAME, B_ID_TYPE, B_INF_SURC_CODE, B_ID_NUM, B_RPT_DATE,B_RPT_DATE_CODE, B_CUSTOMER_TYPE, B_CIMOC   from MBT_110_EX_Rpt where 1=1 @{_PRIV_COND}  and B_NAME like ''%'' || :"bName" || ''%'' and B_ID_TYPE = :"bIdType" and B_ID_NUM = :"bIdNum" and B_INF_SURC_CODE = :"bInfSurcCode" and DATA_STATUS in (''24'',''27'') and CORP_ID=:"v_corpid" and B_RPT_DATE=:"bRptDate"' where data_id = 'Mbt110ExRptQry';
update GP_BM_INQ_CFG set sql_string ='select DATA_ID, NAME,PART_TYPE,OPT_TYPE,PART_NAME, ID_ORG_NAME, ID_DIST, ID_EFCT_DATE, ID_DUE_DATE,CIMOC, INF_SURC_CODE, RPT_DATE, DATA_STATUS, INF_REC_TYPE, ID_TYPE, ID_NUM, DATA_DESC  from MBT_130_EX_RPT where 1=1 @{_PRIV_COND}  and NAME like ''%'' || :"name" || ''%'' and ID_ORG_NAME like ''%'' || :"idOrgName" || ''%''  and CIMOC=:"cimoc" and INF_SURC_CODE=:"infSurcCode" and DATA_STATUS in (''24'',''27'') and CORP_ID=:"v_corpid" and RPT_DATE=:"rptDate"' where data_id = 'Mbt130ExRptQry';
update GP_BM_INQ_CFG set sql_string ='SELECT DATA_ID,DATA_STATUS,B_INF_REC_TYPE,PART_TYPE,OPT_TYPE,PART_NAME,B_CONTRACT_CODE,B_RPT_DATE,B_RPT_DATE_CODE,B_NAME,B_ID_TYPE,B_ID_NUM,B_MNGMT_ORG_CODE,B_CONTRACT_NO,D_CREDIT_LIM_TYPE,D_LIM_LOOP_FLG,D_CREDIT_LIM,D_CY,D_CON_EFF_DATE,D_CON_EXP_DATE,D_CON_STATUS,D_CREDIT_REST,D_CREDIT_REST_CODE,F_DATA_DESC FROM MBT_220_EX_RPT where 1=1 @{_PRIV_COND}  and B_INF_REC_TYPE IN (''222'',''223'',''224'') and  B_NAME like  ''%''||:"bName"||''%'' and B_CONTRACT_CODE like ''%''||:"bContractCode"||''%'' and DATA_STATUS in (''24'',''27'') and CORP_ID=:"v_corpid" and B_RPT_DATE =:"bRptDate"' where data_id = 'Mbt220ExRptQry';
update GP_BM_INQ_CFG set sql_string ='SELECT DATA_ID, DATA_DATE, DATA_STATUS, B_INF_REC_TYPE,B_CONTRACT_CODE,B_RPT_DATE,PART_TYPE||''-''||PART_NAME PART_TYPE,DATA_DESC FROM MBT_420_EX_RPT E where 1=1  @{_PRIV_COND} and B_INF_REC_TYPE IN (''422'',''423'',''424'')  and B_CONTRACT_CODE = :"bContractCode" and B_RPT_DATE = :"bRptDate"  and DATA_STATUS in (''24'',''27'') and CORP_ID=:"v_corpid"' where data_id = 'Mbt420ExRptQry';
update GP_BM_INQ_CFG set sql_string ='select DATA_ID, DATA_DATE, ORG_ID, GROUP_ID, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, CORP_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, DATA_DESC, INF_REC_TYPE, OD_BNES_CODE, NW_BNES_CODE  from MBT_411 where 1=1 @{_PRIV_COND} and DATA_STATUS in(''24'',''27'') and DATA_ID=:"dataId" and  NW_BNES_CODE like ''%'' || :"nwBnesCode" || ''%''  and OD_BNES_CODE like ''%'' || :"odBnesCode" || ''%''  and CORP_ID=:"v_corpid"' where data_id = 'Mbt411RptQry';
update GP_BM_INQ_CFG set sql_string ='select DATA_ID, DATA_STATUS,PART_TYPE,OPT_TYPE,PART_NAME, B_ENT_NAME, B_ENT_CERT, B_ENT_CERT_NUM, B_INF_SURC_CODE, B_RPT_DATE, B_RPT_DATE_CODE, B_CIMOC, B_CUSTOMER_TYPE, B_ETP_STS, B_ORG_TYPE  from Mbt_310_EX_RPT where 1=1 @{_PRIV_COND}  and DATA_STATUS in (''24'',''27'') and B_ENT_NAME like ''%'' || :"bEntName" || ''%'' and B_ENT_CERT=:"bEntCert" and B_ENT_CERT_NUM=:"bEntCertNum" and B_INF_SURC_CODE=:"bInfSurcCode"  and CORP_ID=:"v_corpid" and B_RPT_DATE =:"bRptDate"' where data_id = 'Mbt310ExRptQry';
update GP_BM_INQ_CFG set sql_string ='select DATA_ID, DATA_DATE, ORG_ID, GROUP_ID, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, CORP_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, DATA_DESC, INF_REC_TYPE, OD_BNES_CODE, NW_BNES_CODE  from MBT_211_RPT where 1=1  @{_PRIV_COND} and  DATA_STATUS in(''24'',''27'') and DATA_ID=:"dataId" and  NW_BNES_CODE like ''%'' || :"nwBnesCode" || ''%''  and OD_BNES_CODE like ''%'' || :"odBnesCode" || ''%''  and CORP_ID=:"v_corpid"' where data_id = 'Mbt211RptQry';
update GP_BM_INQ_CFG set sql_string ='select DATA_STATUS,DATA_ID, INF_REC_TYPE, OD_BNES_CODE , NW_BNES_CODE , DATA_DESC, DATA_CRT_TIME from MBT_221_RPT where 1=1 @{_PRIV_COND}  and OD_BNES_CODE =:"odBnesCode" and NW_BNES_CODE =:"nwBnesCode" and DATA_STATUS IN (''24'',''27'') and CORP_ID=:"v_corpid"' where data_id = 'Mbt221RptQry';
update GP_BM_INQ_CFG set sql_string ='SELECT DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, DATA_ID, INF_REC_TYPE, ACCT_CODE, OPETN_TYPE, MONTH, FLAG, RPT_DATE, DATA_DESC, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, ODS_DATA_ID, RPT_TIME FROM MBT_215_RPT  where 1=1 @{_PRIV_COND}  and ACCT_CODE like ''%'' || :"acctCode" || ''%'' and FLAG=:"flag" and MONTH =:"month" and OPETN_TYPE=:"opetnType" and DATA_STATUS IN (''24'',''27'') and CORP_ID=:"v_corpid"' where data_id = 'Mbt215RptQry';
update GP_BM_INQ_CFG set sql_string ='select  DATA_ID,DATA_STATUS,B_INF_REC_TYPE,B_ACCT_CODE,RPT_DATE,PART_TYPE,OPT_TYPE,PART_NAME,DATA_DESC from MBT_440_EX_RPT where 1=1 @{_PRIV_COND}  and  PART_NAME=:"partName"  and PART_TYPE=:"part_type" and DATA_STATUS in (''24'',''27'') and CORP_ID=:"v_corpid" and B_RPT_DATE =:"bRptDate"' where data_id = 'Mbt440ExRptQry';
update GP_BM_INQ_CFG set sql_string ='select DATA_VERSION,DATA_STATUS,B_ACCT_CODE,B_INF_REC_TYPE,MOD_REC_CODE,RPT_DATE,PART_TYPE,OPT_TYPE,PART_NAME,DATA_DESC,DATA_ID from MBT_230_EX_RPT where 1=1 @{_PRIV_COND}  and   PART_NAME=:"partName"  and PART_TYPE=:"part_type" and DATA_STATUS in (''24'',''27'') and CORP_ID=:"v_corpid" and RPT_DATE=:"rptDate"' where data_id = 'Mbt230ExRptQry';
update GP_BM_INQ_CFG set sql_string ='select DATA_ID,DATA_STATUS,PART_TYPE,OPT_TYPE,PART_NAME, B_INF_REC_NO, B_INF_REC_TYPE, B_CC_CODE, B_RPT_DATE, B_RPT_DATE_CODE, B_INFO_ID_TYPE, B_NAME, B_CERT_TYPE, B_CERT_NUM, B_MNGMT_ORG_CODE, B_CUST_NO  from MBT_510_EX_RPT  where 1=1 @{_PRIV_COND} and  B_CC_CODE=:"bCcCode" and B_NAME like  ''%''||:"bName"||''%'' and DATA_STATUS in (''24'',''27'') and CORP_ID=:"v_corpid" and B_RPT_DATE =:"bRptDate" and B_RPT_DATE =:"bRptDate"' where data_id = 'Mbt510ExRptQry';
update GP_BM_INQ_CFG set sql_string ='select DATA_STATUS,DATA_ID, INF_REC_TYPE, OD_BNES_CODE , NW_BNES_CODE , DATA_DESC, DATA_CRT_TIME from MBT_511_RPT where 1=1 @{_PRIV_COND}  and CUST_TYPE=''C''  and OD_BNES_CODE =:"odBnesCode" and NW_BNES_CODE =:"nwBnesCod" and DATA_STATUS IN (''24'',''27'') and CORP_ID=:"v_corpid"' where data_id = 'Mbt511RptQry';
update GP_BM_INQ_CFG set sql_string ='SELECT DATA_ID,DATA_STATUS,B_INF_REC_TYPE, B_ACCT_TYPE, B_ACCT_CODE, B_RPT_DATE, PART_NAME,OPT_TYPE, PART_TYPE, DATA_DESC FROM MBT_210_EX_RPT where 1=1  @{_PRIV_COND} and  DATA_ID =:"dataId"  and B_ACCT_TYPE =:"bAcctType" and B_ACCT_CODE like ''%''||:"bAcctCode"|| ''%'' and DATA_STATUS IN (''24'',''27'')  and CORP_ID=:"v_corpid" and B_RPT_DATE=:"bRptDate"' where data_id = 'Mbt210ExRptQry';
update GP_BM_INQ_CFG set sql_string ='select DATA_STATUS,DATA_ID, INF_REC_TYPE, OD_BNES_CODE , NW_BNES_CODE , DATA_DESC, DATA_CRT_TIME from MBT_511_RPT where 1=1 @{_PRIV_COND}  and CUST_TYPE=''P''  and OD_BNES_CODE =:"odBnesCode" and NW_BNES_CODE =:"nwBnesCode" and DATA_STATUS IN (''24'',''27'') and CORP_ID=:"v_corpid"' where data_id = 'Mbt511_P_RptQry';
update GP_BM_INQ_CFG set sql_string ='select  DATA_ID,DATA_STATUS,B_INF_REC_TYPE,B_ACCT_CODE,RPT_DATE,PART_TYPE,OPT_TYPE,PART_NAME,DATA_DESC from MBT_410_EX_Rpt where 1=1 and  PART_NAME=:"partName"  and PART_TYPE=:"part_type" and DATA_STATUS in (''24'',''27'')' where data_id = 'Mbt410ExRptQry';

