-- 校验框架升级
-- 如果要更新的话需要刷新pom,还要执行这2句sql，如果不更新就不能执行
alter table GP_QC_RULE rename column SQL to EXISTS_SQL;
alter table GP_QC_TYPE rename column SQL to EXISTS_SQL;


DELETE FROM GP_QC_RULE_MAP WHERE DATA_ID='MBT_420CUSTOMIZEDValidation00004';
INSERT INTO GP_QC_RULE_MAP (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_SET_ID, RULE_ID, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES('MBT_420CUSTOMIZEDValidation00004', '20200904', 'TESTCORP', '72', '002', NULL, NULL, 'MBT_420_1700701', 'MBT_420CUSTOMIZEDValidation00004', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'mbtrule', NULL);


DELETE FROM GP_QC_RULE WHERE DATA_ID='MBT_420CUSTOMIZEDValidation00004';
INSERT INTO GP_QC_RULE (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, RULE_DESC, RULE_MESSAGE, RULE_TYPE, RULE_SOURCE, FIELD, FIELD_NAME, TRIMMABLE, NULLABLE, TYPE_ID, ENCODING, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, MAX_PRECISION, MIN_SCALE, MAX_SCALE, ENUMERATION, PATTERN, IN_ENTITY, IN_FIELD, EXISTS_SQL, SQL_EXTRA_KEY, SCRIPT, BEAN, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_OP, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES('MBT_420CUSTOMIZEDValidation00004', '20200904', 'TESTCORP', '72', '002', NULL, NULL, ' 当授信额度类型为黄金借贷时，授信限额/授信限额编号不能为空', ' 当授信额度类型为黄金借贷时，授信限额/授信限额编号不能为空', NULL, 'BUSI', 'DATA_ID', NULL, NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ' if (B_CONTRACT_CODE.contains("GDL") ){
       if ( !isEmpty(D_CREDIT_REST) && !isEmpty(D_CREDIT_REST_CODE)){
       return true
       }
       return FALSE
       
      }
       return true', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '6a46ca0aee8c4712bb7d86a884fab723', NULL, NULL, 'mbtrule', '1');