ALTER TABLE MBT_210 ADD (J_LAT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (J_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (J_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (I_USED_INST_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (I_SPEC_LINE_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (H_ACT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (H_CUR_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (H_OVERD_RAW_BA_OVE180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (H_OVERD_PRINC180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (H_OVERD91_180PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (H_OVERD61_90PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (H_OVERD31_60PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (H_OVAER_PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (H_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (H_NOTLSU_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (H_USED_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (H_PRID_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (H_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (C_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210 ADD (C_ACCT_CRED_LINE_AMT_ORG NUMBER(15)) ; 

COMMENT ON COLUMN MBT_210.J_LAT_RPY_AMT_ORG IS '最近一次实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210.J_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210.J_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210.I_USED_INST_AMT_ORG IS '已用分期金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210.I_SPEC_LINE_ORG IS '大额专项分期额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210.H_ACT_RPY_AMT_ORG IS '本月实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210.H_CUR_RPY_AMT_ORG IS '本月应还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210.H_OVERD_RAW_BA_OVE180_ORG IS '透支 180 天以上未还余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210.H_OVERD_PRINC180_ORG IS '逾期 180 天以上未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210.H_OVERD91_180PRINC_ORG IS '逾期 91-180 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210.H_OVERD61_90PRINC_ORG IS '逾期 61-90 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210.H_OVERD31_60PRINC_ORG IS '逾期 31-60 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210.H_OVAER_PRINC_ORG IS '当前逾期本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210.H_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210.H_NOTLSU_BAL_ORG IS '未出单的大额专项分期余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210.H_USED_AMT_ORG IS '已使用额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210.H_PRID_ACCT_BAL_ORG IS '本期账单余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210.H_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210.C_LOAN_AMT_ORG IS '借款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210.C_ACCT_CRED_LINE_AMT_ORG IS '信用额度_原始数据金额'; 


ALTER TABLE MBT_210_EX ADD (J_LAT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (J_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (J_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (I_USED_INST_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (I_SPEC_LINE_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (H_ACT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (H_CUR_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (H_OVERD_RAW_BA_OVE180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (H_OVERD_PRINC180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (H_OVERD91_180PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (H_OVERD61_90PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (H_OVERD31_60PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (H_OVAER_PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (H_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (H_NOTLSU_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (H_USED_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (H_PRID_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (H_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (C_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX ADD (C_ACCT_CRED_LINE_AMT_ORG NUMBER(15)) ; 

COMMENT ON COLUMN MBT_210_EX.J_LAT_RPY_AMT_ORG IS '最近一次实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.J_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.J_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.I_USED_INST_AMT_ORG IS '已用分期金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.I_SPEC_LINE_ORG IS '大额专项分期额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.H_ACT_RPY_AMT_ORG IS '本月实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.H_CUR_RPY_AMT_ORG IS '本月应还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.H_OVERD_RAW_BA_OVE180_ORG IS '透支 180 天以上未还余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.H_OVERD_PRINC180_ORG IS '逾期 180 天以上未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.H_OVERD91_180PRINC_ORG IS '逾期 91-180 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.H_OVERD61_90PRINC_ORG IS '逾期 61-90 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.H_OVERD31_60PRINC_ORG IS '逾期 31-60 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.H_OVAER_PRINC_ORG IS '当前逾期本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.H_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.H_NOTLSU_BAL_ORG IS '未出单的大额专项分期余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.H_USED_AMT_ORG IS '已使用额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.H_PRID_ACCT_BAL_ORG IS '本期账单余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.H_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.C_LOAN_AMT_ORG IS '借款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX.C_ACCT_CRED_LINE_AMT_ORG IS '信用额度_原始数据金额'; 



ALTER TABLE MBT_210_EX_HIS ADD (J_LAT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (J_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (J_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (I_USED_INST_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (I_SPEC_LINE_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (H_ACT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (H_CUR_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (H_OVERD_RAW_BA_OVE180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (H_OVERD_PRINC180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (H_OVERD91_180PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (H_OVERD61_90PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (H_OVERD31_60PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (H_OVAER_PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (H_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (H_NOTLSU_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (H_USED_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (H_PRID_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (H_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (C_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_HIS ADD (C_ACCT_CRED_LINE_AMT_ORG NUMBER(15)) ; 

COMMENT ON COLUMN MBT_210_EX_HIS.J_LAT_RPY_AMT_ORG IS '最近一次实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.J_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.J_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.I_USED_INST_AMT_ORG IS '已用分期金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.I_SPEC_LINE_ORG IS '大额专项分期额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.H_ACT_RPY_AMT_ORG IS '本月实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.H_CUR_RPY_AMT_ORG IS '本月应还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.H_OVERD_RAW_BA_OVE180_ORG IS '透支 180 天以上未还余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.H_OVERD_PRINC180_ORG IS '逾期 180 天以上未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.H_OVERD91_180PRINC_ORG IS '逾期 91-180 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.H_OVERD61_90PRINC_ORG IS '逾期 61-90 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.H_OVERD31_60PRINC_ORG IS '逾期 31-60 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.H_OVAER_PRINC_ORG IS '当前逾期本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.H_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.H_NOTLSU_BAL_ORG IS '未出单的大额专项分期余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.H_USED_AMT_ORG IS '已使用额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.H_PRID_ACCT_BAL_ORG IS '本期账单余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.H_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.C_LOAN_AMT_ORG IS '借款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_HIS.C_ACCT_CRED_LINE_AMT_ORG IS '信用额度_原始数据金额'; 

ALTER TABLE MBT_210_EX_RPT ADD (J_LAT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (J_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (J_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (I_USED_INST_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (I_SPEC_LINE_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (H_ACT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (H_CUR_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (H_OVERD_RAW_BA_OVE180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (H_OVERD_PRINC180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (H_OVERD91_180PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (H_OVERD61_90PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (H_OVERD31_60PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (H_OVAER_PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (H_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (H_NOTLSU_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (H_USED_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (H_PRID_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (H_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (C_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_RPT ADD (C_ACCT_CRED_LINE_AMT_ORG NUMBER(15)) ; 

COMMENT ON COLUMN MBT_210_EX_RPT.J_LAT_RPY_AMT_ORG IS '最近一次实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.J_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.J_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.I_USED_INST_AMT_ORG IS '已用分期金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.I_SPEC_LINE_ORG IS '大额专项分期额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.H_ACT_RPY_AMT_ORG IS '本月实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.H_CUR_RPY_AMT_ORG IS '本月应还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.H_OVERD_RAW_BA_OVE180_ORG IS '透支 180 天以上未还余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.H_OVERD_PRINC180_ORG IS '逾期 180 天以上未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.H_OVERD91_180PRINC_ORG IS '逾期 91-180 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.H_OVERD61_90PRINC_ORG IS '逾期 61-90 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.H_OVERD31_60PRINC_ORG IS '逾期 31-60 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.H_OVAER_PRINC_ORG IS '当前逾期本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.H_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.H_NOTLSU_BAL_ORG IS '未出单的大额专项分期余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.H_USED_AMT_ORG IS '已使用额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.H_PRID_ACCT_BAL_ORG IS '本期账单余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.H_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.C_LOAN_AMT_ORG IS '借款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_RPT.C_ACCT_CRED_LINE_AMT_ORG IS '信用额度_原始数据金额'; 

ALTER TABLE MBT_210_EX_TMP ADD (J_LAT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (J_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (J_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (I_USED_INST_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (I_SPEC_LINE_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (H_ACT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (H_CUR_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (H_OVERD_RAW_BA_OVE180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (H_OVERD_PRINC180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (H_OVERD91_180PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (H_OVERD61_90PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (H_OVERD31_60PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (H_OVAER_PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (H_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (H_NOTLSU_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (H_USED_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (H_PRID_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (H_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (C_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_EX_TMP ADD (C_ACCT_CRED_LINE_AMT_ORG NUMBER(15)) ; 

COMMENT ON COLUMN MBT_210_EX_TMP.J_LAT_RPY_AMT_ORG IS '最近一次实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.J_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.J_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.I_USED_INST_AMT_ORG IS '已用分期金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.I_SPEC_LINE_ORG IS '大额专项分期额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.H_ACT_RPY_AMT_ORG IS '本月实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.H_CUR_RPY_AMT_ORG IS '本月应还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.H_OVERD_RAW_BA_OVE180_ORG IS '透支 180 天以上未还余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.H_OVERD_PRINC180_ORG IS '逾期 180 天以上未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.H_OVERD91_180PRINC_ORG IS '逾期 91-180 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.H_OVERD61_90PRINC_ORG IS '逾期 61-90 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.H_OVERD31_60PRINC_ORG IS '逾期 31-60 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.H_OVAER_PRINC_ORG IS '当前逾期本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.H_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.H_NOTLSU_BAL_ORG IS '未出单的大额专项分期余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.H_USED_AMT_ORG IS '已使用额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.H_PRID_ACCT_BAL_ORG IS '本期账单余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.H_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.C_LOAN_AMT_ORG IS '借款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_EX_TMP.C_ACCT_CRED_LINE_AMT_ORG IS '信用额度_原始数据金额'; 


ALTER TABLE MBT_210_HIS ADD (J_LAT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (J_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (J_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (I_USED_INST_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (I_SPEC_LINE_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (H_ACT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (H_CUR_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (H_OVERD_RAW_BA_OVE180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (H_OVERD_PRINC180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (H_OVERD91_180PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (H_OVERD61_90PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (H_OVERD31_60PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (H_OVAER_PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (H_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (H_NOTLSU_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (H_USED_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (H_PRID_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (H_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (C_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_HIS ADD (C_ACCT_CRED_LINE_AMT_ORG NUMBER(15)) ; 

COMMENT ON COLUMN MBT_210_HIS.J_LAT_RPY_AMT_ORG IS '最近一次实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.J_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.J_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.I_USED_INST_AMT_ORG IS '已用分期金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.I_SPEC_LINE_ORG IS '大额专项分期额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.H_ACT_RPY_AMT_ORG IS '本月实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.H_CUR_RPY_AMT_ORG IS '本月应还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.H_OVERD_RAW_BA_OVE180_ORG IS '透支 180 天以上未还余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.H_OVERD_PRINC180_ORG IS '逾期 180 天以上未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.H_OVERD91_180PRINC_ORG IS '逾期 91-180 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.H_OVERD61_90PRINC_ORG IS '逾期 61-90 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.H_OVERD31_60PRINC_ORG IS '逾期 31-60 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.H_OVAER_PRINC_ORG IS '当前逾期本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.H_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.H_NOTLSU_BAL_ORG IS '未出单的大额专项分期余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.H_USED_AMT_ORG IS '已使用额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.H_PRID_ACCT_BAL_ORG IS '本期账单余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.H_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.C_LOAN_AMT_ORG IS '借款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_HIS.C_ACCT_CRED_LINE_AMT_ORG IS '信用额度_原始数据金额'; 

ALTER TABLE MBT_210_RPT ADD (J_LAT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (J_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (J_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (I_USED_INST_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (I_SPEC_LINE_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (H_ACT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (H_CUR_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (H_OVERD_RAW_BA_OVE180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (H_OVERD_PRINC180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (H_OVERD91_180PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (H_OVERD61_90PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (H_OVERD31_60PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (H_OVAER_PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (H_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (H_NOTLSU_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (H_USED_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (H_PRID_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (H_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (C_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_RPT ADD (C_ACCT_CRED_LINE_AMT_ORG NUMBER(15)) ; 

COMMENT ON COLUMN MBT_210_RPT.J_LAT_RPY_AMT_ORG IS '最近一次实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.J_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.J_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.I_USED_INST_AMT_ORG IS '已用分期金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.I_SPEC_LINE_ORG IS '大额专项分期额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.H_ACT_RPY_AMT_ORG IS '本月实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.H_CUR_RPY_AMT_ORG IS '本月应还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.H_OVERD_RAW_BA_OVE180_ORG IS '透支 180 天以上未还余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.H_OVERD_PRINC180_ORG IS '逾期 180 天以上未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.H_OVERD91_180PRINC_ORG IS '逾期 91-180 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.H_OVERD61_90PRINC_ORG IS '逾期 61-90 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.H_OVERD31_60PRINC_ORG IS '逾期 31-60 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.H_OVAER_PRINC_ORG IS '当前逾期本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.H_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.H_NOTLSU_BAL_ORG IS '未出单的大额专项分期余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.H_USED_AMT_ORG IS '已使用额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.H_PRID_ACCT_BAL_ORG IS '本期账单余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.H_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.C_LOAN_AMT_ORG IS '借款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_RPT.C_ACCT_CRED_LINE_AMT_ORG IS '信用额度_原始数据金额'; 

ALTER TABLE MBT_210_TMP ADD (J_LAT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (J_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (J_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (I_USED_INST_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (I_SPEC_LINE_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (H_ACT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (H_CUR_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (H_OVERD_RAW_BA_OVE180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (H_OVERD_PRINC180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (H_OVERD91_180PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (H_OVERD61_90PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (H_OVERD31_60PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (H_OVAER_PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (H_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (H_NOTLSU_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (H_USED_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (H_PRID_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (H_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (C_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TMP ADD (C_ACCT_CRED_LINE_AMT_ORG NUMBER(15)) ; 

COMMENT ON COLUMN MBT_210_TMP.J_LAT_RPY_AMT_ORG IS '最近一次实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.J_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.J_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.I_USED_INST_AMT_ORG IS '已用分期金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.I_SPEC_LINE_ORG IS '大额专项分期额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.H_ACT_RPY_AMT_ORG IS '本月实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.H_CUR_RPY_AMT_ORG IS '本月应还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.H_OVERD_RAW_BA_OVE180_ORG IS '透支 180 天以上未还余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.H_OVERD_PRINC180_ORG IS '逾期 180 天以上未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.H_OVERD91_180PRINC_ORG IS '逾期 91-180 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.H_OVERD61_90PRINC_ORG IS '逾期 61-90 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.H_OVERD31_60PRINC_ORG IS '逾期 31-60 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.H_OVAER_PRINC_ORG IS '当前逾期本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.H_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.H_NOTLSU_BAL_ORG IS '未出单的大额专项分期余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.H_USED_AMT_ORG IS '已使用额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.H_PRID_ACCT_BAL_ORG IS '本期账单余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.H_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.C_LOAN_AMT_ORG IS '借款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TMP.C_ACCT_CRED_LINE_AMT_ORG IS '信用额度_原始数据金额'; 

ALTER TABLE MBT_210_TODAY_BAK ADD (J_LAT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (J_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (J_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (I_USED_INST_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (I_SPEC_LINE_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (H_ACT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (H_CUR_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (H_OVERD_RAW_BA_OVE180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (H_OVERD_PRINC180_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (H_OVERD91_180PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (H_OVERD61_90PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (H_OVERD31_60PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (H_OVAER_PRINC_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (H_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (H_NOTLSU_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (H_USED_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (H_PRID_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (H_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (C_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_210_TODAY_BAK ADD (C_ACCT_CRED_LINE_AMT_ORG NUMBER(15)) ; 

COMMENT ON COLUMN MBT_210_TODAY_BAK.J_LAT_RPY_AMT_ORG IS '最近一次实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.J_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.J_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.I_USED_INST_AMT_ORG IS '已用分期金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.I_SPEC_LINE_ORG IS '大额专项分期额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.H_ACT_RPY_AMT_ORG IS '本月实际还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.H_CUR_RPY_AMT_ORG IS '本月应还款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.H_OVERD_RAW_BA_OVE180_ORG IS '透支 180 天以上未还余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.H_OVERD_PRINC180_ORG IS '逾期 180 天以上未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.H_OVERD91_180PRINC_ORG IS '逾期 91-180 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.H_OVERD61_90PRINC_ORG IS '逾期 61-90 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.H_OVERD31_60PRINC_ORG IS '逾期 31-60 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.H_OVAER_PRINC_ORG IS '当前逾期本金_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.H_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.H_NOTLSU_BAL_ORG IS '未出单的大额专项分期余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.H_USED_AMT_ORG IS '已使用额度_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.H_PRID_ACCT_BAL_ORG IS '本期账单余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.H_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.C_LOAN_AMT_ORG IS '借款金额_原始数据金额'; 
COMMENT ON COLUMN MBT_210_TODAY_BAK.C_ACCT_CRED_LINE_AMT_ORG IS '信用额度_原始数据金额'; 

ALTER TABLE ODS_MBT_210 ADD (J_LAT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (J_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (J_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (I_USED_INST_AMT_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (I_SPEC_LINE_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (H_ACT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (H_CUR_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (H_OVERD_RAW_BA_OVE180_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (H_OVERD_PRINC180_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (H_OVERD91_180PRINC_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (H_OVERD61_90PRINC_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (H_OVERD31_60PRINC_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (H_OVAER_PRINC_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (H_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (H_NOTLSU_BAL_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (H_USED_AMT_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (H_PRID_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (H_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (C_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210 ADD (C_ACCT_CRED_LINE_AMT_ORG NUMBER(15)) ; 

COMMENT ON COLUMN ODS_MBT_210.J_LAT_RPY_AMT_ORG IS '最近一次实际还款金额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.J_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.J_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.I_USED_INST_AMT_ORG IS '已用分期金额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.I_SPEC_LINE_ORG IS '大额专项分期额度_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.H_ACT_RPY_AMT_ORG IS '本月实际还款金额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.H_CUR_RPY_AMT_ORG IS '本月应还款金额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.H_OVERD_RAW_BA_OVE180_ORG IS '透支 180 天以上未还余额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.H_OVERD_PRINC180_ORG IS '逾期 180 天以上未归还本金_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.H_OVERD91_180PRINC_ORG IS '逾期 91-180 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.H_OVERD61_90PRINC_ORG IS '逾期 61-90 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.H_OVERD31_60PRINC_ORG IS '逾期 31-60 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.H_OVAER_PRINC_ORG IS '当前逾期本金_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.H_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.H_NOTLSU_BAL_ORG IS '未出单的大额专项分期余额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.H_USED_AMT_ORG IS '已使用额度_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.H_PRID_ACCT_BAL_ORG IS '本期账单余额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.H_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.C_LOAN_AMT_ORG IS '借款金额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210.C_ACCT_CRED_LINE_AMT_ORG IS '信用额度_原始数据金额'; 

ALTER TABLE ODS_MBT_210_HIS ADD (J_LAT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (J_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (J_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (I_USED_INST_AMT_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (I_SPEC_LINE_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (H_ACT_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (H_CUR_RPY_AMT_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (H_OVERD_RAW_BA_OVE180_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (H_OVERD_PRINC180_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (H_OVERD91_180PRINC_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (H_OVERD61_90PRINC_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (H_OVERD31_60PRINC_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (H_OVAER_PRINC_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (H_TOT_OVERD_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (H_NOTLSU_BAL_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (H_USED_AMT_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (H_PRID_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (H_ACCT_BAL_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (C_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_210_HIS ADD (C_ACCT_CRED_LINE_AMT_ORG NUMBER(15)) ; 

COMMENT ON COLUMN ODS_MBT_210_HIS.J_LAT_RPY_AMT_ORG IS '最近一次实际还款金额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.J_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.J_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.I_USED_INST_AMT_ORG IS '已用分期金额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.I_SPEC_LINE_ORG IS '大额专项分期额度_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.H_ACT_RPY_AMT_ORG IS '本月实际还款金额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.H_CUR_RPY_AMT_ORG IS '本月应还款金额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.H_OVERD_RAW_BA_OVE180_ORG IS '透支 180 天以上未还余额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.H_OVERD_PRINC180_ORG IS '逾期 180 天以上未归还本金_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.H_OVERD91_180PRINC_ORG IS '逾期 91-180 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.H_OVERD61_90PRINC_ORG IS '逾期 61-90 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.H_OVERD31_60PRINC_ORG IS '逾期 31-60 天未归还本金_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.H_OVAER_PRINC_ORG IS '当前逾期本金_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.H_TOT_OVERD_ORG IS '当前逾期总额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.H_NOTLSU_BAL_ORG IS '未出单的大额专项分期余额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.H_USED_AMT_ORG IS '已使用额度_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.H_PRID_ACCT_BAL_ORG IS '本期账单余额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.H_ACCT_BAL_ORG IS '余额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.C_LOAN_AMT_ORG IS '借款金额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_210_HIS.C_ACCT_CRED_LINE_AMT_ORG IS '信用额度_原始数据金额'; 
-------------------------------------------------------220--------------------------------------------------------------
ALTER TABLE MBT_220 ADD (D_CREDIT_REST_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220 ADD (D_CREDIT_LIM_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220_EX ADD (D_CREDIT_REST_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220_EX ADD (D_CREDIT_LIM_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220_EX_HIS ADD (D_CREDIT_REST_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220_EX_HIS ADD (D_CREDIT_LIM_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220_EX_RPT ADD (D_CREDIT_REST_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220_EX_RPT ADD (D_CREDIT_LIM_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220_EX_TMP ADD (D_CREDIT_REST_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220_EX_TMP ADD (D_CREDIT_LIM_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220_HIS ADD (D_CREDIT_REST_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220_HIS ADD (D_CREDIT_LIM_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220_RPT ADD (D_CREDIT_REST_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220_RPT ADD (D_CREDIT_LIM_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220_TMP ADD (D_CREDIT_REST_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220_TMP ADD (D_CREDIT_LIM_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220_TODAY_BAK ADD (D_CREDIT_REST_ORG NUMBER(15)) ; 
ALTER TABLE MBT_220_TODAY_BAK ADD (D_CREDIT_LIM_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_220 ADD (D_CREDIT_REST_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_220 ADD (D_CREDIT_LIM_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_220_HIS ADD (D_CREDIT_REST_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_220_HIS ADD (D_CREDIT_LIM_ORG NUMBER(15)) ; 

COMMENT ON COLUMN MBT_220.D_CREDIT_REST_ORG IS '授信限额_原始数据金额'; 
COMMENT ON COLUMN MBT_220.D_CREDIT_LIM_ORG IS '授信额度_原始数据金额'; 
COMMENT ON COLUMN MBT_220_EX.D_CREDIT_REST_ORG IS '授信限额_原始数据金额'; 
COMMENT ON COLUMN MBT_220_EX.D_CREDIT_LIM_ORG IS '授信额度_原始数据金额'; 
COMMENT ON COLUMN MBT_220_EX_HIS.D_CREDIT_REST_ORG IS '授信限额_原始数据金额'; 
COMMENT ON COLUMN MBT_220_EX_HIS.D_CREDIT_LIM_ORG IS '授信额度_原始数据金额'; 
COMMENT ON COLUMN MBT_220_EX_RPT.D_CREDIT_REST_ORG IS '授信限额_原始数据金额'; 
COMMENT ON COLUMN MBT_220_EX_RPT.D_CREDIT_LIM_ORG IS '授信额度_原始数据金额'; 
COMMENT ON COLUMN MBT_220_EX_TMP.D_CREDIT_REST_ORG IS '授信限额_原始数据金额'; 
COMMENT ON COLUMN MBT_220_EX_TMP.D_CREDIT_LIM_ORG IS '授信额度_原始数据金额'; 
COMMENT ON COLUMN MBT_220_HIS.D_CREDIT_REST_ORG IS '授信限额_原始数据金额'; 
COMMENT ON COLUMN MBT_220_HIS.D_CREDIT_LIM_ORG IS '授信额度_原始数据金额'; 
COMMENT ON COLUMN MBT_220_RPT.D_CREDIT_REST_ORG IS '授信限额_原始数据金额'; 
COMMENT ON COLUMN MBT_220_RPT.D_CREDIT_LIM_ORG IS '授信额度_原始数据金额'; 
COMMENT ON COLUMN MBT_220_TMP.D_CREDIT_REST_ORG IS '授信限额_原始数据金额'; 
COMMENT ON COLUMN MBT_220_TMP.D_CREDIT_LIM_ORG IS '授信额度_原始数据金额'; 
COMMENT ON COLUMN MBT_220_TODAY_BAK.D_CREDIT_REST_ORG IS '授信限额_原始数据金额'; 
COMMENT ON COLUMN MBT_220_TODAY_BAK.D_CREDIT_LIM_ORG IS '授信额度_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_220.D_CREDIT_REST_ORG IS '授信限额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_220.D_CREDIT_LIM_ORG IS '授信额度_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_220_HIS.D_CREDIT_REST_ORG IS '授信限额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_220_HIS.D_CREDIT_LIM_ORG IS '授信额度_原始数据金额'; 
-------------------------------------------------------230--------------------------------------------------------------
ALTER TABLE MBT_230 ADD (D_RI_EX_ORG NUMBER(15)) ; 
ALTER TABLE MBT_230 ADD (D_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_230 ADD (C_ACCT_CRED_LINE_ORG NUMBER(15)) ; 
ALTER TABLE MBT_230_HIS ADD (D_RI_EX_ORG NUMBER(15)) ; 
ALTER TABLE MBT_230_HIS ADD (D_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_230_HIS ADD (C_ACCT_CRED_LINE_ORG NUMBER(15)) ; 
ALTER TABLE MBT_230_RPT ADD (D_RI_EX_ORG NUMBER(15)) ; 
ALTER TABLE MBT_230_RPT ADD (D_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_230_RPT ADD (C_ACCT_CRED_LINE_ORG NUMBER(15)) ; 
ALTER TABLE MBT_230_TMP ADD (D_RI_EX_ORG NUMBER(15)) ; 
ALTER TABLE MBT_230_TMP ADD (D_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_230_TMP ADD (C_ACCT_CRED_LINE_ORG NUMBER(15)) ; 
ALTER TABLE MBT_230_TODAY_BAK ADD (D_RI_EX_ORG NUMBER(15)) ; 
ALTER TABLE MBT_230_TODAY_BAK ADD (D_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_230_TODAY_BAK ADD (C_ACCT_CRED_LINE_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_230 ADD (D_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_230 ADD (C_ACCT_CRED_LINE_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_230 ADD (D_RI_EX_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_230_HIS ADD (D_RI_EX_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_230_HIS ADD (D_LOAN_AMT_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_230_HIS ADD (C_ACCT_CRED_LINE_ORG NUMBER(15)) ; 

COMMENT ON COLUMN MBT_230.D_RI_EX_ORG IS '风险敞口_原始数据金额'; 
COMMENT ON COLUMN MBT_230.D_LOAN_AMT_ORG IS '在保余额_原始数据金额'; 
COMMENT ON COLUMN MBT_230.C_ACCT_CRED_LINE_ORG IS '担保金额_原始数据金额'; 
COMMENT ON COLUMN MBT_230_HIS.D_RI_EX_ORG IS '风险敞口_原始数据金额'; 
COMMENT ON COLUMN MBT_230_HIS.D_LOAN_AMT_ORG IS '在保余额_原始数据金额'; 
COMMENT ON COLUMN MBT_230_HIS.C_ACCT_CRED_LINE_ORG IS '担保金额_原始数据金额'; 
COMMENT ON COLUMN MBT_230_RPT.D_RI_EX_ORG IS '风险敞口_原始数据金额'; 
COMMENT ON COLUMN MBT_230_RPT.D_LOAN_AMT_ORG IS '在保余额_原始数据金额'; 
COMMENT ON COLUMN MBT_230_RPT.C_ACCT_CRED_LINE_ORG IS '担保金额_原始数据金额'; 
COMMENT ON COLUMN MBT_230_TMP.D_RI_EX_ORG IS '风险敞口_原始数据金额'; 
COMMENT ON COLUMN MBT_230_TMP.D_LOAN_AMT_ORG IS '在保余额_原始数据金额'; 
COMMENT ON COLUMN MBT_230_TMP.C_ACCT_CRED_LINE_ORG IS '担保金额_原始数据金额'; 
COMMENT ON COLUMN MBT_230_TODAY_BAK.D_RI_EX_ORG IS '风险敞口_原始数据金额'; 
COMMENT ON COLUMN MBT_230_TODAY_BAK.D_LOAN_AMT_ORG IS '在保余额_原始数据金额'; 
COMMENT ON COLUMN MBT_230_TODAY_BAK.C_ACCT_CRED_LINE_ORG IS '担保金额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_230.D_LOAN_AMT_ORG IS '在保余额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_230.C_ACCT_CRED_LINE_ORG IS '担保金额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_230.D_RI_EX_ORG IS '风险敞口_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_230_HIS.D_RI_EX_ORG IS '风险敞口_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_230_HIS.D_LOAN_AMT_ORG IS '在保余额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_230_HIS.C_ACCT_CRED_LINE_ORG IS '担保金额_原始数据金额'; 
-------------------------------------------------------510--------------------------------------------------------------
ALTER TABLE MBT_510 ADD (C_CC_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_510_HIS ADD (C_CC_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_510_RPT ADD (C_CC_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_510_TMP ADD (C_CC_AMT_ORG NUMBER(15)) ; 
ALTER TABLE MBT_510_TODAY_BAK ADD (C_CC_AMT_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_510 ADD (C_CC_AMT_ORG NUMBER(15)) ; 
ALTER TABLE ODS_MBT_510_HIS ADD (C_CC_AMT_ORG NUMBER(15)) ; 

COMMENT ON COLUMN MBT_510.C_CC_AMT_ORG IS '担保金额_原始数据金额'; 
COMMENT ON COLUMN MBT_510_HIS.C_CC_AMT_ORG IS '担保金额_原始数据金额'; 
COMMENT ON COLUMN MBT_510_RPT.C_CC_AMT_ORG IS '担保金额_原始数据金额'; 
COMMENT ON COLUMN MBT_510_TMP.C_CC_AMT_ORG IS '担保金额_原始数据金额'; 
COMMENT ON COLUMN MBT_510_TODAY_BAK.C_CC_AMT_ORG IS '担保金额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_510.C_CC_AMT_ORG IS '担保金额_原始数据金额'; 
COMMENT ON COLUMN ODS_MBT_510_HIS.C_CC_AMT_ORG IS '担保金额_原始数据金额'; 
-------------------------------------------------------210前台页面sql修改--------------------------------------------------------------
UPDATE GP_BM_INQ_CFG SET DATA_DATE=NULL, CORP_ID='TESTCORP', ORG_ID=NULL, GROUP_ID=NULL, NEXT_ACTION=NULL, DATA_STATUS=NULL, DATA_FLAG=NULL, DATA_SOURCE=NULL, CHECK_FLAG=NULL, CHECK_DESC=NULL, CHECK_ERR_TYPE=NULL, DATA_VERSION=NULL, DATA_REJ_DESC=NULL, DATA_DEL_DESC=NULL, DATA_CRT_USER=NULL, DATA_CRT_DATE=NULL, DATA_CRT_TIME=NULL, DATA_CHG_USER=NULL, DATA_CHG_DATE=NULL, DATA_CHG_TIME=NULL, DATA_APV_USER=NULL, DATA_APV_DATE=NULL, DATA_APV_TIME=NULL, RSV1=NULL, RSV2=NULL, RSV3=NULL, RSV4=NULL, RSV5=NULL, REMARK=NULL, SQL_ID='Mbt210Add_Bas', SQL_STRING='select DATA_ID,DATA_DATE,CORP_ID,ORG_ID,GROUP_ID,INQ_ORG_ID,INQ_GROUP_ID,REF_NO,B_INF_REC_TYPE,B_ACCT_TYPE,B_ACCT_CODE,B_RPT_DATE,B_RPT_DATE_CODE,B_NAME,B_ID_TYPE,B_ID_NUM,B_MNGMT_ORG_CODE,C_BUSI_LINES,C_BUSI_DTL_LINES,C_OPEN_DATE,C_CY,C_ACCT_CRED_LINE_AMT,C_ACCT_CRED_LINE_AMT_LCY,C_LOAN_AMT,C_LOAN_AMT_LCY,C_FLAG,C_DUE_DATE,C_REPAY_MODE,C_REPAY_FREQCY,C_REPAY_PRD,C_APPLY_BUSI_DIST,C_GUAR_MODE,C_OTH_REPY_GUAR_WAY,C_ASSET_TRAND_FLAG,C_FUND_SOU,C_LOAN_FORM,C_CREDIT_ID,F_MCC,G_INIT_CRED_NAME,G_INIT_CRED_ORG_NM,G_ORIG_DBT_CATE,G_INIT_RPY_STS,H_MONTH,H_SETT_DATE,H_ACCT_STATUS,H_ACCT_BAL,H_ACCT_BAL_LCY,H_PRID_ACCT_BAL,H_PRID_ACCT_BAL_LCY,H_USED_AMT,H_USED_AMT_LCY,H_NOTLSU_BAL,H_NOTLSU_BAL_LCY,H_REM_REP_PRD,H_FIVE_CATE,H_FIVE_CATE_ADJ_DATE,H_RPY_STATUS,H_RPY_PRCT,H_OVERD_PRD,H_TOT_OVERD,H_TOT_OVERD_LCY,H_OVAER_PRINC,H_OVAER_PRINC_LCY,H_OVERD31_60PRINC,H_OVERD31_60PRINC_LCY,H_OVERD61_90PRINC,H_OVERD61_90PRINC_LCY,H_OVERD91_180PRINC,H_OVERD91_180PRINC_LCY,H_OVERD_PRINC180,H_OVERD_PRINC180_LCY,H_OVERD_RAW_BA_OVE180,H_OVERD_RAW_BA_OVE180_LCY,H_CUR_RPY_AMT,H_CUR_RPY_AMT_LCY,H_ACT_RPY_AMT,H_ACT_RPY_AMT_LCY,H_LAT_RPY_DATE,H_CLOSE_DATE,I_SPEC_LINE,I_SPEC_LINE_LCY,I_SPEC_EFCT_DATE,I_SPEC_END_DATE,I_USED_INST_AMT,I_USED_INST_AMT_LCY,J_ACCT_STATUS,J_ACCT_BAL,J_ACCT_BAL_LCY,J_FIVE_CATE,J_FIVE_CATE_ADJ_DATE,J_REM_REP_PRD,J_RPY_STATUS,J_OVERD_PRD,J_TOT_OVERD,J_TOT_OVERD_LCY,J_LAT_RPY_AMT,J_LAT_RPY_AMT_LCY,J_LAT_RPY_DATE,J_CLOSE_DATE,DATA_DESC,REMARKS,CHECK_FLAG,CHECK_DESC,CHECK_ERR_TYPE,NEXT_ACTION,DATA_STATUS,DATA_FLAG,DATA_SOURCE,DATA_VERSION,DATA_REJ_DESC,DATA_DEL_DESC,DATA_CRT_USER,DATA_CRT_DATE,DATA_CRT_TIME,DATA_CHG_USER,DATA_CHG_DATE,DATA_CHG_TIME,DATA_APV_USER,DATA_APV_DATE,DATA_APV_TIME,RSV1,RSV2,RSV3,RSV4,RSV5,IS_RPT,CUST_NO,MON_SETTLE_DATE,FB_MSG,FB_STATUS,RPT_FILE_NAME,RPT_DATA_ID,FB_DATE,FB_TIME,C_LOAN_CON_CODE,C_FIRST_HOU_LOAN_FLAG,J_LAT_RPY_AMT_ORG, J_TOT_OVERD_ORG, J_ACCT_BAL_ORG, I_USED_INST_AMT_ORG, I_SPEC_LINE_ORG, H_ACT_RPY_AMT_ORG, H_CUR_RPY_AMT_ORG, H_OVERD_RAW_BA_OVE180_ORG, H_OVERD_PRINC180_ORG, H_OVERD91_180PRINC_ORG, H_OVERD61_90PRINC_ORG, H_OVERD31_60PRINC_ORG, H_OVAER_PRINC_ORG, H_TOT_OVERD_ORG, H_NOTLSU_BAL_ORG, H_USED_AMT_ORG, H_PRID_ACCT_BAL_ORG, H_ACCT_BAL_ORG, C_LOAN_AMT_ORG, C_ACCT_CRED_LINE_AMT_ORG  from MBT_210 where DATA_ID=:"dataId"', DETAIL_SQL_STRING=NULL, SYSTEM=NULL WHERE DATA_ID='Mbt210Add_Bas';

UPDATE GP_BM_INQ_CFG SET SQL_STRING='select DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, REF_NO, B_INF_REC_TYPE, B_ACCT_TYPE, B_ACCT_CODE, B_RPT_DATE, B_RPT_DATE_CODE, B_NAME, B_ID_TYPE, B_ID_NUM, B_MNGMT_ORG_CODE, C_BUSI_LINES, C_BUSI_DTL_LINES, C_OPEN_DATE, C_CY, C_ACCT_CRED_LINE_AMT,C_ACCT_CRED_LINE_AMT_LCY, C_LOAN_AMT,C_LOAN_AMT_LCY, C_FLAG, C_DUE_DATE, C_REPAY_MODE, C_REPAY_FREQCY, C_REPAY_PRD, C_APPLY_BUSI_DIST, C_GUAR_MODE, C_OTH_REPY_GUAR_WAY, C_ASSET_TRAND_FLAG, C_FUND_SOU, C_LOAN_FORM, C_CREDIT_ID, F_MCC, G_INIT_CRED_NAME, G_INIT_CRED_ORG_NM, G_ORIG_DBT_CATE, G_INIT_RPY_STS, H_MONTH, H_SETT_DATE, H_ACCT_STATUS, H_ACCT_BAL,H_ACCT_BAL_LCY, H_PRID_ACCT_BAL, H_PRID_ACCT_BAL_LCY,H_USED_AMT,H_USED_AMT_LCY, H_NOTLSU_BAL,H_NOTLSU_BAL_LCY, H_REM_REP_PRD, H_FIVE_CATE, H_FIVE_CATE_ADJ_DATE, H_RPY_STATUS, H_RPY_PRCT, H_OVERD_PRD, H_TOT_OVERD,H_TOT_OVERD_LCY, H_OVAER_PRINC,H_OVAER_PRINC_LCY, H_OVERD31_60PRINC, H_OVERD31_60PRINC_LCY,H_OVERD61_90PRINC,H_OVERD61_90PRINC_LCY, H_OVERD91_180PRINC,H_OVERD91_180PRINC_LCY, H_OVERD_PRINC180,H_OVERD_PRINC180_LCY, H_OVERD_RAW_BA_OVE180,H_OVERD_RAW_BA_OVE180_LCY, H_CUR_RPY_AMT,H_CUR_RPY_AMT_LCY, H_ACT_RPY_AMT, H_ACT_RPY_AMT_LCY,H_LAT_RPY_DATE, H_CLOSE_DATE, I_SPEC_LINE, I_SPEC_LINE_LCY,I_SPEC_EFCT_DATE, I_SPEC_END_DATE, I_USED_INST_AMT,I_USED_INST_AMT_LCY, J_ACCT_STATUS, J_ACCT_BAL, J_ACCT_BAL_LCY,J_FIVE_CATE, J_FIVE_CATE_ADJ_DATE, J_REM_REP_PRD, J_RPY_STATUS, J_OVERD_PRD, J_TOT_OVERD,J_TOT_OVERD_LCY,J_LAT_RPY_AMT,J_LAT_RPY_AMT_LCY, J_LAT_RPY_DATE, J_CLOSE_DATE, DATA_DESC, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, IS_RPT, CUST_NO, MON_SETTLE_DATE,C_LOAN_CON_CODE,C_FIRST_HOU_LOAN_FLAG,J_LAT_RPY_AMT_ORG, J_TOT_OVERD_ORG, J_ACCT_BAL_ORG, I_USED_INST_AMT_ORG, I_SPEC_LINE_ORG, H_ACT_RPY_AMT_ORG, H_CUR_RPY_AMT_ORG, H_OVERD_RAW_BA_OVE180_ORG, H_OVERD_PRINC180_ORG, H_OVERD91_180PRINC_ORG, H_OVERD61_90PRINC_ORG, H_OVERD31_60PRINC_ORG, H_OVAER_PRINC_ORG, H_TOT_OVERD_ORG, H_NOTLSU_BAL_ORG, H_USED_AMT_ORG, H_PRID_ACCT_BAL_ORG, H_ACCT_BAL_ORG, C_LOAN_AMT_ORG, C_ACCT_CRED_LINE_AMT_ORG  from MBT_210_HIS where DATA_ID=:"dataId"' WHERE DATA_ID='Mbt210HisQry_Bas';

UPDATE GP_BM_INQ_CFG SET SQL_STRING='select DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, REF_NO, B_INF_REC_TYPE, B_ACCT_TYPE, B_ACCT_CODE, B_RPT_DATE, B_RPT_DATE_CODE, B_NAME, B_ID_TYPE, B_ID_NUM, B_MNGMT_ORG_CODE, C_BUSI_LINES, C_BUSI_DTL_LINES, C_OPEN_DATE, C_CY, C_ACCT_CRED_LINE_AMT,C_ACCT_CRED_LINE_AMT_LCY, C_LOAN_AMT,C_LOAN_AMT_LCY, C_FLAG, C_DUE_DATE, C_REPAY_MODE, C_REPAY_FREQCY, C_REPAY_PRD, C_APPLY_BUSI_DIST, C_GUAR_MODE, C_OTH_REPY_GUAR_WAY, C_ASSET_TRAND_FLAG, C_FUND_SOU, C_LOAN_FORM, C_CREDIT_ID, F_MCC, G_INIT_CRED_NAME, G_INIT_CRED_ORG_NM, G_ORIG_DBT_CATE, G_INIT_RPY_STS, H_MONTH, H_SETT_DATE, H_ACCT_STATUS, H_ACCT_BAL,H_ACCT_BAL_LCY, H_PRID_ACCT_BAL, H_PRID_ACCT_BAL_LCY,H_USED_AMT,H_USED_AMT_LCY, H_NOTLSU_BAL, H_NOTLSU_BAL_LCY,H_REM_REP_PRD, H_FIVE_CATE, H_FIVE_CATE_ADJ_DATE, H_RPY_STATUS, H_RPY_PRCT, H_OVERD_PRD, H_TOT_OVERD, H_TOT_OVERD_LCY,H_OVAER_PRINC,H_OVAER_PRINC_LCY, H_OVERD31_60PRINC,H_OVERD31_60PRINC_LCY, H_OVERD61_90PRINC,H_OVERD61_90PRINC_LCY, H_OVERD91_180PRINC,H_OVERD91_180PRINC_LCY, H_OVERD_PRINC180,H_OVERD_PRINC180_LCY, H_OVERD_RAW_BA_OVE180, H_OVERD_RAW_BA_OVE180_LCY,H_CUR_RPY_AMT, H_CUR_RPY_AMT_LCY,H_ACT_RPY_AMT,H_ACT_RPY_AMT_LCY, H_LAT_RPY_DATE, H_CLOSE_DATE, I_SPEC_LINE, I_SPEC_LINE_LCY,I_SPEC_EFCT_DATE, I_SPEC_END_DATE, I_USED_INST_AMT,I_USED_INST_AMT_LCY, J_ACCT_STATUS, J_ACCT_BAL,J_ACCT_BAL_LCY, J_FIVE_CATE, J_FIVE_CATE_ADJ_DATE, J_REM_REP_PRD, J_RPY_STATUS, J_OVERD_PRD, J_TOT_OVERD,J_TOT_OVERD_LCY, J_LAT_RPY_AMT,J_LAT_RPY_AMT_LCY,J_LAT_RPY_DATE, J_CLOSE_DATE, DATA_DESC, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, IS_RPT, CUST_NO, MON_SETTLE_DATE,C_LOAN_CON_CODE,C_FIRST_HOU_LOAN_FLAG,J_LAT_RPY_AMT_ORG, J_TOT_OVERD_ORG, J_ACCT_BAL_ORG, I_USED_INST_AMT_ORG, I_SPEC_LINE_ORG, H_ACT_RPY_AMT_ORG, H_CUR_RPY_AMT_ORG, H_OVERD_RAW_BA_OVE180_ORG, H_OVERD_PRINC180_ORG, H_OVERD91_180PRINC_ORG, H_OVERD61_90PRINC_ORG, H_OVERD31_60PRINC_ORG, H_OVAER_PRINC_ORG, H_TOT_OVERD_ORG, H_NOTLSU_BAL_ORG, H_USED_AMT_ORG, H_PRID_ACCT_BAL_ORG, H_ACCT_BAL_ORG, C_LOAN_AMT_ORG, C_ACCT_CRED_LINE_AMT_ORG  from MBT_210_RPT where DATA_ID=:"dataId"' WHERE DATA_ID='Mbt210RptQry_Bas';

INSERT INTO GP_BM_INQ_CFG (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, REMARK, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM) VALUES('Mbt210RptQry_Bas1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Mbt210RptQry_Bas1', 'select DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, REF_NO, B_INF_REC_TYPE, B_ACCT_TYPE, B_ACCT_CODE, B_RPT_DATE, B_RPT_DATE_CODE, B_NAME, B_ID_TYPE, B_ID_NUM, B_MNGMT_ORG_CODE, C_BUSI_LINES, C_BUSI_DTL_LINES, C_OPEN_DATE, C_CY, C_ACCT_CRED_LINE_AMT,C_ACCT_CRED_LINE_AMT_LCY, C_LOAN_AMT,C_LOAN_AMT_LCY, C_FLAG, C_DUE_DATE, C_REPAY_MODE, C_REPAY_FREQCY, C_REPAY_PRD, C_APPLY_BUSI_DIST, C_GUAR_MODE, C_OTH_REPY_GUAR_WAY, C_ASSET_TRAND_FLAG, C_FUND_SOU, C_LOAN_FORM, C_CREDIT_ID, F_MCC, G_INIT_CRED_NAME, G_INIT_CRED_ORG_NM, G_ORIG_DBT_CATE, G_INIT_RPY_STS, H_MONTH, H_SETT_DATE, H_ACCT_STATUS, H_ACCT_BAL,H_ACCT_BAL_LCY, H_PRID_ACCT_BAL,H_PRID_ACCT_BAL_LCY, H_USED_AMT, H_USED_AMT_LCY,H_NOTLSU_BAL,H_NOTLSU_BAL_LCY, H_REM_REP_PRD, H_FIVE_CATE, H_FIVE_CATE_ADJ_DATE, H_RPY_STATUS, H_RPY_PRCT, H_OVERD_PRD, H_TOT_OVERD, H_TOT_OVERD_LCY,H_OVAER_PRINC,H_OVAER_PRINC_LCY, H_OVERD31_60PRINC,H_OVERD31_60PRINC_LCY, H_OVERD61_90PRINC,H_OVERD61_90PRINC_LCY, H_OVERD91_180PRINC, H_OVERD91_180PRINC_LCY,H_OVERD_PRINC180,H_OVERD_PRINC180_LCY, H_OVERD_RAW_BA_OVE180,H_OVERD_RAW_BA_OVE180_LCY, H_CUR_RPY_AMT,H_CUR_RPY_AMT_LCY, H_ACT_RPY_AMT,H_ACT_RPY_AMT_LCY, H_LAT_RPY_DATE, H_CLOSE_DATE, I_SPEC_LINE,I_SPEC_LINE_LCY, I_SPEC_EFCT_DATE, I_SPEC_END_DATE, I_USED_INST_AMT,I_USED_INST_AMT_LCY, J_ACCT_STATUS, J_ACCT_BAL,J_ACCT_BAL_LCY, J_FIVE_CATE, J_FIVE_CATE_ADJ_DATE, J_REM_REP_PRD, J_RPY_STATUS, J_OVERD_PRD, J_TOT_OVERD,J_TOT_OVERD_LCY, J_LAT_RPY_AMT, J_LAT_RPY_AMT_LCY,J_LAT_RPY_DATE, J_CLOSE_DATE, DATA_DESC, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5,  CUST_NO, MON_SETTLE_DATE,C_LOAN_CON_CODE,C_FIRST_HOU_LOAN_FLAG,J_LAT_RPY_AMT_ORG, J_TOT_OVERD_ORG, J_ACCT_BAL_ORG, I_USED_INST_AMT_ORG, I_SPEC_LINE_ORG, H_ACT_RPY_AMT_ORG, H_CUR_RPY_AMT_ORG, H_OVERD_RAW_BA_OVE180_ORG, H_OVERD_PRINC180_ORG, H_OVERD91_180PRINC_ORG, H_OVERD61_90PRINC_ORG, H_OVERD31_60PRINC_ORG, H_OVAER_PRINC_ORG, H_TOT_OVERD_ORG, H_NOTLSU_BAL_ORG, H_USED_AMT_ORG, H_PRID_ACCT_BAL_ORG, H_ACCT_BAL_ORG, C_LOAN_AMT_ORG, C_ACCT_CRED_LINE_AMT_ORG  from MBT_210_TMP where DATA_ID=:"dataId" ', NULL, NULL);

-------------------------------------------------------220前台页面sql修改--------------------------------------------------------------
UPDATE GP_BM_INQ_CFG SET SQL_STRING=' SELECT DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, B_INF_REC_TYPE, B_CONTRACT_CODE, B_RPT_DATE, B_RPT_DATE_CODE, B_NAME, B_ID_TYPE, B_ID_NUM, B_MNGMT_ORG_CODE, B_CONTRACT_NO, D_CREDIT_LIM_TYPE, D_LIM_LOOP_FLG, D_CREDIT_LIM,D_CREDIT_LIM_LCY, D_CY, D_CON_EFF_DATE, D_CON_EXP_DATE, D_CON_STATUS, D_CREDIT_REST, D_CREDIT_REST_LCY,D_CREDIT_REST_CODE, F_DATA_DESC, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, CUST_NO, IS_RPT, FB_STATUS, RPT_FILE_NAME, FB_MSG, RPT_DATA_ID, FB_DATE, FB_TIME,D_CREDIT_REST_ORG,D_CREDIT_LIM_ORG FROM MBT_220 where DATA_ID=:"dataId"' WHERE DATA_ID='Mbt220Add_Bas';

UPDATE GP_BM_INQ_CFG SET SQL_STRING='SELECT DATA_ID,DATA_SOURCE,DATA_STATUS, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME,CUST_NO,B_INF_REC_TYPE,B_CONTRACT_CODE,B_RPT_DATE,B_RPT_DATE_CODE,B_NAME,B_ID_TYPE,B_ID_NUM,B_MNGMT_ORG_CODE,B_CONTRACT_NO,D_CREDIT_LIM_TYPE,D_LIM_LOOP_FLG,D_CREDIT_LIM,D_CREDIT_LIM_LCY,D_CY,D_CON_EFF_DATE,D_CON_EXP_DATE,D_CON_STATUS,D_CREDIT_REST,D_CREDIT_REST_LCY,D_CREDIT_REST_CODE,F_DATA_DESC,D_CREDIT_REST_ORG,D_CREDIT_LIM_ORG FROM MBT_220_HIS where DATA_ID=:"dataId"' WHERE DATA_ID='Mbt220HisQry_Bas';

UPDATE GP_BM_INQ_CFG SET SQL_STRING='SELECT DATA_ID,DATA_SOURCE,DATA_STATUS, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME,CUST_NO,B_INF_REC_TYPE,B_CONTRACT_CODE,B_RPT_DATE,B_RPT_DATE_CODE,B_NAME,B_ID_TYPE,B_ID_NUM,B_MNGMT_ORG_CODE,B_CONTRACT_NO,D_CREDIT_LIM_TYPE,D_LIM_LOOP_FLG,D_CREDIT_LIM,D_CREDIT_LIM_LCY,D_CY,D_CON_EFF_DATE,D_CON_EXP_DATE,D_CON_STATUS,D_CREDIT_REST,D_CREDIT_REST_LCY,D_CREDIT_REST_CODE,F_DATA_DESC,D_CREDIT_REST_ORG,D_CREDIT_LIM_ORG FROM MBT_220_RPT where DATA_ID=:"dataId" union all SELECT DATA_ID,DATA_SOURCE,DATA_STATUS, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME,CUST_NO,B_INF_REC_TYPE,B_CONTRACT_CODE,B_RPT_DATE,B_RPT_DATE_CODE,B_NAME,B_ID_TYPE,B_ID_NUM,B_MNGMT_ORG_CODE,B_CONTRACT_NO,D_CREDIT_LIM_TYPE,D_LIM_LOOP_FLG,D_CREDIT_LIM,D_CREDIT_LIM_LCY,D_CY,D_CON_EFF_DATE,D_CON_EXP_DATE,D_CON_STATUS,D_CREDIT_REST,D_CREDIT_REST_LCY,D_CREDIT_REST_CODE,F_DATA_DESC,D_CREDIT_REST_ORG,D_CREDIT_LIM_ORG FROM MBT_220_TMP where DATA_ID=:"dataId"' WHERE DATA_ID='Mbt220RptQry_Bas';
-------------------------------------------------------230前台页面sql修改--------------------------------------------------------------
UPDATE GP_BM_INQ_CFG SET SQL_STRING=' select  DATA_ID,DATA_DATE,CORP_ID,ORG_ID,GROUP_ID,INQ_ORG_ID,INQ_GROUP_ID,B_ACCT_TYPE,B_ACCT_CODE,B_RPT_DATE,B_RPT_DATE_CODE,B_INF_REC_TYPE,B_NAME,B_ID_TYPE,B_ID_NUM,B_MNGMT_ORG_CODE,B_CUST_NO,C_BUSI_LINES,C_BUSI_DTIL_LINES,C_OPEN_DATE,C_ACCT_CRED_LINE,C_ACCT_CRED_LINE_LCY,C_CY,C_DUE_DATE,C_GUAR_MODE,C_OTH_REPY_GUAR_WAY,C_SEC_DEP,C_CTRCT_TXT_CD,D_ACCT_STATUS,D_LOAN_AMT,D_LOAN_AMT_LCY,D_REPAY_PRD,D_FIVE_CATE,D_FIVE_CATE_ADJ_DATE,D_RI_EX,D_RI_EX_LCY,D_COMP_ADV_FLAG,D_CLOSE_DATE,CHECK_FLAG,CHECK_DESC,CHECK_ERR_TYPE,NEXT_ACTION,DATA_STATUS,DATA_FLAG,DATA_SOURCE,DATA_VERSION,DATA_REJ_DESC,DATA_DEL_DESC,DATA_CRT_USER,DATA_CRT_DATE,DATA_CRT_TIME,DATA_CHG_USER,DATA_CHG_DATE,DATA_CHG_TIME,DATA_APV_USER,DATA_APV_DATE,DATA_APV_TIME,REF_NO,DATA_DESC,RSV1,RSV2,RSV3,RSV4,RSV5,INF_REC_TYPE,IS_RPT,FB_MSG,FB_STATUS,RPT_FILE_NAME,RPT_DATA_ID,FB_DATE,FB_TIME,D_RI_EX_ORG,D_LOAN_AMT_ORG,C_ACCT_CRED_LINE_ORG from MBT_230 where data_id=:"dataId"' WHERE DATA_ID='MBT230Add_Bas';

UPDATE GP_BM_INQ_CFG SET SQL_STRING='select DATA_SOURCE, DATA_ID,DATA_STATUS, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME,B_NAME,B_ID_TYPE,B_INF_REC_TYPE,B_ID_NUM,B_RPT_DATE,B_RPT_DATE_CODE,B_ACCT_CODE,B_ACCT_TYPE,B_MNGMT_ORG_CODE,B_CUST_NO,C_BUSI_LINES,C_OPEN_DATE,C_ACCT_CRED_LINE,C_ACCT_CRED_LINE_LCY,C_CY,C_OTH_REPY_GUAR_WAY,C_DUE_DATE,C_BUSI_DTIL_LINES,C_GUAR_MODE,C_SEC_DEP,C_CTRCT_TXT_CD,D_ACCT_STATUS,D_LOAN_AMT,D_LOAN_AMT_LCY,D_REPAY_PRD ,D_FIVE_CATE ,D_FIVE_CATE_ADJ_DATE,D_RI_EX,D_RI_EX_LCY,D_COMP_ADV_FLAG,D_CLOSE_DATE,D_RI_EX_ORG,D_LOAN_AMT_ORG,C_ACCT_CRED_LINE_ORG from MBT_230_HIS where data_id=:"dataId"' WHERE DATA_ID='MBT230HisQry_Bas';

UPDATE GP_BM_INQ_CFG SET SQL_STRING='select DATA_SOURCE, DATA_ID,DATA_STATUS, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME,B_NAME,B_ID_TYPE,B_INF_REC_TYPE,B_ID_NUM,B_RPT_DATE,B_RPT_DATE_CODE,B_ACCT_CODE,B_ACCT_TYPE,B_MNGMT_ORG_CODE,B_CUST_NO,C_BUSI_LINES,C_OPEN_DATE,C_ACCT_CRED_LINE,C_ACCT_CRED_LINE_LCY,C_CY,C_OTH_REPY_GUAR_WAY,C_DUE_DATE,C_BUSI_DTIL_LINES,C_GUAR_MODE,C_SEC_DEP,C_CTRCT_TXT_CD,D_ACCT_STATUS,D_LOAN_AMT,D_LOAN_AMT_LCY,D_REPAY_PRD ,D_FIVE_CATE ,D_FIVE_CATE_ADJ_DATE,D_RI_EX,D_RI_EX_LCY,D_COMP_ADV_FLAG,D_CLOSE_DATE,D_RI_EX_ORG,D_LOAN_AMT_ORG,C_ACCT_CRED_LINE_ORG from MBT_230_RPT where data_id=:"dataId" union all select DATA_SOURCE, DATA_ID,DATA_STATUS, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME,B_NAME,B_ID_TYPE,B_INF_REC_TYPE,B_ID_NUM,B_RPT_DATE,B_RPT_DATE_CODE,B_ACCT_CODE,B_ACCT_TYPE,B_MNGMT_ORG_CODE,B_CUST_NO,C_BUSI_LINES,C_OPEN_DATE,C_ACCT_CRED_LINE,C_ACCT_CRED_LINE_LCY,C_CY,C_OTH_REPY_GUAR_WAY,C_DUE_DATE,C_BUSI_DTIL_LINES,C_GUAR_MODE,C_SEC_DEP,C_CTRCT_TXT_CD,D_ACCT_STATUS,D_LOAN_AMT,D_LOAN_AMT_LCY,D_REPAY_PRD ,D_FIVE_CATE ,D_FIVE_CATE_ADJ_DATE,D_RI_EX,D_RI_EX_LCY,D_COMP_ADV_FLAG,D_CLOSE_DATE,D_RI_EX_ORG,D_LOAN_AMT_ORG,C_ACCT_CRED_LINE_ORG from MBT_230_TMP where data_id=:"dataId" ' WHERE DATA_ID='MBT230RptQry_Bas';
-------------------------------------------------------510前台页面sql修改--------------------------------------------------------------
UPDATE GP_BM_INQ_CFG SET SQL_STRING=' select RPT_DATA_ID ,FB_DATE ,FB_STATUS ,RPT_FILE_NAME ,FB_MSG ,FB_TIME,DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, B_INF_REC_NO, B_INF_REC_TYPE, B_CC_CODE, B_RPT_DATE, B_RPT_DATE_CODE, B_INFO_ID_TYPE, B_NAME, B_CERT_TYPE, B_CERT_NUM, B_MNGMT_ORG_CODE, B_CUST_NO, C_GUAR_TYPE, C_CC_AMT,C_CC_AMT_LCY, C_CY, C_CC_VAL_DATE, C_CC_EXP_DATE, C_MAX_GUAR, C_CC_STATUS, G_DATA_DESC, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5,CUST_TYPE,C_CC_AMT_ORG from MBT_510 where 1=1 and DATA_ID=:"dataId" and CORP_ID=:"v_corpid"' WHERE DATA_ID='Mbt510Add_Bas_ds';

UPDATE GP_BM_INQ_CFG SET SQL_STRING='select DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, B_INF_REC_NO, B_INF_REC_TYPE, B_CC_CODE, B_RPT_DATE, B_RPT_DATE_CODE, B_INFO_ID_TYPE, B_NAME, B_CERT_TYPE, B_CERT_NUM, B_MNGMT_ORG_CODE, B_CUST_NO, C_GUAR_TYPE, C_CC_AMT,C_CC_AMT_LCY, C_CY, C_CC_VAL_DATE, C_CC_EXP_DATE, C_MAX_GUAR, C_CC_STATUS, G_DATA_DESC, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5,C_CC_AMT_ORG  from MBT_510_HIS where 1=1 and DATA_ID=:"dataId" ' WHERE DATA_ID='Mbt510HisQry_Bas_ds';

UPDATE GP_BM_INQ_CFG SET SQL_STRING='select DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, B_INF_REC_NO, B_INF_REC_TYPE, B_CC_CODE, B_RPT_DATE, B_RPT_DATE_CODE, B_INFO_ID_TYPE, B_NAME, B_CERT_TYPE, B_CERT_NUM, B_MNGMT_ORG_CODE, B_CUST_NO, C_GUAR_TYPE, C_CC_AMT, C_CC_AMT_LCY,C_CY, C_CC_VAL_DATE, C_CC_EXP_DATE, C_MAX_GUAR, C_CC_STATUS, G_DATA_DESC, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5,C_CC_AMT_ORG  from MBT_510_RPT where 1=1 and DATA_ID=:"dataId" union all select DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, B_INF_REC_NO, B_INF_REC_TYPE, B_CC_CODE, B_RPT_DATE, B_RPT_DATE_CODE, B_INFO_ID_TYPE, B_NAME, B_CERT_TYPE, B_CERT_NUM, B_MNGMT_ORG_CODE, B_CUST_NO, C_GUAR_TYPE, C_CC_AMT, C_CC_AMT_LCY,C_CY, C_CC_VAL_DATE, C_CC_EXP_DATE, C_MAX_GUAR, C_CC_STATUS, G_DATA_DESC, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5,C_CC_AMT_ORG  from MBT_510_TMP where 1=1 and DATA_ID=:"dataId" ' WHERE DATA_ID='Mbt510RptQry_Bas_ds';

-------------------------------------------------------新增表结构--------------------------------------------------------------


-- MBT_USER.GP_BM_EXCHANGE_RATE definition

CREATE TABLE "GP_BM_EXCHANGE_RATE" 
   (	"DATA_ID" CHAR(32) NOT NULL ENABLE, 
	"ER_DATE" CHAR(8) NOT NULL ENABLE, 
	"ORI_CCY" CHAR(3) NOT NULL ENABLE, 
	"OBV_CCY" CHAR(3) DEFAULT 'CNY' NOT NULL ENABLE, 
	"UNIT" NUMBER(10,0) DEFAULT 1 NOT NULL ENABLE, 
	"EXCHANGE_RATE" NUMBER(12,6) NOT NULL ENABLE, 
	"DATA_CHG_DATE" CHAR(8), 
	"DATA_CHG_TIME" CHAR(14), 
	"RSV1" VARCHAR2(180), 
	"RSV2" VARCHAR2(181), 
	"RSV3" VARCHAR2(182), 
	"RSV4" VARCHAR2(183), 
	"RSV5" VARCHAR2(184), 
	 CONSTRAINT "GP_BM_EXCHANGE_RATE_PK" PRIMARY KEY ("DATA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MBT_USER_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MBT_USER_TBS" ;

   COMMENT ON COLUMN "GP_BM_EXCHANGE_RATE"."DATA_ID" IS '数据ID';
   COMMENT ON COLUMN "GP_BM_EXCHANGE_RATE"."ER_DATE" IS '汇率日期';
   COMMENT ON COLUMN "GP_BM_EXCHANGE_RATE"."ORI_CCY" IS '原币币种';
   COMMENT ON COLUMN "GP_BM_EXCHANGE_RATE"."OBV_CCY" IS '折算币种';
   COMMENT ON COLUMN "GP_BM_EXCHANGE_RATE"."UNIT" IS '单位';
   COMMENT ON COLUMN "GP_BM_EXCHANGE_RATE"."EXCHANGE_RATE" IS '汇率';
   COMMENT ON COLUMN "GP_BM_EXCHANGE_RATE"."DATA_CHG_DATE" IS '数据修改/删除日期';
   COMMENT ON COLUMN "GP_BM_EXCHANGE_RATE"."DATA_CHG_TIME" IS '数据修改/删除时间';
   COMMENT ON COLUMN "GP_BM_EXCHANGE_RATE"."RSV1" IS '备用1';
   COMMENT ON COLUMN "GP_BM_EXCHANGE_RATE"."RSV2" IS '备用2';
   COMMENT ON COLUMN "GP_BM_EXCHANGE_RATE"."RSV3" IS '备用3';
   COMMENT ON COLUMN "GP_BM_EXCHANGE_RATE"."RSV4" IS '备用4';
   COMMENT ON COLUMN "GP_BM_EXCHANGE_RATE"."RSV5" IS '备用5';


   CREATE TABLE "GP_BM_EXCHANGE_RATE_AMT" 
   (	"DATA_ID" VARCHAR2(32) NOT NULL ENABLE, 
	"TABLE_NAME" VARCHAR2(64), 
	"ORG_NAME" VARCHAR2(64), 
	"LCY_NAME" VARCHAR2(64), 
	"NAME" VARCHAR2(64), 
	 PRIMARY KEY ("DATA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MBT_USER_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MBT_USER_TBS" ;
-------------------------------------------------------插入表数据--------------------------------------------------------------
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248849', 'Mbt210', 'cAcctCredLineAmtOrg', 'cAcctCredLineAmtLcy', 'cAcctCredLineAmt');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248850', 'Mbt210', 'cLoanAmtOrg', 'cLoanAmtLcy', 'cLoanAmt');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248851', 'Mbt210', 'hAcctBalOrg', 'hAcctBalLcy', 'hAcctBal');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248852', 'Mbt210', 'hPridAcctBalOrg', 'hPridAcctBalLcy', 'hPridAcctBal');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248853', 'Mbt210', 'hUsedAmtOrg', 'hUsedAmtLcy', 'hUsedAmt');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248854', 'Mbt210', 'hNotlsuBalOrg', 'hNotlsuBalLcy', 'hNotlsuBal');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248855', 'Mbt210', 'hTotOverdOrg', 'hTotOverdLcy', 'hTotOverd');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248856', 'Mbt210', 'hOvaerPrincOrg', 'hOvaerPrincLcy', 'hOvaerPrinc');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248857', 'Mbt210', 'hOverd3160princOrg', 'hOverd3160princLcy', 'hOverd3160princ');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248858', 'Mbt210', 'hOverd6190princOrg', 'hOverd6190princLcy', 'hOverd6190princ');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248859', 'Mbt210', 'hOverd91180princOrg', 'hOverd91180princLcy', 'hOverd91180princ');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248860', 'Mbt210', 'hOverdPrinc180Org', 'hOverdPrinc180Lcy', 'hOverdPrinc180');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248861', 'Mbt210', 'hOverdRawBaOve180Org', 'hOverdRawBaOve180Lcy', 'hOverdRawBaOve180');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248862', 'Mbt210', 'hCurRpyAmtOrg', 'hCurRpyAmtLcy', 'hCurRpyAmt');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248863', 'Mbt210', 'hActRpyAmtOrg', 'hActRpyAmtLcy', 'hActRpyAmt');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248864', 'Mbt210', 'iSpecLineOrg', 'iSpecLineLcy', 'iSpecLine');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248865', 'Mbt210', 'iUsedInstAmtOrg', 'iUsedInstAmtLcy', 'iUsedInstAmt');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248866', 'Mbt210', 'jAcctBalOrg', 'jAcctBalLcy', 'jAcctBal');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248867', 'Mbt210', 'jTotOverdOrg', 'jTotOverdLcy', 'jTotOverd');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248868', 'Mbt210', 'jLatRpyAmtOrg', 'jLatRpyAmtLcy', 'jLatRpyAmt');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2020042500000000000000013248868', 'Mbt510', 'cCcAmtOrg', 'cCcAmtLcy', 'cCcAmt');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248869', 'Mbt220', 'dCreditLimOrg', 'dCreditLimLcy', 'dCreditLim');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248870', 'Mbt220', 'dCreditRestOrg', 'dCreditRestLcy', 'dCreditRest');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248871', 'Mbt230', 'dRiExOrg', 'dRiExLcy', 'dRiEx');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248872', 'Mbt230', 'dLoanAmtOrg', 'dLoanAmtLcy', 'dLoanAmt');
INSERT INTO GP_BM_EXCHANGE_RATE_AMT (DATA_ID, TABLE_NAME, ORG_NAME, LCY_NAME, NAME) VALUES('
2019042500000000000000013248873', 'Mbt230', 'cAcctCredLineOrg', 'cAcctCredLineLcy', 'cAcctCredLine');


