prompt Importing table GP_BM_EXPORT_FUNCTION...
set feedback off
set define off
insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('095308c7516a49f5a2b678296b4c4f92', null, null, null, null, null, null, '201801025', '企业身份标识整合信息上报数据查询', null, null, '095308c7516a49f5a2b678296b4c4f92', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_企业身份标识整合信息上报数据查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('b3575bbacef044859696bccdcc0f7d23', null, null, null, null, null, null, '201801055', '企业基本信息上报变更处理查询', null, null, 'b3575bbacef044859696bccdcc0f7d23', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_企业基本信息上报变更处理查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('f8de4658de794748be65c69898a64f60', null, null, null, null, null, null, '1700608', '企业基本上报查询', null, null, 'f8de4658de794748be65c69898a64f60', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_企业基本上报查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('46582827a198446cb9ba440f051ea092', null, null, null, null, null, null, '201801035', '企业间关联关系信息上报数据查询', null, null, '46582827a198446cb9ba440f051ea092', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_企业间关联关系信息上报数据查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('22493a55a40c4b1d903e66accb33fd72', null, null, null, null, null, null, '201801043', '企业基本信息变更申请查询', null, null, '22493a55a40c4b1d903e66accb33fd72', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_企业基本信息变更申请查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('e615195918e340f4a764a57327629040', null, null, null, null, null, null, '201802025', '企业借贷标识变更上报数据查询', null, null, 'e615195918e340f4a764a57327629040', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '	ExcelTemplate_企业借贷标识变更上报数据查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('33307b4818d24ef48db0cbaafedddf8d', null, null, null, null, null, null, '201802033', '企业借贷信息变更申请查询', null, null, '33307b4818d24ef48db0cbaafedddf8d', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '	ExcelTemplate_企业借贷信息变更申请查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('79b9bc53d6e945818a7fea962f277b98', null, null, null, null, null, null, '1700105', '企业借贷上报查询', null, null, '79b9bc53d6e945818a7fea962f277b98', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_企业借贷上报查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('9e0468d368614d5cb4126a6b6b45749d', null, null, null, null, null, null, '2018020405', '企业借贷信息上报变更处理查询', null, null, '9e0468d368614d5cb4126a6b6b45749d', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '	ExcelTemplate_企业借贷信息上报变更处理查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('b5d10df2b49946e0b0cf21d8dff45c21', null, null, null, null, null, null, '17004012', '标识变更类请求记录上报', null, null, 'b5d10df2b49946e0b0cf21d8dff45c21', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '	ExcelTemplate_标识变更类请求记录上报.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('aa0da2324d484ca4a412a11342125f53', null, null, null, null, null, null, '17004010', '企业担保信息变更申请审核', null, null, 'aa0da2324d484ca4a412a11342125f53', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '	ExcelTemplate_企业担保信息变更申请审核.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('6fcbd247998c47f088c3c748c9dd3bb0', null, null, null, null, null, null, '2019010405', '企业担保信息上报变更处理查询', null, null, '6fcbd247998c47f088c3c748c9dd3bb0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '	ExcelTemplate_企业担保信息上报变更处理查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('82bf78f7bc0f44f0ad22ca830da87c37', null, null, null, null, null, null, '1700405', '企业担保上报查询', null, null, '82bf78f7bc0f44f0ad22ca830da87c37', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '	ExcelTemplate_企业担保上报查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('9214c3f48d2f431ea4134b3914008e27', null, null, null, null, null, null, '1700710', '标识变更类请求记录上报查询', null, null, '9214c3f48d2f431ea4134b3914008e27', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '	ExcelTemplate_标识变更类请求记录上报查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('486fd4d5b42a406d9580ff4dea6f96f3', null, null, null, null, null, null, '1700705', '企业授信上报查询', null, null, '486fd4d5b42a406d9580ff4dea6f96f3', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_企业授信上报查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('a57e8146002b46b0b3f07f5e68419c59', null, null, null, null, null, null, '1700716', '企业授信协议变更申请查询', null, null, 'a57e8146002b46b0b3f07f5e68419c59', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_企业授信协议变更申请查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('8d096287da374fa484d61b3d3e3c16e2', null, null, null, null, null, null, '1700718', '企业授信协议上报变更申请查询', null, null, '8d096287da374fa484d61b3d3e3c16e2', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_企业授信协议上报变更申请查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('787fd9961fb5424cb75614691fcc8e97', null, null, null, null, null, null, '1700545', '企业抵(质)押信息上报变更处理查询', null, null, '787fd9961fb5424cb75614691fcc8e97', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ExcelTemplate_企业抵(质)押信息上报变更处理查询.xlsx', 'XLS', 'onlyExport');

insert into GP_BM_EXPORT_FUNCTION (DATA_ID, DATA_DATE, CORP_ID, ORG_ID, GROUP_ID, INQ_ORG_ID, INQ_GROUP_ID, FUNCTION_ID, FUNCTION_NAME, STRATEGY_ID, STRATEGY_DESC, GUID, REMARKS, CHECK_FLAG, CHECK_DESC, CHECK_ERR_TYPE, NEXT_ACTION, DATA_STATUS, DATA_FLAG, DATA_SOURCE, DATA_VERSION, DATA_REJ_DESC, DATA_DEL_DESC, DATA_CRT_USER, DATA_CRT_DATE, DATA_CRT_TIME, DATA_CHG_USER, DATA_CHG_DATE, DATA_CHG_TIME, DATA_APV_USER, DATA_APV_DATE, DATA_APV_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, FILE_NAME, EXPORT_FILE_TYPE, EXPORT_STRATEGY_TYPE)
values ('f1e3e28fc8d94c61be1a5c186dbdc3c2', null, null, null, null, null, null, '1700523', '企业抵(质)押信息变更申请查询', null, null, 'f1e3e28fc8d94c61be1a5c186dbdc3c2', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '	ExcelTemplate_企业抵(质)押信息变更申请查询.xlsx', 'XLS', 'onlyExport');

prompt Done.
